Repository elastic/elasticsearch, pull requests merged in 2021-11, with the labels that each got.

#80119 [CI] Mute MultiVersionRepositoryAccessIT failures
  qa/repository-multi-version/src/test/java/org/elasticsearch/upgrades/MultiVersionRepositoryAccessIT.java
Labels: v8.0.0, >test-mute, auto-backport-and-merge, v8.1.0

#80065 Unmute GeoIpDownloaderIT#testInvalidTimestamp() test.
  modules/ingest-geoip/src/internalClusterTest/java/org/elasticsearch/ingest/geoip/GeoIpDownloaderIT.java
Labels: >non-issue, :Data Management/Ingest, Team:Data Management, v8.1.0

#80120 [8.0] [CI] Mute MultiVersionRepositoryAccessIT failures (#80119)
  qa/repository-multi-version/src/test/java/org/elasticsearch/upgrades/MultiVersionRepositoryAccessIT.java
Labels: backport, v8.0.0, auto-merge

#80122 Fix InternalDistributionBwcSetupPluginFuncTest
  build-tools-internal/src/integTest/groovy/org/elasticsearch/gradle/internal/InternalDistributionBwcSetupPluginFuncTest.groovy
  build-tools-internal/src/integTest/resources/org/elasticsearch/gradle/internal/fake_git/remote/build-tools-internal/src/main/resources/minimumCompilerVersion
  build-tools-internal/src/integTest/resources/org/elasticsearch/gradle/internal/fake_git/remote/buildSrc/src/main/resources/minimumCompilerVersion
Labels: >enhancement, :Delivery/Build, Team:Delivery, auto-merge, v8.1.0

#79899 Fix IndexShardTests#testRestoreLocalHistoryFromTranslogOnPromotion
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: >test, :Distributed/Engine, v8.0.0, Team:Distributed, auto-backport, v7.16.0, v8.1.0

#80126 [CI] Mute RestSqlIT::testAsyncTextPaginated
  x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java
Labels: v8.0.0, >test-mute, auto-merge, auto-backport-and-merge, v8.1.0

#80128 [CI] Mute PackageUpgradeTests::test20InstallUpgradedVersion
  qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java
Labels: >test-mute, auto-merge, v8.1.0

#80127 [8.0] Mute RestSqlIT::testAsyncTextPaginated (#80126)
  x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java
Labels: backport, v8.0.0, auto-merge

#80096 [ML] provide a better error when user attempts to infer a model that must be deployed
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/TrainedModelConfig.java
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/PyTorchModelIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/loadingservice/ModelLoadingService.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/loadingservice/ModelLoadingServiceTests.java
Labels: >non-issue, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0

#80123 [8.0] Fix IndexShardTests#testRestoreLocalHistoryFromTranslogOnPromotion (#79899)
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: backport, v8.0.0

#80124 [7.16] Fix IndexShardTests#testRestoreLocalHistoryFromTranslogOnPromotion (#79899)
  server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java
Labels: backport, v7.16.1

#80079 Fix race condition in XPackUsageRestCancellationIT
  x-pack/plugin/core/src/internalClusterTest/java/org/elasticsearch/xpack/core/rest/action/XPackUsageRestCancellationIT.java
Labels: >test, :Distributed/Task Management, v8.0.0, Team:Distributed, v7.16.0, v8.1.0

#80048 [ML] removing allow_no_[datafeeds|jobs] from v8 APIs
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.ml_datafeeds.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.ml_jobs.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.close_job.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.get_datafeed_stats.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.get_datafeeds.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.get_job_stats.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.get_jobs.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.get_overall_buckets.json
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/MachineLearningField.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/CloseJobAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetDatafeedsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetDatafeedsStatsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetJobsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetJobsStatsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetOverallBucketsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/StopDatafeedAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/RestCompatibilityChecker.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/cat/RestCatDatafeedsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/cat/RestCatJobsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/datafeeds/RestGetDatafeedStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/datafeeds/RestGetDatafeedsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/datafeeds/RestStopDatafeedAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/job/RestCloseJobAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/job/RestGetJobStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/job/RestGetJobsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/results/RestGetOverallBucketsAction.java
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/datafeeds_crud.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/get_datafeed_stats.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/jobs_crud.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/jobs_get_result_overall_buckets.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/jobs_get_stats.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/start_stop_datafeed.yml
Labels: >breaking, :ml, v8.0.0, Team:Clients, auto-backport-and-merge, v8.1.0

#79391 [DOCS] Update audit events
  x-pack/docs/en/security/auditing/event-types.asciidoc
Labels: >docs, v8.0.0, Team:Docs, v7.16.0, auto-backport-and-merge, v7.15.2, v8.1.0

#80131 [8.0] [ML] provide a better error when user attempts to infer a model that must be deployed (#80096)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/TrainedModelConfig.java
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/InferenceIngestIT.java
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/PyTorchModelIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/loadingservice/ModelLoadingService.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/loadingservice/ModelLoadingServiceTests.java
Labels: backport, v8.0.0, auto-merge

#80133 [8.0] Fix race condition in XPackUsageRestCancellationIT (#80079)
  x-pack/plugin/core/src/internalClusterTest/java/org/elasticsearch/xpack/core/rest/action/XPackUsageRestCancellationIT.java
Labels: backport, v8.0.0

#80134 [8.0] [ML] removing allow_no_[datafeeds|jobs] from v8 APIs (#80048)
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.ml_datafeeds.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.ml_jobs.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.close_job.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.get_datafeed_stats.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.get_datafeeds.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.get_job_stats.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.get_jobs.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ml.get_overall_buckets.json
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/MachineLearningField.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/CloseJobAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetDatafeedsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetDatafeedsStatsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetJobsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetJobsStatsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetOverallBucketsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/StopDatafeedAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/RestCompatibilityChecker.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/cat/RestCatDatafeedsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/cat/RestCatJobsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/datafeeds/RestGetDatafeedStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/datafeeds/RestGetDatafeedsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/datafeeds/RestStopDatafeedAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/job/RestCloseJobAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/job/RestGetJobStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/job/RestGetJobsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/rest/results/RestGetOverallBucketsAction.java
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/datafeeds_crud.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/get_datafeed_stats.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/jobs_crud.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/jobs_get_result_overall_buckets.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/jobs_get_stats.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/start_stop_datafeed.yml
Labels: backport, v8.0.0, auto-merge

#80138 [7.15] [DOCS] Update audit events (#79391)
  x-pack/docs/en/security/auditing/event-types.asciidoc
Labels: backport, auto-merge, v7.15.2

#80105 [ML] provide nicer errors on _infer with missing model
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/PyTorchModelIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportInferTrainedModelDeploymentAction.java
Labels: >non-issue, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0

#80136 [8.0] [DOCS] Update audit events (#79391)
  x-pack/docs/en/security/auditing/event-types.asciidoc
Labels: backport, v8.0.0, auto-merge

#80141 [CI] Mute failing RestGetSnapshotsIT::testSortAndPaginateWithInProgress
  qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java
Labels: >test-mute, auto-merge, v7.16.1

#80137 [7.16] [DOCS] Update audit events (#79391)
  x-pack/docs/en/security/auditing/event-types.asciidoc
Labels: backport, auto-merge, v7.16.1

#79954 Remove `createParser` variant
  libs/x-content/src/main/java/org/elasticsearch/xcontent/XContent.java
  test/framework/src/main/java/org/elasticsearch/common/logging/JsonLogsStream.java
  x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateGenerateTool.java
  x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/CertificateTool.java
  x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/NdJsonTextStructureFinderFactory.java
Labels: >non-issue, :Core/Infra/Core, Team:Core/Infra, v8.1.0

#80143 [8.0] [ML] provide nicer errors on _infer with missing model (#80105)
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/PyTorchModelIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportInferTrainedModelDeploymentAction.java
Labels: backport, v8.0.0, auto-merge

#79401 Add cluster UUID and name to audit logs
  x-pack/plugin/core/src/main/config/log4j2.properties
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/audit/logfile/AuditTrailSettingsUpdateTests.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/logfile/LoggingAuditTrail.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/test/SecuritySettingsSource.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/audit/logfile/LoggingAuditTrailFilterTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/audit/logfile/LoggingAuditTrailTests.java
Labels: >enhancement, :Security/Audit, v8.0.0, Team:Security, auto-backport, v7.16.1

#80097 Fix Snapshot BwC Version for WRITER_UUIDs
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
Labels: >non-issue, :Distributed/Snapshot/Restore, v8.0.0, Team:Distributed, v8.1.0

#80151 [7.16] [CI] Mute MultiVersionRepositoryAccessIT failures (#80119)
  qa/repository-multi-version/src/test/java/org/elasticsearch/upgrades/MultiVersionRepositoryAccessIT.java
Labels: backport, auto-merge, v7.16.1

#80098 [ML] Add the number of queue requests per node to deployment stats
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetDeploymentStatsAction.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/action/GetDeploymentStatsActionResponseTests.java
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/PyTorchModelIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportGetDeploymentStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/ModelStats.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/pytorch/process/PyTorchResultProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/ProcessWorkerExecutorService.java
Labels: >non-issue, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0

#79965 [8.0] Do not allow shadowing metrics or dimensions (#79757)
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/05_dimension_and_metric_in_non_tsdb_index.yml
  server/src/main/java/org/elasticsearch/index/mapper/MappingLookup.java
  server/src/main/java/org/elasticsearch/index/query/SearchExecutionContext.java
  server/src/test/java/org/elasticsearch/index/mapper/MappingLookupTests.java
Labels: backport, v8.0.0, auto-merge

#79977 [DOCS] Deprecate monitoring settings
  docs/reference/monitoring/collecting-monitoring-data.asciidoc
  docs/reference/settings/monitoring-settings.asciidoc
Labels: >docs, :Data Management/Monitoring, Team:Data Management, Team:Docs, v7.16.1, v8.1.0, v8.0.0-beta1

#79978 [8.0][DOCS] Deprecate monitoring settings
  docs/reference/monitoring/collecting-monitoring-data.asciidoc
  docs/reference/settings/monitoring-settings.asciidoc
Labels: backport, v8.0.0

#79976 [7.16][DOCS] Deprecate monitoring settings
  docs/reference/monitoring/collecting-monitoring-data.asciidoc
  docs/reference/settings/monitoring-settings.asciidoc
Labels: backport

#80155 [DOCS] Adds breaking change for allow_no_datafeeds and allow_no_jobs
  docs/reference/migration/migrate_8_0/api.asciidoc
Labels: >docs, :ml, v8.0.0, Team:Docs, Team:ML, v8.1.0

#79205 Rework docs for the `size` of `terms` agg
  docs/reference/aggregations/bucket/terms-aggregation.asciidoc
  modules/percolator/src/test/java/org/elasticsearch/percolator/QueryBuilderStoreTests.java
  server/src/main/java/org/elasticsearch/index/query/CoordinatorRewriteContext.java
  server/src/main/java/org/elasticsearch/index/query/CoordinatorRewriteContextProvider.java
  server/src/main/java/org/elasticsearch/index/query/QueryRewriteContext.java
  server/src/main/java/org/elasticsearch/index/query/SearchExecutionContext.java
  server/src/main/java/org/elasticsearch/index/query/WrapperQueryBuilder.java
  server/src/main/java/org/elasticsearch/indices/IndicesService.java
  server/src/main/java/org/elasticsearch/search/suggest/completion/CompletionSuggestionBuilder.java
  server/src/main/java/org/elasticsearch/search/suggest/phrase/PhraseSuggester.java
  server/src/test/java/org/elasticsearch/action/search/CanMatchPreFilterSearchPhaseTests.java
  server/src/test/java/org/elasticsearch/index/mapper/DateFieldTypeTests.java
  server/src/test/java/org/elasticsearch/search/aggregations/AggregatorFactoriesTests.java
  server/src/test/java/org/elasticsearch/search/aggregations/bucket/FiltersTests.java
  server/src/test/java/org/elasticsearch/search/builder/SearchSourceBuilderTests.java
  server/src/test/java/org/elasticsearch/search/suggest/completion/CompletionSuggesterBuilderTests.java
  test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/permission/DocumentPermissions.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/termsenum/action/TransportTermsEnumAction.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/permission/DocumentPermissionsTests.java
  x-pack/plugin/frozen-indices/src/test/java/org/elasticsearch/index/engine/frozen/RewriteCachingDirectoryReaderTests.java
Labels: >docs, :Analytics/Aggregations, Team:Docs, Team:Analytics, auto-merge, auto-backport-and-merge, v7.15.2, v8.1.0, v8.0.0-beta1

#80158 [8.0][DOCS] Adds breaking change for allow_no_datafeeds and allow_no_jobs …
  docs/reference/migration/migrate_8_0/api.asciidoc
Labels: backport, v8.0.0

#79969 8.0.0-beta1 release notes
  docs/reference/release-notes.asciidoc
  docs/reference/release-notes/8.0.0-beta1.asciidoc
Labels: >docs, WIP, v8.0.0, Team:Docs

#79651 Optimize `significant_text` aggregation to only parse the field it requires from _source
  server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java
Labels: >enhancement, :Analytics/Aggregations, Team:Analytics, v8.1.0

#80184 [8.0] [ML] [DOCS] Update the model part upload URL in example (#80181)
  docs/reference/ml/df-analytics/apis/put-trained-model-definition-part.asciidoc
Labels: backport, v8.0.0, auto-merge

#80190 [8.x] [DOCS] Add 8.0.0-beta1 release notes
  docs/reference/release-notes.asciidoc
  docs/reference/release-notes/8.0.0-beta1.asciidoc
Labels: backport, v8.1.0

#79618 Skip Expensive InternalSnapshotInfoService Application in some Cases
  server/src/main/java/org/elasticsearch/snapshots/InternalSnapshotsInfoService.java
Labels: >non-issue, :Distributed/Snapshot/Restore, v8.0.0, Team:Distributed, v7.16.1

#80193 Mute old ES reindex tests
  modules/reindex/build.gradle
Labels: :Delivery/Build, >test-failure, Team:Delivery, auto-merge, v8.1.0

#80163 [DOCS] Adds deprecated allow_no_jobs and allow_no_datafeeds in ML APIs
  docs/reference/cat/anomaly-detectors.asciidoc
  docs/reference/cat/datafeeds.asciidoc
  docs/reference/ml/anomaly-detection/apis/close-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-overall-buckets.asciidoc
  docs/reference/ml/anomaly-detection/apis/stop-datafeed.asciidoc
Labels: >docs, :ml, Team:Docs, Team:ML, v7.10.3, v7.11.3, v7.12.2, auto-backport, v7.13.5, v7.16.0, v7.14.3, v7.15.2, v7.16.1

#80179 Cache `DiscoveryNode#trimTier` Result
  server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java
Labels: >non-issue, :Distributed/Allocation, v8.0.0, Team:Distributed, v8.1.0

#80114 Evaluate wrapped proxy request for compression
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/TransportActionProxy.java
Labels: >non-issue, :Distributed/Network, Team:Distributed, v8.1.0

#80095 [DOCS] Add system indices deprecation
  docs/reference/migration/migrate_7_16.asciidoc
Labels: >docs, :Core/Infra/Core, Team:Core/Infra, Team:Docs, v7.16.0, v7.16.1

#79641 [DOCS] Security ON by default beta updates
  x-pack/docs/en/security/configuring-stack-security.asciidoc
Labels: >docs, :Security/TLS, v8.0.0, Team:Docs, Team:Security, auto-backport-and-merge, v8.1.0, v8.0.0-beta1

#80113 [DOCS] Update Docker for security ON by default
  docs/reference/redirects.asciidoc
  docs/reference/setup/install/.env
  docs/reference/setup/install/create-certs.yml
  docs/reference/setup/install/docker-compose.yml
  docs/reference/setup/install/docker.asciidoc
  docs/reference/setup/install/instances.yml
  x-pack/docs/en/security/securing-communications/configuring-tls-docker.asciidoc
  x-pack/docs/en/security/security-manual-configuration.asciidoc
Labels: >docs, :Security/TLS, v8.0.0, Team:Docs, Team:Security, auto-backport-and-merge, v8.1.0, v8.0.0-beta1

#80201 Fix regex in checkstyle on windows
  build-tools-internal/src/main/resources/checkstyle.xml
Labels: >enhancement, :Delivery/Build, Team:Delivery, v7.16.0, v8.1.0

#80159 [ML] adding all config update types for inference processor error
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/ingest/InferenceProcessor.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/ingest/InferenceProcessorFactoryTests.java
Labels: >non-issue, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0

#80154 [8.0] [ML] Add the number of queue requests per node to deployment stats (#80098)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetDeploymentStatsAction.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/action/GetDeploymentStatsActionResponseTests.java
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/PyTorchModelIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportGetDeploymentStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/ModelStats.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/pytorch/process/PyTorchResultProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/ProcessWorkerExecutorService.java
Labels: backport, v8.0.0, auto-merge

#80212 [8.0] [DOCS] Security ON by default beta updates (#79641)
  x-pack/docs/en/security/configuring-stack-security.asciidoc
Labels: backport, v8.0.0, auto-merge

#80211 [8.0] [DOCS] Update Docker for security ON by default (#80113)
  docs/reference/redirects.asciidoc
  docs/reference/setup/install/.env
  docs/reference/setup/install/create-certs.yml
  docs/reference/setup/install/docker-compose.yml
  docs/reference/setup/install/docker.asciidoc
  docs/reference/setup/install/instances.yml
  x-pack/docs/en/security/securing-communications/configuring-tls-docker.asciidoc
  x-pack/docs/en/security/security-manual-configuration.asciidoc
Labels: backport, v8.0.0, auto-merge

#80204 Undeprecate the auto complete thread pool
  server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java
Labels: >bug, :Search/Search, Team:Search, v7.16.0, v7.16.1

#80210 Adding .logstash-management to the list of known templates
  test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java
Labels: :Data Management/Other, Team:Data Management, Team:Clients, v7.16.0, v7.16.1

#80213 Upgrade Lucene 9 snapshot cc2a31f2be8
  build-tools-internal/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.0.0-snapshot-2719cf6630e.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  modules/legacy-geo/licenses/lucene-spatial-extras-9.0.0-snapshot-2719cf6630e.jar.sha1
  modules/legacy-geo/licenses/lucene-spatial-extras-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-analysis-common-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-analysis-common-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-backward-codecs-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-backward-codecs-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-core-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-core-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-grouping-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-grouping-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-highlighter-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-highlighter-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-join-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-join-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-memory-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-memory-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-misc-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-misc-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-queries-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-queries-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-queryparser-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-queryparser-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-sandbox-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-sandbox-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-spatial3d-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-spatial3d-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-suggest-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-suggest-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  x-pack/plugin/sql/sql-action/licenses/lucene-core-9.0.0-snapshot-2719cf6630e.jar.sha1
  x-pack/plugin/sql/sql-action/licenses/lucene-core-9.0.0-snapshot-cc2a31f2be8.jar.sha1
Labels: :Search/Search, >upgrade, v8.0.0, v8.1.0

#80216 [7.15][DOCS] Adds deprecated allow_no_jobs and allow_no_datafeeds ML API... (#80163)
  docs/reference/cat/anomaly-detectors.asciidoc
  docs/reference/cat/datafeeds.asciidoc
  docs/reference/ml/anomaly-detection/apis/close-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-overall-buckets.asciidoc
  docs/reference/ml/anomaly-detection/apis/stop-datafeed.asciidoc
Labels: backport, v7.15.2

#80217 [7.14][DOCS] Adds deprecated allow_no_jobs and allow_no_datafeeds ML API…(#80163)
  docs/reference/cat/anomaly-detectors.asciidoc
  docs/reference/cat/datafeeds.asciidoc
  docs/reference/ml/anomaly-detection/apis/close-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-overall-buckets.asciidoc
  docs/reference/ml/anomaly-detection/apis/stop-datafeed.asciidoc
Labels: backport, v7.14.3

#80219 [7.13][DOCS] Adds deprecated allow_no_jobs and allow_no_datafeeds ML API…(#80163)
  docs/reference/cat/anomaly-detectors.asciidoc
  docs/reference/cat/datafeeds.asciidoc
  docs/reference/ml/anomaly-detection/apis/close-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-overall-buckets.asciidoc
  docs/reference/ml/anomaly-detection/apis/stop-datafeed.asciidoc
Labels: backport, v7.13.5

#80215 [8.0][ML] Report start_time for trained model deployments and allocations …
  docs/reference/ml/df-analytics/apis/get-trained-model-deployment-stats.asciidoc
  docs/reference/ml/df-analytics/apis/start-trained-model-deployment.asciidoc
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetDeploymentStatsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/allocation/TrainedModelAllocation.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/action/GetDeploymentStatsActionResponseTests.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportGetDeploymentStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/ModelStats.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/action/TransportGetDeploymentStatsActionTests.java
Labels: backport, v8.0.0, auto-merge

#80220 [7.12][DOCS] Adds deprecated allow_no_jobs and allow_no_datafeeds ML API...(#80163)
  docs/reference/cat/anomaly-detectors.asciidoc
  docs/reference/cat/datafeeds.asciidoc
  docs/reference/ml/anomaly-detection/apis/close-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-overall-buckets.asciidoc
  docs/reference/ml/anomaly-detection/apis/stop-datafeed.asciidoc
Labels: backport, v7.12.2

#80221 [7.11][DOCS] Adds deprecated allow_no_jobs and allow_no_datafeeds ML API...(#80163)
  docs/reference/cat/anomaly-detectors.asciidoc
  docs/reference/cat/datafeeds.asciidoc
  docs/reference/ml/anomaly-detection/apis/close-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-overall-buckets.asciidoc
  docs/reference/ml/anomaly-detection/apis/stop-datafeed.asciidoc
Labels: backport, v7.11.3

#80222 [7.10][DOCS] Adds deprecated allow_no_jobs and allow_no_datafeeds ML API…(#80163)
  docs/reference/cat/anomaly-detectors.asciidoc
  docs/reference/cat/datafeeds.asciidoc
  docs/reference/ml/anomaly-detection/apis/close-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-datafeed.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job-stats.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-job.asciidoc
  docs/reference/ml/anomaly-detection/apis/get-overall-buckets.asciidoc
  docs/reference/ml/anomaly-detection/apis/stop-datafeed.asciidoc
Labels: backport, v7.10.3

#80223 Rework docs for the `size` of `terms` agg (backport of #79205)
  docs/reference/aggregations/bucket/terms-aggregation.asciidoc
Labels: backport, v8.0.0, v8.0.0-beta1

#80218 Upgrade Lucene 9 snapshot cc2a31f2be8
  build-tools-internal/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.0.0-snapshot-2719cf6630e.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  modules/legacy-geo/licenses/lucene-spatial-extras-9.0.0-snapshot-2719cf6630e.jar.sha1
  modules/legacy-geo/licenses/lucene-spatial-extras-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.0.0-snapshot-2719cf6630e.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-analysis-common-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-analysis-common-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-backward-codecs-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-backward-codecs-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-core-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-core-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-grouping-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-grouping-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-highlighter-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-highlighter-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-join-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-join-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-memory-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-memory-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-misc-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-misc-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-queries-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-queries-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-queryparser-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-queryparser-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-sandbox-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-sandbox-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-spatial3d-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-spatial3d-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-suggest-9.0.0-snapshot-2719cf6630e.jar.sha1
  server/licenses/lucene-suggest-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  x-pack/plugin/sql/sql-action/licenses/lucene-core-9.0.0-snapshot-2719cf6630e.jar.sha1
  x-pack/plugin/sql/sql-action/licenses/lucene-core-9.0.0-snapshot-cc2a31f2be8.jar.sha1
Labels: :Search/Search, >upgrade, backport, v8.0.0

#80226 Rework docs for the `size` of `terms` agg (backport of #79205) (#80223)
  docs/reference/aggregations/bucket/terms-aggregation.asciidoc
Labels: backport, v7.16.1

#80227 Rework docs for the `size` of `terms` agg (backport of #79205) (#80223)
  docs/reference/aggregations/bucket/terms-aggregation.asciidoc
Labels: backport, v7.15.2

#80203 Restore rounding tests
  benchmarks/src/main/java/org/elasticsearch/benchmark/indices/common/RoundingBenchmark.java
  server/src/main/java/org/elasticsearch/common/Rounding.java
  server/src/test/java/org/elasticsearch/common/RoundingTests.java
  server/src/test/java/org/elasticsearch/common/RoundingWireTests.java
Labels: >test, :Core/Infra/Core, Team:Core/Infra, v8.1.0, v8.0.0-beta1

#80229 Restore rounding tests (#80203)
  benchmarks/src/main/java/org/elasticsearch/benchmark/indices/common/RoundingBenchmark.java
  server/src/main/java/org/elasticsearch/common/Rounding.java
  server/src/test/java/org/elasticsearch/common/RoundingTests.java
  server/src/test/java/org/elasticsearch/common/RoundingWireTests.java
Labels: >test, backport, v8.0.0, auto-merge, v8.0.0-beta1

#80230 [DOCS] Add collapsible section to `dimension` parameter
  docs/reference/mapping/types/ip.asciidoc
  docs/reference/mapping/types/keyword.asciidoc
  docs/reference/mapping/types/numeric.asciidoc
Labels: >docs, Team:Docs, v7.15.2

#80140 Add privileges to kibana_system for upgrading endpoint hidden indices
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStore.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java
Labels: >enhancement, :Security/Authorization, v8.0.0, Team:Security, external-contributor, v7.16.0, auto-backport-and-merge, v8.1.0

#80234 [8.0] Allow kibana_system to upgrade endpoint hidden indices (#80140)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStore.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java
Labels: backport, v8.0.0, external-contributor, auto-merge

#80235 [7.16] Allow kibana_system to upgrade endpoint hidden indices (#80140)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStore.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java
Labels: backport, external-contributor, auto-merge, v7.16.1

#80060 Reenable V7RestCompat for invalidateApiKey with single id
  x-pack/plugin/build.gradle
Labels: >test, :Security/Security, v8.0.0, Team:Security, auto-backport-and-merge, v8.1.0

#80231 [Security Solution] Add proper permissions to fleet server for Endpoint response index
  x-pack/docs/en/rest-api/security/get-service-accounts.asciidoc
  x-pack/plugin/security/qa/service-account/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/service/ServiceAccountIT.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccounts.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccountsTests.java
Labels: >enhancement, :Security/Authorization, v8.0.0, Team:Security, external-contributor, v7.16.0, auto-backport-and-merge, v8.1.0

#80237 [8.0] Reenable V7RestCompat for invalidateApiKey with single id (#80060)
  x-pack/plugin/build.gradle
Labels: backport, v8.0.0, auto-merge

#80238 [Security Solution] Add proper permissions to fleet server for Endpoint response index (#80231)
  x-pack/docs/en/rest-api/security/get-service-accounts.asciidoc
  x-pack/plugin/security/qa/service-account/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/service/ServiceAccountIT.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccounts.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccountsTests.java
Labels: >enhancement, :Security/Authorization, v8.0.0, Team:Security, external-contributor, v7.16.0, auto-backport-and-merge, v8.1.0

#80240 [DOCS] Fixes version in ML breaking change
  docs/reference/migration/migrate_8_0/api.asciidoc
Labels: >docs, :ml, Team:Docs, Team:ML, v8.1.0

#79809 Enable run as for all authentication schemes
  x-pack/plugin/build.gradle
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authc/Authentication.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authc/AuthenticationTests.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authc/RunAsIntegTests.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/action/token/TransportCreateTokenAction.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/logfile/LoggingAuditTrail.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/AuthenticatorChain.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/service/ServiceAccountService.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/AuthorizationService.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/audit/logfile/LoggingAuditTrailTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/AuthorizationServiceTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStoreTests.java
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/service_accounts/10_basic.yml
Labels: >enhancement, :Security/Authentication, Team:Security, v8.1.0

#80241 [Security Solution] Add proper permissions to fleet server for Endpoint response index (#80238)
  x-pack/docs/en/rest-api/security/get-service-accounts.asciidoc
  x-pack/plugin/security/qa/service-account/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/service/ServiceAccountIT.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccounts.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccountsTests.java
Labels: backport, v8.0.0, auto-merge

#80242 [Security Solution] Add proper permissions to fleet server for Endpoint response index (#80238)
  x-pack/docs/en/rest-api/security/get-service-accounts.asciidoc
  x-pack/plugin/security/qa/service-account/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/service/ServiceAccountIT.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccounts.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccountsTests.java
Labels: backport, auto-merge, v7.16.0

#80244 Prevent infinite recursion for RBACEngineAuthorizationInfo#hashCode
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/RBACEngineTests.java
Labels: >non-issue, :Security/Security, v8.0.0, Team:Security, v7.16.0, auto-backport-and-merge, v8.1.0

#80245 [8.0] Prevent infinite recursion for RBACEngineAuthorizationInfo#hashCode (#80244)
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/RBACEngineTests.java
Labels: backport, v8.0.0, auto-merge

#80246 [7.16] Prevent infinite recursion for RBACEngineAuthorizationInfo#hashCode (#80244)
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/RBACEngineTests.java
Labels: backport, auto-merge, v7.16.0

#80247 [Test] Fix and enhance testServiceAccountDenial
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/AuthorizationServiceTests.java
Labels: >test, :Security/Security, Team:Security, v8.1.0

#80205 Document _key tag added on the agg layer features
  docs/reference/search/search-vector-tile-api.asciidoc
Labels: >docs, :Analytics/Geo, v8.0.0, Team:Docs, Team:Analytics, v7.16.1, v8.1.0

#80249 [7.16] Document _key tag added on the agg layer features (#80205)
  docs/reference/search/search-vector-tile-api.asciidoc
Labels: backport, auto-merge, v7.16.1

#80248 [8.0] Document _key tag added on the agg layer features (#80205)
  docs/reference/search/search-vector-tile-api.asciidoc
Labels: backport, v8.0.0, auto-merge

#79699 Move GeoShapeIndexer#prepareForIndexing to its own utility class
  modules/legacy-geo/src/test/java/org/elasticsearch/legacygeo/BaseGeoParsingTestCase.java
  modules/legacy-geo/src/test/java/org/elasticsearch/legacygeo/GeoJsonShapeParserTests.java
  modules/legacy-geo/src/test/java/org/elasticsearch/legacygeo/GeoWKTShapeParserTests.java
  modules/legacy-geo/src/test/java/org/elasticsearch/legacygeo/ShapeBuilderTests.java
  server/src/main/java/org/elasticsearch/common/geo/GeoLineDecomposer.java
  server/src/main/java/org/elasticsearch/common/geo/GeoPolygonDecomposer.java
  server/src/main/java/org/elasticsearch/common/geo/GeoShapeUtils.java
  server/src/main/java/org/elasticsearch/common/geo/GeometryNormalizer.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoShapeIndexer.java
  server/src/test/java/org/elasticsearch/common/geo/GeometryIndexerTests.java
  server/src/test/java/org/elasticsearch/common/geo/GeometryNormalizerTests.java
  x-pack/plugin/spatial/src/internalClusterTest/java/org/elasticsearch/xpack/spatial/search/GeoShapeScriptDocValuesIT.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/GeoShapeValues.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldMapper.java
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/fielddata/GeometryDocValueTests.java
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/fielddata/Tile2DVisitorTests.java
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/fielddata/TriangleTreeTests.java
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/mapper/LatLonShapeDocValuesQueryTests.java
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/ingest/CircleProcessorTests.java
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/search/aggregations/bucket/geogrid/GeoGridTilerTestCase.java
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/search/aggregations/bucket/geogrid/GeoTileTilerTests.java
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/search/aggregations/metrics/GeoShapeCentroidAggregatorTests.java
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/util/GeoTestUtils.java
Labels: :Analytics/Geo, >refactoring, Team:Analytics, v8.1.0

#79999 Rename shared cache static constant settings
  x-pack/plugin/autoscaling/src/internalClusterTest/java/org/elasticsearch/xpack/autoscaling/AbstractFrozenAutoscalingIntegTestCase.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/BaseFrozenSearchableSnapshotsIntegTestCase.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/BaseSearchableSnapshotsIntegTestCase.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsCanMatchOnCoordinatorIntegTests.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/SearchableSnapshotsBlobStoreCacheIntegTests.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/NodesCachesStatsIntegTests.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/PartiallyCachedShardAllocationIntegTests.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshots.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/action/cache/FrozenCacheInfoNodeAction.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/decider/HasFrozenCacheAllocationDecider.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheService.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/AbstractSearchableSnapshotsTestCase.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheServiceTests.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/store/input/FrozenIndexInputTests.java
Labels: >non-issue, :Distributed/Snapshot/Restore, v8.0.0, Team:Distributed, v7.16.0, auto-backport-and-merge, v8.1.0

#80252 [8.0] Fix regex in checkstyle on windows (#80201)
  build-tools-internal/src/main/resources/checkstyle.xml
Labels: >bug, :Delivery/Build, backport, v8.0.0, Team:Delivery, auto-merge

#80251 [8.0] Rename shared cache static constant settings (#79999)
  x-pack/plugin/autoscaling/src/internalClusterTest/java/org/elasticsearch/xpack/autoscaling/AbstractFrozenAutoscalingIntegTestCase.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/BaseFrozenSearchableSnapshotsIntegTestCase.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/BaseSearchableSnapshotsIntegTestCase.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsCanMatchOnCoordinatorIntegTests.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/SearchableSnapshotsBlobStoreCacheIntegTests.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/NodesCachesStatsIntegTests.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/PartiallyCachedShardAllocationIntegTests.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshots.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/action/cache/FrozenCacheInfoNodeAction.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/decider/HasFrozenCacheAllocationDecider.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheService.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/AbstractSearchableSnapshotsTestCase.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheServiceTests.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/store/input/FrozenIndexInputTests.java
Labels: backport, v8.0.0, auto-merge

#80255 Rename shared cache static constant settings (#79999)
  x-pack/plugin/autoscaling/src/internalClusterTest/java/org/elasticsearch/xpack/autoscaling/AbstractFrozenAutoscalingIntegTestCase.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/BaseFrozenSearchableSnapshotsIntegTestCase.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/BaseSearchableSnapshotsIntegTestCase.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsCanMatchOnCoordinatorIntegTests.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/SearchableSnapshotsBlobStoreCacheIntegTests.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/NodesCachesStatsIntegTests.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/PartiallyCachedShardAllocationIntegTests.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshots.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/action/cache/FrozenCacheInfoNodeAction.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/decider/HasFrozenCacheAllocationDecider.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheService.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/AbstractSearchableSnapshotsTestCase.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheServiceTests.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/store/input/FrozenIndexInputTests.java
Labels: backport, auto-merge, v7.16.0, v7.16.1

#80077 Fix SearchableSnapshotsPersistentCacheIntegTests
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/full/SearchableSnapshotsPersistentCacheIntegTests.java
Labels: >test, :Distributed/Snapshot/Restore, v8.0.0, Team:Distributed, v7.16.0, auto-backport-and-merge, v7.15.2, v8.1.0

#80261 [8.0] Fix SearchableSnapshotsPersistentCacheIntegTests (#80077)
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/full/SearchableSnapshotsPersistentCacheIntegTests.java
Labels: backport, v8.0.0, auto-merge

#80263 [7.15] Fix SearchableSnapshotsPersistentCacheIntegTests (#80077)
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/full/SearchableSnapshotsPersistentCacheIntegTests.java
Labels: backport, auto-merge, v7.15.2

#80250 [TEST] Reset LDAP processing delay after test
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/SearchGroupsResolverInMemoryTests.java
Labels: >test, :Security/Authentication, v8.0.0, Team:Security, auto-backport-and-merge, v8.1.0

#80262 [7.16] Fix SearchableSnapshotsPersistentCacheIntegTests (#80077)
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/cache/full/SearchableSnapshotsPersistentCacheIntegTests.java
Labels: backport, auto-merge, v7.16.1

#80149 [ML] reduce the logging spam for the ml initializer for annotation index creation
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MlInitializationService.java
Labels: >non-issue, :ml, Team:ML, v8.1.0

#80266 [8.0] [TEST] Reset LDAP processing delay after test (#80250)
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/SearchGroupsResolverInMemoryTests.java
Labels: backport, v8.0.0, auto-merge

#80214 [8.0] [ML] adding all config update types for inference processor error (#80159)
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/ingest/InferenceProcessor.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/ingest/InferenceProcessorFactoryTests.java
Labels: backport, v8.0.0, auto-merge

#80150 [DOCS] EQL: Document optional fields
  docs/reference/eql/syntax.asciidoc
Labels: >docs, :Query Languages/EQL, Team:Docs, Team:QL, v7.16.1, v8.1.0, v8.0.0-beta1

#80271 [7.16] [DOCS] EQL: Document optional fields (#80150)
  docs/reference/eql/syntax.asciidoc
Labels: backport, auto-merge, v7.16.1

#80270 [8.0] [DOCS] EQL: Document optional fields (#80150)
  docs/reference/eql/syntax.asciidoc
Labels: backport, v8.0.0, auto-merge

#80091 [DOCS] Add transient settings migration guide
  docs/reference/cluster/update-settings.asciidoc
  docs/reference/migration/migrate_7_16.asciidoc
  docs/reference/migration/transient-settings-migration-guide.asciidoc
  docs/reference/setup/configuration.asciidoc
Labels: >docs, :Core/Infra/Core, Team:Core/Infra, Team:Docs, v7.16.1, v8.1.0, v8.0.0-beta1

#80272 [master] [DOCS] Add transient settings migration guide (#80091)
  docs/reference/cluster/update-settings.asciidoc
  docs/reference/migration/migrate_8_0.asciidoc
  docs/reference/migration/transient-settings-migration-guide.asciidoc
  docs/reference/setup/configuration.asciidoc
Labels: backport, v8.1.0

#80273 [8.0] [DOCS] Add transient settings migration guide (#80091)
  docs/reference/cluster/update-settings.asciidoc
  docs/reference/migration/migrate_8_0.asciidoc
  docs/reference/migration/transient-settings-migration-guide.asciidoc
  docs/reference/setup/configuration.asciidoc
Labels: backport, v8.0.0

#80274 Fix execution of exists query within nested queries on field with doc…
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search/161_exists_query_within_nested_query.yml
  server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/LuceneDocument.java
  server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java
Labels: backport, v7.15.2, v7.15.3

#80278 [master] [DOCS] Add collapsible section to `dimension` parameter (#80230)
  docs/reference/index-modules.asciidoc
  docs/reference/mapping/types/aggregate-metric-double.asciidoc
  docs/reference/mapping/types/histogram.asciidoc
  docs/reference/mapping/types/ip.asciidoc
  docs/reference/mapping/types/keyword.asciidoc
  docs/reference/mapping/types/numeric.asciidoc
Labels: backport, v8.1.0

#80144 This commit includes more updates to deprecation info API message wor…
  server/src/main/java/org/elasticsearch/script/ScriptService.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/TransformConfig.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/pivot/PivotConfig.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/transform/transforms/TransformConfigTests.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/CcrAutoFollowedSystemIndicesChecker.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/IndexDeprecationChecks.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/MlDeprecationChecker.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/NodeDeprecationChecks.java
  x-pack/plugin/deprecation/src/test/java/org/elasticsearch/xpack/deprecation/IndexDeprecationChecksTests.java
  x-pack/plugin/deprecation/src/test/java/org/elasticsearch/xpack/deprecation/NodeDeprecationChecksTests.java
Labels: :Data Management/Other, Team:Data Management, v7.16.0, v7.16.1

#80280 [7.16] [DOCS] Add collapsible section to TSDB mapping parameters + index setting (#80230) (#80278)
  docs/reference/index-modules.asciidoc
  docs/reference/mapping/types/aggregate-metric-double.asciidoc
  docs/reference/mapping/types/histogram.asciidoc
  docs/reference/mapping/types/ip.asciidoc
  docs/reference/mapping/types/keyword.asciidoc
  docs/reference/mapping/types/numeric.asciidoc
Labels: backport, auto-merge, v7.16.1

#80173 Fix xcontent test deprecated
  libs/x-content/src/test/java/org/elasticsearch/xcontent/support/filtering/AbstractXContentFilteringTestCase.java
Labels: >test, :Core/Infra/Core, external-contributor, auto-merge, v8.1.0

#80166 Possible source of leaked delayable writables
  server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java
  server/src/main/java/org/elasticsearch/search/query/QuerySearchResult.java
  x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchActionIT.java
Labels: >bug, :Analytics/Aggregations, Team:Analytics, v7.16.0, auto-backport-and-merge, v7.15.2, v8.1.0, v8.0.0-beta1

#80069 add benchmark to test xcontent parser filter performance
  benchmarks/src/main/java/org/elasticsearch/benchmark/xcontent/FilterContentBenchmark.java
  benchmarks/src/main/resources/org/elasticsearch/benchmark/xcontent/monitor_cluster_stats.json
  benchmarks/src/main/resources/org/elasticsearch/benchmark/xcontent/monitor_index_stats.json
  benchmarks/src/main/resources/org/elasticsearch/benchmark/xcontent/monitor_node_stats.json
Labels: Team:Analytics, external-contributor, auto-merge, :Analytics/TSDB, v8.1.0

#80115 [DOCS] Fix HOSTNAME quotes
  docs/reference/setup/configuration.asciidoc
Labels: >docs, v8.0.0, Team:Docs, external-contributor, v7.16.0, v7.15.1, auto-backport-and-merge, v8.1.0

#80292 [8.0] Possible source of leaked delayable writables (#80166)
  server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java
  server/src/main/java/org/elasticsearch/search/query/QuerySearchResult.java
  x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchActionIT.java
Labels: backport, v8.0.0, auto-merge

#80291 [7.16] Possible source of leaked delayable writables (#80166)
  server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java
  server/src/main/java/org/elasticsearch/search/query/QuerySearchResult.java
  x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchActionIT.java
Labels: backport, auto-merge, v7.16.1

#80054 Ensure system index doc types are migrated to `_doc`
  modules/reindex/src/internalClusterTest/java/org/elasticsearch/migration/FeatureMigrationIT.java
  server/src/main/java/org/elasticsearch/upgrades/SystemIndexMigrationInfo.java
Labels: >non-issue, :Core/Infra/Core, Team:Core/Infra, v7.16.1

#80049 Fix race condition when storing Feature migration callback metadata
  server/src/main/java/org/elasticsearch/upgrades/SystemIndexMigrator.java
Labels: >non-issue, :Core/Infra/Core, v8.0.0, Team:Core/Infra, auto-backport, v7.16.1, v8.1.0

#80199 Add support for superseding in CancellableSingleObjectCache
  server/src/main/java/org/elasticsearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/elasticsearch/common/util/CancellableSingleObjectCache.java
  server/src/test/java/org/elasticsearch/common/util/CancellableSingleObjectCacheTests.java
Labels: >enhancement, :Distributed/Distributed, Team:Distributed, auto-backport-and-merge, v7.16.1, v8.1.0

#80297 [7.15] [DOCS] Fix HOSTNAME quotes (#80115)
  docs/reference/setup/configuration.asciidoc
Labels: backport, auto-merge, v7.15.3

#80296 [7.16] [DOCS] Fix HOSTNAME quotes (#80115)
  docs/reference/setup/configuration.asciidoc
Labels: backport, auto-merge, v7.16.1

#80295 [8.0] [DOCS] Fix HOSTNAME quotes (#80115)
  docs/reference/setup/configuration.asciidoc
Labels: backport, v8.0.0, auto-merge

#80293 [7.15] Possible source of leaked delayable writables (#80166)
  server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java
  server/src/main/java/org/elasticsearch/search/query/QuerySearchResult.java
  x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchActionIT.java
Labels: backport, auto-merge

#80233 Additional deprecation checks
  server/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/DeprecationChecks.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/IndexDeprecationChecks.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/NodeDeprecationChecks.java
  x-pack/plugin/deprecation/src/test/java/org/elasticsearch/xpack/deprecation/IndexDeprecationChecksTests.java
  x-pack/plugin/deprecation/src/test/java/org/elasticsearch/xpack/deprecation/NodeDeprecationChecksTests.java
Labels: :Data Management/Other, Team:Data Management, v7.16.0, v7.16.1

#80294 [7.16] [DOCS] Registered domain processor (#71753)
  docs/reference/ingest/processors.asciidoc
  docs/reference/ingest/processors/registered-domain.asciidoc
Labels: >docs, :Data Management/Ingest, backport, Team:Data Management, Team:Docs, v7.16.1

#80290 Adding two missing entries to the deprecation info api
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecycleSettings.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/DeprecationChecks.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/NodeDeprecationChecks.java
  x-pack/plugin/deprecation/src/test/java/org/elasticsearch/xpack/deprecation/NodeDeprecationChecksTests.java
Labels: backport pending, :Data Management/Other, v8.0.0, Team:Data Management, auto-backport-and-merge, v8.1.0

#80279 [8.0] [DOCS] Add collapsible section to TSDB mapping parameters + index setting (#80230) (#80278)
  docs/reference/index-modules.asciidoc
  docs/reference/mapping/types/aggregate-metric-double.asciidoc
  docs/reference/mapping/types/histogram.asciidoc
  docs/reference/mapping/types/ip.asciidoc
  docs/reference/mapping/types/keyword.asciidoc
  docs/reference/mapping/types/numeric.asciidoc
Labels: backport, v8.0.0, auto-merge

#80298 [7.14] [DOCS] Registered domain processor (#71753)
  docs/reference/ingest/processors.asciidoc
  docs/reference/ingest/processors/registered-domain.asciidoc
Labels: >docs, :Data Management/Ingest, backport, Team:Data Management, Team:Docs, v7.14.3

#80300 [7.15] [DOCS] Registered domain processor (#71753)
  docs/reference/ingest/processors.asciidoc
  docs/reference/ingest/processors/registered-domain.asciidoc
Labels: >docs, :Data Management/Ingest, backport, Team:Data Management, Team:Docs, v7.15.3

#80302 [7.16] Add support for superseding in CancellableSingleObjectCache (#80199)
  server/src/main/java/org/elasticsearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/elasticsearch/common/util/CancellableSingleObjectCache.java
  server/src/test/java/org/elasticsearch/common/util/CancellableSingleObjectCacheTests.java
Labels: backport, auto-merge, v7.16.1

#80307 [8.0] Adding two missing entries to the deprecation info api (#80290)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecycleSettings.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/DeprecationChecks.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/NodeDeprecationChecks.java
  x-pack/plugin/deprecation/src/test/java/org/elasticsearch/xpack/deprecation/NodeDeprecationChecksTests.java
Labels: backport, v8.0.0, auto-merge

#80299 [8.0] Fix race condition when storing Feature migration callback metadata (#80049)
  server/src/main/java/org/elasticsearch/upgrades/SystemIndexMigrator.java
Labels: backport, v8.0.0

#80301 [7.16] Fix race condition when storing Feature migration callback metadata (#80049)
  server/src/main/java/org/elasticsearch/upgrades/SystemIndexMigrator.java
Labels: backport, v7.16.1

#80313 Correct description in kNN search rest spec
  rest-api-spec/src/main/resources/rest-api-spec/api/knn_search.json
Labels: :Search/Search, v8.0.0, Team:Search, Team:Clients, v8.1.0

#80034 Bump bundled JDK to 17.0.1
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/test/DistroTestPlugin.java
  build-tools-internal/version.properties
  docs/changelog/80034.yaml
Labels: :Delivery/Packaging, >upgrade, v8.0.0, Team:Delivery, auto-backport-and-merge, v7.15.2, v7.16.1, v8.1.0

#80317 [8.0] Bump bundled JDK to 17.0.1 (#80034)
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/test/DistroTestPlugin.java
  build-tools-internal/version.properties
  docs/changelog/80034.yaml
Labels: backport, v8.0.0, auto-merge

#80318 [7.16] Bump bundled JDK to 17.0.1 (#80034)
  build-tools-internal/version.properties
  docs/changelog/80034.yaml
Labels: backport, auto-merge, v7.16.1

#80319 [7.15] Bump bundled JDK to 17.0.1 (#80034)
  build-tools-internal/version.properties
  docs/changelog/80034.yaml
Labels: backport, auto-merge, v7.15.3

#80058 Fix typo in instructions for ignore-revs
  .git-blame-ignore-revs
Labels: >non-issue, Team:Delivery, :Delivery/Tooling, v8.1.0

#80051 Don't include associated indices when checking Feature migration status
  modules/reindex/src/internalClusterTest/java/org/elasticsearch/migration/FeatureMigrationIT.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/migration/TransportGetFeatureUpgradeStatusAction.java
Labels: >non-issue, :Core/Infra/Core, v8.0.0, Team:Core/Infra, auto-merge, auto-backport-and-merge, v7.16.1, v8.1.0

#80324 [8.0] Don't include associated indices when checking Feature migration status (#80051)
  modules/reindex/src/internalClusterTest/java/org/elasticsearch/migration/FeatureMigrationIT.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/migration/TransportGetFeatureUpgradeStatusAction.java
Labels: backport, v8.0.0, auto-merge

#80043 Script: support boolean fields in Fields API
  modules/lang-painless/src/main/resources/org/elasticsearch/painless/org.elasticsearch.script.fields.txt
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/50_script_doc_values.yml
  server/src/main/java/org/elasticsearch/index/fielddata/ScriptDocValues.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/LeafLongFieldData.java
  server/src/main/java/org/elasticsearch/script/field/BooleanDocValuesField.java
  server/src/test/java/org/elasticsearch/index/mapper/BooleanScriptFieldTypeTests.java
  test/framework/src/main/java/org/elasticsearch/index/mapper/MapperTestCase.java
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra, v8.1.0

#80086 Fix IndexTemplateRegistry Deserializing Templates etc. During CS Updates
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/LifecyclePolicyConfig.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/logging/DeprecationIndexingTemplateRegistry.java
  x-pack/plugin/fleet/src/main/java/org/elasticsearch/xpack/fleet/FleetTemplateRegistry.java
  x-pack/plugin/ilm/qa/multi-node/build.gradle
  x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java
  x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/slm/SLMSnapshotBlockingIntegTests.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycle.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/history/ILMHistoryTemplateRegistry.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/SnapshotLifecycleTask.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/SnapshotRetentionTask.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/action/TransportExecuteSnapshotLifecycleAction.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/history/SnapshotHistoryItem.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/history/SnapshotHistoryStore.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/history/SnapshotLifecycleTemplateRegistry.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/history/package-info.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/package-info.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/history/ILMHistoryStoreTests.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotLifecycleTaskTests.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotRetentionServiceTests.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotRetentionTaskTests.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/history/SnapshotHistoryItemTests.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/history/SnapshotHistoryStoreTests.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/history/SnapshotLifecycleTemplateRegistryTests.java
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/MlNativeIntegTestCase.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MlIndexTemplateRegistry.java
  x-pack/plugin/stack/src/main/java/org/elasticsearch/xpack/stack/StackTemplateRegistry.java
  x-pack/plugin/stack/src/test/java/org/elasticsearch/xpack/stack/StackTemplateRegistryTests.java
  x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/support/WatcherIndexTemplateRegistry.java
  x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/support/WatcherIndexTemplateRegistryTests.java
Labels: >refactoring, :Data Management/ILM+SLM, v8.0.0, Team:Data Management, v8.1.0

#80288 Fix Searchable Snapshot Bwc Tests Data Tier Setting for 7.12
  x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/SearchableSnapshotsRollingUpgradeIT.java
Labels: >test, :Distributed/Snapshot/Restore, Team:Distributed, v7.16.0, v7.16.1

#80194 fix delete-auto-follow-pattern task name
  x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportDeleteAutoFollowPatternAction.java
Labels: >non-issue, :Distributed/CCR, Team:Distributed, v8.1.0

#80145 [docs] Update required JAVA_HOME variables for running tests
  CONTRIBUTING.md
Labels: >docs, :Delivery/Build, Team:Docs, Team:Delivery, v8.1.0

#80275 add description to shard changes action request
  x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardChangesAction.java
  x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardChangesActionTests.java
Labels: >enhancement, :Distributed/CCR, v8.0.0, Team:Distributed, v7.16.0, auto-backport-and-merge, v8.1.0

#80333 [8.0] add description to shard changes action request (#80275)
  x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardChangesAction.java
  x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardChangesActionTests.java
Labels: backport, v8.0.0, auto-merge

#80310 [ML] throw when definition is requested for pytorch models
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/PyTorchModelIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/persistence/TrainedModelProvider.java
Labels: >non-issue, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0

#80334 [7.16] add description to shard changes action request (#80275)
  x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardChangesAction.java
  x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardChangesActionTests.java
Labels: backport, auto-merge, v7.16.1
