Repository elastic/elasticsearch, pull requests merged in 2021-12, with the labels that each got.

#81145 Spherical mercator transformation should handle properly out of bounds latitudes
  server/src/main/java/org/elasticsearch/common/geo/SphericalMercatorUtils.java
  server/src/test/java/org/elasticsearch/common/geo/SphericalMercatorUtilTests.java
Labels: >bug, :Analytics/Geo, v8.0.0, Team:Analytics, v7.16.1, v8.1.0

#81198 [8.0] Spherical mercator transformation should handle properly out of bounds latitudes (#81145)
  server/src/main/java/org/elasticsearch/common/geo/SphericalMercatorUtils.java
  server/src/test/java/org/elasticsearch/common/geo/SphericalMercatorUtilTests.java
Labels: backport, v8.0.0, auto-merge

#81199 [7.16] Spherical mercator transformation should handle properly out of bounds latitudes (#81145)
  server/src/main/java/org/elasticsearch/common/geo/SphericalMercatorUtils.java
  server/src/test/java/org/elasticsearch/common/geo/SphericalMercatorUtilTests.java
Labels: backport, auto-merge, v7.16.1

#80156 Make some Netty Handlers Singletons
  modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java
  modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequestCreator.java
  modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpResponseCreator.java
  modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
  modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/ESLoggingHandler.java
  modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
Labels: >non-issue, :Distributed/Network, Team:Distributed, v8.1.0

#81185 [8.0] URL option for BaseRunAsSuperuserCommand (#81025)
  docs/reference/commands/create-enrollment-token.asciidoc
  docs/reference/commands/reset-password.asciidoc
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/esnative/tool/ResetPasswordTool.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/enrollment/ExternalEnrollmentTokenGenerator.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/enrollment/tool/CreateEnrollmentTokenTool.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/tool/BaseRunAsSuperuserCommand.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/enrollment/ExternalEnrollmentTokenGeneratorTests.java
  x-pack/qa/security-tools-tests/src/test/java/org/elasticsearch/xpack/security/authc/esnative/tool/ResetPasswordToolTests.java
  x-pack/qa/security-tools-tests/src/test/java/org/elasticsearch/xpack/security/enrollment/tool/CreateEnrollmentTokenToolTests.java
Labels: backport, v8.0.0

#81186 [8.0] Retry token creation on null httpInfo/transportInfo (#81075)
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/InitialNodeSecurityAutoConfiguration.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/enrollment/InternalEnrollmentTokenGenerator.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/enrollment/InternalEnrollmentTokenGeneratorTests.java
Labels: backport, v8.0.0

#81187 [8.0] Bind on localhost only when no site addresses (#81083)
  x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java
Labels: backport, v8.0.0

#81161 [ML] Fix PyTorchModelIT::testDeploymentStats
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/PyTorchModelIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportGetDeploymentStatsAction.java
Labels: >test, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0

#81003 [ML][DOCS] Add zero shot example and setting truncation at inference
  docs/reference/ml/df-analytics/apis/infer-trained-model-deployment.asciidoc
Labels: >docs, :ml, v8.0.0, Team:Docs, Team:ML, v8.1.0

#80951 Migrate CardinalityIT test to AggregatorTestCase
  server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/metrics/CardinalityIT.java
  server/src/test/java/org/elasticsearch/search/aggregations/metrics/CardinalityAggregatorTests.java
  test/framework/src/main/java/org/elasticsearch/search/aggregations/AggregatorTestCase.java
Labels: >test, :Analytics/Aggregations, >refactoring, Team:Analytics, v8.1.0

#81202 [ML] Fix PyTorchModelIT::testDeploymentStats (#81161)
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/PyTorchModelIT.java
Labels: :ml, backport, v8.0.0, Team:ML, auto-merge

#81189 [8.0] Take node.name into consideration in autoconfiguration (#81007)
  qa/os/src/test/java/org/elasticsearch/packaging/test/ArchiveTests.java
  qa/os/src/test/java/org/elasticsearch/packaging/test/ConfigurationTests.java
  qa/os/src/test/java/org/elasticsearch/packaging/util/ServerUtils.java
  x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java
Labels: backport, v8.0.0

#81206 [8.0] [ML] Improve logging when opening a model is cancelled (#81203)
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/pytorch/process/PyTorchStateStreamer.java
Labels: backport, v8.0.0, auto-merge

#81131 [DOCS] Remove source query params from update/delete by query APIs
  docs/reference/docs/delete-by-query.asciidoc
  docs/reference/docs/update-by-query.asciidoc
  rest-api-spec/src/main/resources/rest-api-spec/api/delete_by_query.json
  rest-api-spec/src/main/resources/rest-api-spec/api/update_by_query.json
Labels: >docs, :Distributed/CRUD, v8.0.0, Team:Distributed, Team:Docs, Team:Clients, v7.16.1, v8.1.0, v7.15.3

#81201 Unmute 'Create data stream' yaml rest test and
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/data_stream/10_basic.yml
Labels: >test, v8.0.0, :Data Management/Data streams, Team:Data Management, auto-backport, v7.16.1, v8.1.0

#81216 [DOCS] Relocate 8.0 `repositories.fs.compress` breaking change
  docs/reference/migration/migrate_8_0/cluster-node-setting-changes.asciidoc
  docs/reference/migration/migrate_8_0/rest-api-changes.asciidoc
Labels: >docs, Team:Docs, v8.1.0, v8.0.0-beta1

#81211 [8.0] [ML] fix autoscaling capacity consistency (#81181)
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/autoscaling/MlAutoscalingDeciderService.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/NodeLoad.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/NativeMemoryCalculator.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/autoscaling/MlAutoscalingDeciderServiceTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/utils/NativeMemoryCalculatorTests.java
Labels: backport, v8.0.0, auto-merge

#81209 [8.0] [DOCS] Remove source query params from update/delete by query APIs (#81131)
  docs/reference/docs/delete-by-query.asciidoc
  docs/reference/docs/update-by-query.asciidoc
  rest-api-spec/src/main/resources/rest-api-spec/api/delete_by_query.json
  rest-api-spec/src/main/resources/rest-api-spec/api/update_by_query.json
Labels: backport, v8.0.0, auto-merge

#81220 [8.0] [DOCS] Relocate 8.0 `repositories.fs.compress` breaking change (#81216)
  docs/reference/migration/migrate_8_0/cluster-node-setting-changes.asciidoc
  docs/reference/migration/migrate_8_0/rest-api-changes.asciidoc
Labels: backport, v8.0.0, auto-merge

#81212 [7.16] [DOCS] Remove source query params from update/delete by query APIs (#81131)
  docs/reference/docs/delete-by-query.asciidoc
  docs/reference/docs/update-by-query.asciidoc
  rest-api-spec/src/main/resources/rest-api-spec/api/delete_by_query.json
  rest-api-spec/src/main/resources/rest-api-spec/api/update_by_query.json
Labels: backport, auto-merge

#81218 [8.0] Unmute 'Create data stream' yaml rest test and (#81201)
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/data_stream/10_basic.yml
Labels: backport, v8.0.0

#81219 [7.16] Unmute 'Create data stream' yaml rest test and (#81201)
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/data_stream/10_basic.yml
Labels: backport, v7.16.1

#81193 [8.0] Remove obsolete BWC check in PutPipelineRequest (#80196)
  server/src/main/java/org/elasticsearch/action/ingest/PutPipelineRequest.java
Labels: >non-issue, :Data Management/Ingest, backport, v8.0.0, Team:Data Management

#81156 Remove the deprecated 'indices.exists_type' API
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.exists_type.json
Labels: :Core/Infra/REST API, v8.0.0, Team:Core/Infra, Team:Clients, external-contributor, auto-backport-and-merge, v8.1.0

#81179 Remove document types from path parameters
  rest-api-spec/src/main/resources/rest-api-spec/api/bulk.json
  rest-api-spec/src/main/resources/rest-api-spec/api/create.json
  rest-api-spec/src/main/resources/rest-api-spec/api/delete.json
  rest-api-spec/src/main/resources/rest-api-spec/api/exists_source.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.stats.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.validate_query.json
  rest-api-spec/src/main/resources/rest-api-spec/api/rollup.rollup_search.json
  rest-api-spec/src/main/resources/rest-api-spec/api/update.json
Labels: :Core/Infra/REST API, v8.0.0, Team:Core/Infra, Team:Clients, auto-backport-and-merge, v8.1.0

#81221 [7.16] [ML] fix autoscaling capacity consistency (#81181)
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/autoscaling/MlAutoscalingDeciderService.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/NodeLoad.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/utils/NativeMemoryCalculator.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/autoscaling/MlAutoscalingDeciderServiceTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/utils/NativeMemoryCalculatorTests.java
Labels: backport, auto-merge, v7.16.1

#81225 [8.0] Remove document types from path parameters
  rest-api-spec/src/main/resources/rest-api-spec/api/bulk.json
  rest-api-spec/src/main/resources/rest-api-spec/api/create.json
  rest-api-spec/src/main/resources/rest-api-spec/api/delete.json
  rest-api-spec/src/main/resources/rest-api-spec/api/exists_source.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.stats.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.validate_query.json
  rest-api-spec/src/main/resources/rest-api-spec/api/rollup.rollup_search.json
  rest-api-spec/src/main/resources/rest-api-spec/api/update.json
Labels: backport, v8.0.0, auto-merge

#81224 [8.0] Remove the deprecated 'indices.exists_type' API
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.exists_type.json
Labels: backport, v8.0.0, auto-merge

#81222 Check downloaded beats archives
  distribution/docker/src/docker/Dockerfile
Labels: >enhancement, v8.0.0, Team:Delivery, :Delivery/Cloud, auto-backport-and-merge, v8.1.0

#81229 [8.0] Check downloaded beats archives (#81222)
  distribution/docker/src/docker/Dockerfile
Labels: backport, v8.0.0, auto-merge

#80518 Add '$' syntax as a shortcut for 'field' in Painless
  modules/lang-painless/src/main/antlr/PainlessLexer.g4
  modules/lang-painless/src/main/antlr/PainlessLexer.tokens
  modules/lang-painless/src/main/antlr/PainlessParser.g4
  modules/lang-painless/src/main/antlr/PainlessParser.tokens
  modules/lang-painless/src/main/java/org/elasticsearch/painless/antlr/PainlessLexer.java
  modules/lang-painless/src/main/java/org/elasticsearch/painless/antlr/PainlessParser.java
  modules/lang-painless/src/main/java/org/elasticsearch/painless/antlr/Walker.java
  modules/lang-painless/src/main/java/org/elasticsearch/painless/phase/PainlessSemanticAnalysisPhase.java
  modules/lang-painless/src/main/java/org/elasticsearch/painless/phase/PainlessUserTreeToIRTreePhase.java
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/50_script_doc_values.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/60_script_doc_values_binary.yml
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra, v8.1.0

#81146 TSDB: Make time boundaries settings required in tsdb indices
  qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
  qa/multi-cluster-search/src/test/resources/rest-api-spec/test/multi_cluster/100_tsdb.yml
  qa/multi-cluster-search/src/test/resources/rest-api-spec/test/remote_cluster/10_basic.yml
  qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/IndexingIT.java
  qa/smoke-test-multinode/src/test/resources/rest-api-spec/test/smoke_test_multinode/20_tsdb_consistency.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/10_settings.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/15_timestamp_mapping.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/20_mapping.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/30_snapshot.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/40_search.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/50_alias.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/60_add_dimensions.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/70_dimension_types.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/80_index_resize.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/tsdb/90_unsupported_operations.yml
  server/src/main/java/org/elasticsearch/index/IndexMode.java
  server/src/test/java/org/elasticsearch/index/IndexSortSettingsTests.java
  server/src/test/java/org/elasticsearch/index/TimeSeriesModeTests.java
  server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java
  server/src/test/java/org/elasticsearch/index/mapper/KeywordFieldMapperTests.java
  server/src/test/java/org/elasticsearch/index/mapper/TimeSeriesIdFieldMapperTests.java
  test/framework/src/main/java/org/elasticsearch/index/mapper/MapperTestCase.java
  x-pack/plugin/ccr/qa/multi-cluster/src/test/java/org/elasticsearch/xpack/ccr/FollowIndexIT.java
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/analytics/histogram.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/data_stream/150_tsdb.yml
Labels: Team:Analytics, external-contributor, :Analytics/TSDB, test-release, v8.1.0

#80067 Split system indices out of Security plugin class
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecurityIndexManager.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/support/SecuritySystemIndices.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/SecurityTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/store/NativeRolesStoreTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/support/SecurityIndexManagerTests.java
Labels: >refactoring, :Security/Security, Team:Security, v8.1.0

#81197 [TEST] Wait for async LDAP search to finish
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/SearchGroupsResolverInMemoryTests.java
Labels: >test, :Security/Authentication, v8.0.0, Team:Security, auto-merge, auto-backport-and-merge, v8.1.0

#81236 [8.0] [TEST] Wait for async LDAP search to finish (#81197)
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/SearchGroupsResolverInMemoryTests.java
Labels: backport, v8.0.0, auto-merge

#81207 Normalize geometry before computing the Vector tile feature
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldTypeTests.java
Labels: >test, :Analytics/Geo, Team:Analytics, v8.1.0

#81204 Guard GeoShapeCentroidAggregatorTests#testSingleValue from invalid polygons
  x-pack/plugin/spatial/src/test/java/org/elasticsearch/xpack/spatial/search/aggregations/metrics/GeoShapeCentroidAggregatorTests.java
Labels: >test, :Analytics/Geo, Team:Analytics, v8.1.0

#81155 Fix bug filtering collinear points on vertical lines
  server/src/main/java/org/elasticsearch/common/geo/GeoPolygonDecomposer.java
  server/src/test/java/org/elasticsearch/common/geo/GeometryIndexerTests.java
Labels: >bug, :Analytics/Geo, v8.0.0, Team:Analytics, v7.16.1, v8.1.0

#81241 [7.16] Fix bug filtering collinear points in polygon decomposition (#81155)
  server/src/main/java/org/elasticsearch/common/geo/GeoPolygonDecomposer.java
  server/src/test/java/org/elasticsearch/common/geo/GeometryIndexerTests.java
Labels: backport, auto-merge, v7.16.1

#81240 [8.0] Fix bug filtering collinear points in polygon decomposition (#81155)
  server/src/main/java/org/elasticsearch/common/geo/GeoPolygonDecomposer.java
  server/src/test/java/org/elasticsearch/common/geo/GeometryIndexerTests.java
Labels: backport, v8.0.0, auto-merge

#81144 Fix shadowed vars pt7 (#80996)
  build-conventions/src/main/java/org/elasticsearch/gradle/internal/checkstyle/HiddenFieldCheck.java
  build-tools-internal/src/main/resources/checkstyle.xml
  x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTaskTests.java
  x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/index/engine/FollowingEngineTests.java
  x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/monitoring/collector/ccr/AutoFollowStatsMonitoringDocTests.java
  x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/monitoring/collector/ccr/FollowStatsMonitoringDocTests.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/rollup/action/GetRollupIndexCapsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/scheduler/Cron.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/search/action/AsyncSearchResponse.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/InvalidateApiKeyRequest.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequest.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/IndicesAccessControl.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/permission/FieldPermissions.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/permission/IndicesPermission.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/permission/ResourcePrivileges.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/slm/SnapshotLifecyclePolicy.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/slm/SnapshotLifecyclePolicyMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/slm/SnapshotLifecycleStats.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ssl/SSLService.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/termsenum/action/MultiShardTermsEnum.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/TransformMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/action/StopTransformAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/SettingsConfig.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/TransformConfig.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/TransformProgress.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/pivot/DateHistogramGroupSource.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/transforms/pivot/HistogramGroupSource.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/actions/throttler/PeriodThrottler.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/client/WatchSourceBuilder.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/common/stats/Counters.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/execution/WatchExecutionContext.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/transform/chain/ChainTransform.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/transport/actions/execute/ExecuteWatchRequest.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/watcher/watch/Watch.java
Labels: >refactoring, backport, Team:Delivery, :Delivery/Tooling, auto-merge, v7.16.1

#81250 Checkstyle shadows vars pt8 (#81147)
  build-conventions/src/main/java/org/elasticsearch/gradle/internal/checkstyle/HiddenFieldCheck.java
  server/src/internalClusterTest/java/org/elasticsearch/action/IndicesRequestIT.java
  x-pack/plugin/analytics/src/test/java/org/elasticsearch/xpack/analytics/topmetrics/InternalTopMetricsTests.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/License.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseService.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/Licensing.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/StartBasicClusterTask.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/XPackLicenseState.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/protocol/xpack/frozen/FreezeRequest.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/protocol/xpack/watcher/PutWatchRequest.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/DataTiersFeatureSetUsage.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackPlugin.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/DeleteDataStreamAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/async/StoredAsyncResponse.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/async/StoredAsyncTask.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ccr/action/FollowStatsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexing/AsyncTwoPhaseIndexer.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/MlMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/CloseJobAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetJobsStatsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetModelSnapshotsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetRecordsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetTrainedModelsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/PostDataAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/PutDataFrameAnalyticsAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/StartDatafeedAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/calendars/Calendar.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedTimingStats.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedUpdate.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/evaluation/classification/AucRoc.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/evaluation/classification/Precision.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/evaluation/classification/Recall.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/evaluation/outlierdetection/AucRoc.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/stats/classification/ClassificationStats.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/stats/common/MemoryUsage.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/stats/outlierdetection/OutlierDetectionStats.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/stats/regression/RegressionStats.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/TrainedModelConfig.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/config/Detector.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/config/Job.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/config/JobUpdate.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/process/autodetect/state/DataCounts.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/results/AnomalyRecord.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/results/Bucket.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/results/ForecastRequestStats.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/LocalStateCompositeXPackPlugin.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/XPackPluginTests.java
  x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/AbstractEnrichProcessor.java
  x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPlugin.java
  x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichPolicyRunner.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/assembler/Criterion.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/StringContainsFunctionPipe.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plan/logical/Join.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plan/physical/EsQueryExec.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plan/physical/SequenceExec.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/querydsl/container/QueryContainer.java
  x-pack/plugin/identity-provider/src/internalClusterTest/java/org/elasticsearch/xpack/idp/saml/sp/SamlServiceProviderIndexTests.java
Labels: >refactoring, backport, Team:Delivery, :Delivery/Tooling, auto-merge, v7.16.1

#81116 Assert no serialization errors in tests
  server/src/internalClusterTest/java/org/elasticsearch/cluster/coordination/ZenDiscoveryIT.java
  server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/elasticsearch/transport/InboundHandler.java
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
  server/src/main/java/org/elasticsearch/transport/TransportHandshaker.java
  server/src/test/java/org/elasticsearch/cluster/coordination/JoinHelperTests.java
  server/src/test/java/org/elasticsearch/transport/InboundHandlerTests.java
  server/src/test/java/org/elasticsearch/transport/TransportHandshakerTests.java
  server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java
  test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java
Labels: >test, :Distributed/Network, Team:Distributed, v8.1.0

#80589 Fail fast remote cluster requests
  server/src/main/java/org/elasticsearch/client/node/NodeClient.java
  server/src/main/java/org/elasticsearch/transport/RemoteClusterAwareClient.java
  server/src/main/java/org/elasticsearch/transport/RemoteClusterService.java
  server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java
  server/src/test/java/org/elasticsearch/transport/RemoteClusterAwareClientTests.java
  server/src/test/java/org/elasticsearch/transport/RemoteClusterClientTests.java
Labels: >bug, :Distributed/Network, v8.0.0, Team:Distributed, auto-backport-and-merge, v7.16.1, v8.1.0

#80970 Script: Ordinal field data plumbing
  modules/parent-join/src/main/java/org/elasticsearch/join/mapper/ParentIdFieldMapper.java
  modules/parent-join/src/main/java/org/elasticsearch/join/mapper/ParentJoinFieldMapper.java
  plugins/analysis-icu/src/main/java/org/elasticsearch/plugin/analysis/icu/ICUCollationKeywordFieldMapper.java
  server/src/main/java/org/elasticsearch/index/fielddata/ordinals/GlobalOrdinalsBuilder.java
  server/src/main/java/org/elasticsearch/index/fielddata/ordinals/GlobalOrdinalsIndexFieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/AbstractIndexOrdinalsFieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/AbstractLeafOrdinalsFieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/ConstantIndexFieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/PagedBytesIndexFieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/PagedBytesLeafFieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/SortedSetBytesLeafFieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/SortedSetOrdinalsIndexFieldData.java
  server/src/main/java/org/elasticsearch/index/mapper/IdFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/IndexFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/IpFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/TimeSeriesIdFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/flattened/FlattenedFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/flattened/KeyedFlattenedLeafFieldData.java
  server/src/test/java/org/elasticsearch/index/fielddata/FieldDataCacheTests.java
  server/src/test/java/org/elasticsearch/index/mapper/flattened/KeyedFlattenedLeafFieldDataTests.java
  server/src/test/java/org/elasticsearch/index/mapper/flattened/RootFlattenedFieldTypeTests.java
  x-pack/plugin/mapper-constant-keyword/src/main/java/org/elasticsearch/xpack/constantkeyword/mapper/ConstantKeywordFieldMapper.java
  x-pack/plugin/mapper-version/src/main/java/org/elasticsearch/xpack/versionfield/VersionStringFieldMapper.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/accesscontrol/FieldDataCacheWithFieldSubsetReaderTests.java
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra, v8.1.0

#81257 [8.0] Fail fast remote cluster requests (#80589)
  server/src/main/java/org/elasticsearch/client/node/NodeClient.java
  server/src/main/java/org/elasticsearch/transport/RemoteClusterAwareClient.java
  server/src/main/java/org/elasticsearch/transport/RemoteClusterService.java
  server/src/test/java/org/elasticsearch/action/search/TransportSearchActionTests.java
  server/src/test/java/org/elasticsearch/transport/RemoteClusterAwareClientTests.java
  server/src/test/java/org/elasticsearch/transport/RemoteClusterClientTests.java
Labels: backport, v8.0.0, auto-merge

#81230 Fail tests on unknown actions
  modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4MessageChannelHandler.java
  plugins/transport-nio/src/main/java/org/elasticsearch/transport/nio/TcpReadWriteHandler.java
  server/src/main/java/org/elasticsearch/transport/InboundAggregator.java
  server/src/main/java/org/elasticsearch/transport/InboundPipeline.java
  server/src/main/java/org/elasticsearch/transport/TransportService.java
  server/src/test/java/org/elasticsearch/transport/RemoteClusterClientTests.java
  test/framework/src/main/java/org/elasticsearch/transport/AbstractSimpleTransportTestCase.java
  test/framework/src/main/java/org/elasticsearch/transport/nio/MockNioTransport.java
Labels: >test, :Distributed/Network, Team:Distributed, v8.1.0

#81261 [8.0] [ML] Improve trained model allocation task info (#81259)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/MlTasks.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/StartTrainedModelDeploymentAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/allocation/TrainedModelAllocationNodeService.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/TrainedModelDeploymentTask.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/deployment/TrainedModelDeploymentTaskTests.java
Labels: backport, v8.0.0, auto-merge

#81264 [DOCS] Fix syntax error in bulk API's `dynamic_templates` docs
  docs/reference/rest-api/common-parms.asciidoc
Labels: >docs, Team:Docs, v7.13.5, auto-backport-and-merge, v7.14.3, v7.16.1, v8.1.0, v8.0.0-beta1, v7.15.3

#81267 [7.16] [DOCS] Fix syntax error in bulk `dynamic_templates` docs (#81264)
  docs/reference/rest-api/common-parms.asciidoc
Labels: backport, auto-merge, v7.16.1

#81268 [8.0] [DOCS] Fix syntax error in bulk `dynamic_templates` docs (#81264)
  docs/reference/rest-api/common-parms.asciidoc
Labels: backport, v8.0.0, auto-merge

#81269 [7.15] [DOCS] Fix syntax error in bulk `dynamic_templates` docs (#81264)
  docs/reference/rest-api/common-parms.asciidoc
Labels: backport, auto-merge, v7.15.3

#81270 [7.14] [DOCS] Fix syntax error in bulk `dynamic_templates` docs (#81264)
  docs/reference/rest-api/common-parms.asciidoc
Labels: backport, v7.14.3

#81271 [7.13] [DOCS] Fix syntax error in bulk `dynamic_templates` docs (#81264)
  docs/reference/rest-api/common-parms.asciidoc
Labels: backport, v7.13.5

#81266 Script: keyword fields api support
  docs/changelog/81266.yaml
  modules/lang-painless/src/main/resources/org/elasticsearch/painless/org.elasticsearch.script.fields.txt
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/50_script_doc_values.yml
  server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/elasticsearch/script/field/KeywordDocValuesField.java
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra, v8.1.0

#81129 [DOCS] Adds missing timeout parameter to transform APIs
  docs/reference/rest-api/common-parms.asciidoc
  docs/reference/transform/apis/delete-transform.asciidoc
  docs/reference/transform/apis/preview-transform.asciidoc
  docs/reference/transform/apis/put-transform.asciidoc
  docs/reference/transform/apis/reset-transform.asciidoc
  docs/reference/transform/apis/start-transform.asciidoc
  docs/reference/transform/apis/stop-transform.asciidoc
  docs/reference/transform/apis/update-transform.asciidoc
  docs/reference/transform/apis/upgrade-transforms.asciidoc
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.delete_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.preview_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.put_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.reset_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.update_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.upgrade_transforms.json
Labels: >docs, v8.0.0, :ml/Transform, Team:Docs, Team:Clients, Team:ML, v7.16.1, v8.1.0

#81272 Add date fields to the scripting fields api
  docs/changelog/81272.yaml
  modules/lang-painless/src/main/resources/org/elasticsearch/painless/org.elasticsearch.script.fields.txt
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/50_script_doc_values.yml
  server/src/main/java/org/elasticsearch/index/fielddata/ScriptDocValues.java
  server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/elasticsearch/script/field/DateMillisDocValuesField.java
  server/src/main/java/org/elasticsearch/script/field/DateNanosDocValuesField.java
  server/src/test/java/org/elasticsearch/index/mapper/DateFieldTypeTests.java
  x-pack/plugin/mapper-unsigned-long/src/main/java/org/elasticsearch/xpack/unsignedlong/UnsignedLongDocValuesField.java
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra, v8.1.0

#81277 [8.0][DOCS] Adds missing timeout parameter to transform APIs (#81129)
  docs/reference/rest-api/common-parms.asciidoc
  docs/reference/transform/apis/delete-transform.asciidoc
  docs/reference/transform/apis/preview-transform.asciidoc
  docs/reference/transform/apis/put-transform.asciidoc
  docs/reference/transform/apis/start-transform.asciidoc
  docs/reference/transform/apis/stop-transform.asciidoc
  docs/reference/transform/apis/update-transform.asciidoc
  docs/reference/transform/apis/upgrade-transforms.asciidoc
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.delete_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.preview_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.put_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.update_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.upgrade_transforms.json
Labels: backport, v8.0.0

#81278 [7.16][DOCS] Adds missing timeout parameter to transform APIs (#81129)
  docs/reference/rest-api/common-parms.asciidoc
  docs/reference/transform/apis/delete-transform.asciidoc
  docs/reference/transform/apis/preview-transform.asciidoc
  docs/reference/transform/apis/put-transform.asciidoc
  docs/reference/transform/apis/start-transform.asciidoc
  docs/reference/transform/apis/stop-transform.asciidoc
  docs/reference/transform/apis/update-transform.asciidoc
  docs/reference/transform/apis/upgrade-transforms.asciidoc
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.delete_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.preview_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.put_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.update_transform.json
  rest-api-spec/src/main/resources/rest-api-spec/api/transform.upgrade_transforms.json
Labels: backport, v7.16.1

#81032 SQL: Fix rearranging columns in PIVOT queries
  x-pack/plugin/sql/qa/server/src/main/resources/pivot.csv-spec
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SourceGenerator.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/GlobalCountRef.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/QueryContainer.java
  x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryFolderTests.java
  x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java
Labels: >bug, :Query Languages/SQL, Team:QL, auto-backport-and-merge, v7.16.1, v8.1.0

#81243 Update gradle version to bugfix version 7.3.1
  build-tools-internal/gradle/wrapper/gradle-wrapper.properties
  build-tools-internal/src/main/resources/minimumGradleVersion
  gradle/wrapper/gradle-wrapper.properties
Labels: >enhancement, :Delivery/Build, Team:Delivery, auto-merge, v7.16.0, auto-backport-and-merge, v8.1.0

#81287 [7.16] SQL: Fix rearranging columns in PIVOT queries (#81032)
  x-pack/plugin/sql/qa/server/src/main/resources/pivot.csv-spec
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SourceGenerator.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/GlobalCountRef.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/QueryContainer.java
  x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryFolderTests.java
  x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java
Labels: backport, auto-merge, v7.16.1

#81280 Fix typo in field_caps API
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/field_caps/40_time_series.yml
  server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilities.java
Labels: >non-issue, :Search/Mapping, v8.0.0, Team:Search, Team:Analytics, auto-backport, :Analytics/TSDB, v8.1.0

#81288 [7.16] Update gradle version to bugfix version 7.3.1 (#81243)
  build-tools-internal/gradle/wrapper/gradle-wrapper.properties
  build-tools-internal/src/main/resources/minimumGradleVersion
  gradle/wrapper/gradle-wrapper.properties
Labels: backport, auto-merge, v7.16.1

#81253 Fix docs for passing JVM args to ./gradlew run
  TESTING.asciidoc
Labels: >non-issue, Team:Delivery, :Delivery/Tooling, v8.1.0

#81291 [8.0] Fix typo in field_caps API (#81280)
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/field_caps/40_time_series.yml
  server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilities.java
Labels: backport, v8.0.0

#81294 [8.0] SQL: Fix rearranging columns in PIVOT queries (#81032)
  x-pack/plugin/sql/qa/server/src/main/resources/pivot.csv-spec
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/SourceGenerator.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/GlobalCountRef.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/QueryContainer.java
  x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryFolderTests.java
  x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java
Labels: backport, v8.0.0, auto-merge

#81245 Use Cloudflare's zlib in Docker images
  distribution/docker/build.gradle
  distribution/docker/src/docker/Dockerfile
  distribution/src/bin/elasticsearch
  docs/changelog/81245.yaml
  qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java
Labels: >enhancement, :Delivery/Packaging, v8.0.0, Team:Delivery, auto-merge, v8.1.0

#81298 [TSDB] Lower version tested after backporting PR #81291
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/field_caps/40_time_series.yml
Labels: >test, Team:Analytics, :Analytics/TSDB, v8.1.0

#81300 [Transform] Fix wire compatibility version for transform cluster state
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/TransformMetadata.java
Labels: >bug, :ml/Transform, Team:ML, v7.16.1

#81281 [7.16] Increase test timeout for CoordinatorTests testAllSearchesExecuted
  x-pack/plugin/enrich/src/test/java/org/elasticsearch/xpack/enrich/action/CoordinatorTests.java
Labels: >test, :Data Management/Ingest, backport, Team:Data Management, v7.16.1

#81274 [TEST] Add few additional MDP tests
  server/src/test/java/org/elasticsearch/gateway/PersistedClusterStateServiceTests.java
  server/src/test/java/org/elasticsearch/index/shard/RemoveCorruptedShardDataCommandTests.java
Labels: >test, :Core/Infra/Core, Team:Core/Infra, v8.1.0

#81308 Fix channel open trace logging
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
Labels: >bug, :Distributed/Network, v8.0.0, Team:Distributed, auto-backport-and-merge, v7.16.1, v8.1.0

#81311 [8.0] Fix channel open trace logging (#81308)
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
Labels: backport, v8.0.0, auto-merge

#81314 Fix channel open trace logging (#81308)
  server/src/main/java/org/elasticsearch/transport/TcpTransport.java
Labels: backport, auto-merge, v7.16.1

#81316 [8.0] Increase test timeout for CoordinatorTests testAllSearchesExecuted
  x-pack/plugin/enrich/src/test/java/org/elasticsearch/xpack/enrich/action/CoordinatorTests.java
Labels: >test, :Data Management/Ingest, backport, v8.0.0, Team:Data Management

#81315 [DOCS] Move trained model APIs out of dataframe analytics
  docs/reference/ml/df-analytics/apis/index.asciidoc
  docs/reference/ml/df-analytics/apis/ml-df-analytics-apis.asciidoc
  docs/reference/ml/trained-models/apis/delete-trained-models-aliases.asciidoc
  docs/reference/ml/trained-models/apis/delete-trained-models.asciidoc
  docs/reference/ml/trained-models/apis/get-trained-model-deployment-stats.asciidoc
  docs/reference/ml/trained-models/apis/get-trained-models-stats.asciidoc
  docs/reference/ml/trained-models/apis/get-trained-models.asciidoc
  docs/reference/ml/trained-models/apis/index.asciidoc
  docs/reference/ml/trained-models/apis/infer-trained-model-deployment.asciidoc
  docs/reference/ml/trained-models/apis/ml-trained-models-apis.asciidoc
  docs/reference/ml/trained-models/apis/put-trained-model-definition-part.asciidoc
  docs/reference/ml/trained-models/apis/put-trained-model-vocabulary.asciidoc
  docs/reference/ml/trained-models/apis/put-trained-models-aliases.asciidoc
  docs/reference/ml/trained-models/apis/put-trained-models.asciidoc
  docs/reference/ml/trained-models/apis/start-trained-model-deployment.asciidoc
  docs/reference/ml/trained-models/apis/stop-trained-model-deployment.asciidoc
  docs/reference/rest-api/index.asciidoc
Labels: >docs, :ml, v8.0.0, Team:Docs, Team:ML, v7.16.1, v8.1.0

#81323 [8.0][DOCS] Move trained model APIs out of dataframe analytics (#81315)
  docs/reference/ml/df-analytics/apis/index.asciidoc
  docs/reference/ml/df-analytics/apis/ml-df-analytics-apis.asciidoc
  docs/reference/ml/trained-models/apis/delete-trained-models-aliases.asciidoc
  docs/reference/ml/trained-models/apis/delete-trained-models.asciidoc
  docs/reference/ml/trained-models/apis/get-trained-model-deployment-stats.asciidoc
  docs/reference/ml/trained-models/apis/get-trained-models-stats.asciidoc
  docs/reference/ml/trained-models/apis/get-trained-models.asciidoc
  docs/reference/ml/trained-models/apis/index.asciidoc
  docs/reference/ml/trained-models/apis/infer-trained-model-deployment.asciidoc
  docs/reference/ml/trained-models/apis/ml-trained-models-apis.asciidoc
  docs/reference/ml/trained-models/apis/put-trained-model-definition-part.asciidoc
  docs/reference/ml/trained-models/apis/put-trained-model-vocabulary.asciidoc
  docs/reference/ml/trained-models/apis/put-trained-models-aliases.asciidoc
  docs/reference/ml/trained-models/apis/put-trained-models.asciidoc
  docs/reference/ml/trained-models/apis/start-trained-model-deployment.asciidoc
  docs/reference/ml/trained-models/apis/stop-trained-model-deployment.asciidoc
  docs/reference/rest-api/index.asciidoc
Labels: backport, v8.0.0

#81324 [7.16][DOCS] Move trained model APIs out of dataframe analytics (#81315)
  docs/reference/ml/df-analytics/apis/index.asciidoc
  docs/reference/ml/df-analytics/apis/ml-df-analytics-apis.asciidoc
  docs/reference/ml/trained-models/apis/delete-trained-models-aliases.asciidoc
  docs/reference/ml/trained-models/apis/delete-trained-models.asciidoc
  docs/reference/ml/trained-models/apis/get-trained-models-stats.asciidoc
  docs/reference/ml/trained-models/apis/get-trained-models.asciidoc
  docs/reference/ml/trained-models/apis/index.asciidoc
  docs/reference/ml/trained-models/apis/ml-trained-models-apis.asciidoc
  docs/reference/ml/trained-models/apis/put-trained-models-aliases.asciidoc
  docs/reference/ml/trained-models/apis/put-trained-models.asciidoc
  docs/reference/rest-api/index.asciidoc
Labels: backport, v7.16.1

#81317 Revert some EQL shadowed var changes and improve HiddenField rule
  build-conventions/src/main/java/org/elasticsearch/gradle/internal/checkstyle/HiddenFieldCheck.java
  build-tools-internal/src/main/resources/checkstyle.xml
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/execution/assembler/Criterion.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/StringContainsFunctionPipe.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plan/logical/Join.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plan/physical/EsQueryExec.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plan/physical/SequenceExec.java
  x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/querydsl/container/QueryContainer.java
Labels: >refactoring, v8.0.0, Team:Delivery, :Delivery/Tooling, v7.16.1, v8.1.0

#79756 Monitoring migration guide updates
  docs/reference/migration/migrate_7_16.asciidoc
Labels: >docs, :Data Management/Monitoring, v8.0.0, Team:Data Management, Team:Docs, v7.16.1, v8.1.0

#81325 [DOCS] Fixes broken links to clients
  docs/java-api/client.asciidoc
  docs/java-api/index.asciidoc
  docs/reference/setup/setup-xclient.asciidoc
  x-pack/docs/en/security/tribe-clients-integrations/java.asciidoc
  x-pack/docs/en/watcher/java.asciidoc
Labels: >docs, v6.0.3, v6.1.5, v6.2.5, v6.3.3, v6.4.4, v6.5.5, v6.6.3, v5.6.17, v6.7.3, Team:Docs, auto-backport, v6.8.21

#81331 [6.7][DOCS] Fixes broken links to clients (#81325)
  docs/java-api/client.asciidoc
  docs/java-api/index.asciidoc
  docs/reference/setup/setup-xclient.asciidoc
  x-pack/docs/en/security/tribe-clients-integrations/java.asciidoc
  x-pack/docs/en/watcher/java.asciidoc
Labels: backport, v6.7.3

#81310 Adding discovery.zen.bwc_ping_timeout to the list of removed zen settings
  docs/reference/migration/migrate_8_0/cluster-node-setting-changes.asciidoc
Labels: :Data Management/Other, v8.0.0, Team:Data Management, auto-backport-and-merge, v8.1.0

#81282 Adding a deprecation info API check for discovery.zen.minimum_master_nodes
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/DeprecationChecks.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/NodeDeprecationChecks.java
  x-pack/plugin/deprecation/src/test/java/org/elasticsearch/xpack/deprecation/NodeDeprecationChecksTests.java
Labels: >bug, :Data Management/Other, Team:Data Management, v7.16.1

#81332 [6.6][DOCS] Fixes broken links to clients (#81325)
  docs/java-api/client.asciidoc
  docs/java-api/index.asciidoc
  docs/reference/setup/setup-xclient.asciidoc
  x-pack/docs/en/security/tribe-clients-integrations/java.asciidoc
  x-pack/docs/en/watcher/java.asciidoc
Labels: backport, v6.6.3

#81333 [6.5][DOCS] Fixes broken links to clients (#81325)
  docs/java-api/client.asciidoc
  docs/java-api/index.asciidoc
  docs/reference/setup/setup-xclient.asciidoc
  x-pack/docs/en/security/tribe-clients-integrations/java.asciidoc
  x-pack/docs/en/watcher/java.asciidoc
Labels: backport, v6.5.5

#81334 [6.4][DOCS] Fixes broken links to clients (#81325)
  docs/java-api/client.asciidoc
  docs/java-api/index.asciidoc
  docs/reference/setup/setup-xclient.asciidoc
  x-pack/docs/en/security/tribe-clients-integrations/java.asciidoc
  x-pack/docs/en/watcher/java.asciidoc
Labels: v6.4.4, backport

#81307 [DOCS] Fix the weighed average documentation
  docs/reference/aggregations/metrics/weighted-avg-aggregation.asciidoc
Labels: >docs, :Analytics/Aggregations, v8.0.0, Team:Docs, Team:Analytics, auto-backport-and-merge, v7.16.1, v8.1.0, v7.15.3

#81339 [6.3][DOCS] Fixes broken links to clients (#81325)
  docs/java-api/client.asciidoc
  docs/java-api/index.asciidoc
  docs/reference/setup/setup-xclient.asciidoc
  x-pack/docs/en/security/tribe-clients-integrations/java.asciidoc
  x-pack/docs/en/watcher/java.asciidoc
Labels: v6.3.3, backport

#81341 [8.0] Adding discovery.zen.bwc_ping_timeout to the list of removed zen settings (#81310)
  docs/reference/migration/migrate_8_0/cluster-node-setting-changes.asciidoc
Labels: backport, v8.0.0, auto-merge

#81306 Add YAML REST test for the weighted average aggregation
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search.aggregation/440_weighted_avg.yml
Labels: >test, :Analytics/Aggregations, Team:Analytics, v8.1.0

#81340 [6.2][DOCS] Fixes broken links to clients (#81325)
  docs/java-api/client.asciidoc
  docs/java-api/index.asciidoc
Labels: v6.2.5, backport

#81336 [6.1][DOCS] Fixes broken links to clients (#81325)
  docs/java-api/client.asciidoc
  docs/java-api/index.asciidoc
Labels: v6.1.5, backport

#81337 [6.0][DOCS] Fixes broken links to clients (#81325)
  docs/java-api/client.asciidoc
  docs/java-api/index.asciidoc
Labels: v6.0.3, backport

#81338 [5.6][DOCS] Fixes broken links to clients (#81325)
  docs/java-api/client.asciidoc
  docs/java-api/index.asciidoc
Labels: backport, v5.6.17

#81342 Fix Serialization version check in Shutdown Status
  server/src/main/java/org/elasticsearch/cluster/metadata/ShutdownShardMigrationStatus.java
Labels: >non-issue, v8.0.0, Team:Core/Infra, :Core/Infra/Node Lifecycle, auto-merge, auto-backport-and-merge, v8.1.0

#81235 Disallow explicitly requesting system indices in snapshots
  server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
Labels: >non-issue, :Distributed/Snapshot/Restore, v8.0.0, Team:Distributed, auto-merge, auto-backport-and-merge, v8.1.0

#81344 [8.0] Fix Serialization version check in Shutdown Status (#81342)
  server/src/main/java/org/elasticsearch/cluster/metadata/ShutdownShardMigrationStatus.java
Labels: backport, v8.0.0, auto-merge

#81346 [8.0] Disallow explicitly requesting system indices in snapshots (#81235)
  server/src/internalClusterTest/java/org/elasticsearch/snapshots/SystemIndicesSnapshotIT.java
  server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
Labels: backport, v8.0.0, auto-merge

#81347 [DOCS] Fixes link to language identification example
  docs/reference/ingest/processors/inference.asciidoc
Labels: >docs, :ml, v8.0.0, Team:Docs, Team:ML, auto-backport, v8.1.0

#80437 Add Linux x86-64bits native method to retrieve the number of allocated bytes on disk for a file
  server/src/main/java/org/elasticsearch/common/filesystem/FileSystemNatives.java
  server/src/main/java/org/elasticsearch/common/filesystem/LinuxFileSystemNatives.java
  test/framework/src/main/java/org/elasticsearch/bootstrap/BootstrapForTesting.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFileTests.java
Labels: >enhancement, :Distributed/Snapshot/Restore, Team:Distributed, v8.1.0

#81321 SQL: Extend Tableau connector to reconnect with catalog
  x-pack/plugin/sql/connectors/tableau/connector/connectionProperties.js
  x-pack/plugin/sql/connectors/tableau/connector/connectionResolver.tdr
Labels: >enhancement, :Query Languages/SQL, Team:QL, auto-merge, v8.1.0

#81318 Quiesce test security manager and illegal access warnings
  build-tools-internal/src/main/groovy/elasticsearch.ide.gradle
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchTestBasePlugin.java
  test/framework/src/main/java/org/elasticsearch/bootstrap/BootstrapForTesting.java
Labels: v8.1.0

#81077 Robust error handling for enrollment calls
  qa/os/src/test/java/org/elasticsearch/packaging/test/EnrollNodeToClusterTests.java
  qa/os/src/test/java/org/elasticsearch/packaging/test/EnrollmentProcessTests.java
  x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java
Labels: >bug, :Security/Security, v8.0.0, Team:Security, v8.1.0

#81330 [DOCS] Change <cacert> to <timestamp> with matching description
  x-pack/docs/en/security/configuring-stack-security.asciidoc
Labels: v8.0.0, auto-backport, v8.1.0

#81295 Add explicit warning not to touch repository contents
  docs/reference/snapshot-restore/index.asciidoc
Labels: >docs, :Distributed/Snapshot/Restore, v8.0.0, Team:Distributed, Team:Docs, auto-backport-and-merge, v7.16.1, v8.1.0

#81363 Mute CacheFileTests.testCacheFileCreatedAsSparseFile for aarch64
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFileTests.java
Labels: >test, :Distributed/Snapshot/Restore, >test-mute, Team:Distributed, auto-merge, v8.1.0

#81365 [8.0] Add explicit warning not to touch repository contents (#81295)
  docs/reference/snapshot-restore/index.asciidoc
Labels: backport, v8.0.0, auto-merge

#81366 [7.16] Add explicit warning not to touch repository contents (#81295)
  docs/reference/snapshot-restore/index.asciidoc
Labels: backport, auto-merge, v7.16.1

#81254 [ML] Ensure `BertTokenizer` does not split special tokens
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BasicTokenizer.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/TokenTrieNode.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BasicTokenizerTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BertTokenizerTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/TokenTrieNodeTests.java
Labels: >bug, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0

#81364 [8.0] [DOCS] Change <cacert> to <timestamp> with matching description (#81330)
  x-pack/docs/en/security/configuring-stack-security.asciidoc
Labels: backport, v8.0.0

#81360 [ML] Make PUT trained model definition part action a handled transpor…
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportPutTrainedModelDefinitionPartAction.java
Labels: >non-issue, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0

#81371 [8.0] [ML] Ensure `BertTokenizer` does not split special tokens (#81254)
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BasicTokenizer.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/TokenTrieNode.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BasicTokenizerTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BertTokenizerTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/TokenTrieNodeTests.java
Labels: backport, v8.0.0, auto-merge

#81285 Granting editor and viewer roles access to alerts-as-data indices
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStore.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java
Labels: >enhancement, :Security/Authorization, v8.0.0, Team:Security, external-contributor, auto-backport, v8.1.0

#81348 [8.0] [DOCS] Fixes link to language identification example (#81347)
  docs/reference/ingest/processors/inference.asciidoc
Labels: backport, v8.0.0

#81335 Add plumbing for geo point and geo shape fields for the scripting fields api
  server/src/main/java/org/elasticsearch/index/fielddata/GeoPointScriptFieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/AbstractLatLonPointIndexFieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/AbstractLeafGeoPointFieldData.java
  server/src/main/java/org/elasticsearch/index/fielddata/plain/LatLonPointDVLeafFieldData.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoPointScriptFieldType.java
  server/src/main/java/org/elasticsearch/search/sort/GeoDistanceSortBuilder.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/plain/AbstractAtomicGeoShapeShapeFieldData.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/plain/AbstractLatLonShapeIndexFieldData.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/plain/LatLonShapeDVAtomicShapeFieldData.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldMapper.java
Labels: :Core/Infra/Scripting, >refactoring, Team:Core/Infra, v8.1.0

#80851 Bump source compatibility version to Java 17
  .ci/java-versions.properties
  build-conventions/build.gradle
  build-tools-internal/build.gradle
  build-tools-internal/src/integTest/groovy/org/elasticsearch/gradle/internal/InternalDistributionBwcSetupPluginFuncTest.groovy
  build-tools-internal/src/integTest/resources/org/elasticsearch/gradle/internal/fake_git/remote/build-tools-internal/src/main/resources/minimumCompilerVersion
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchJavaBasePlugin.java
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/precommit/ForbiddenApisPrecommitPlugin.java
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/precommit/ThirdPartyAuditPrecommitPlugin.java
  build-tools-internal/src/main/resources/forbidden/jdk-deprecated.txt
  build-tools-internal/src/main/resources/minimumCompilerVersion
  build-tools-internal/src/main/resources/minimumRuntimeVersion
  build-tools-internal/src/testKit/thirdPartyAudit/build.gradle
  modules/ingest-geoip/build.gradle
  modules/transport-netty4/build.gradle
  plugins/discovery-ec2/build.gradle
  plugins/discovery-gce/build.gradle
  plugins/examples/build.gradle
  plugins/repository-azure/build.gradle
  plugins/repository-gcs/build.gradle
  plugins/transport-nio/build.gradle
  qa/wildfly/build.gradle
  qa/wildfly/docker-compose.yml
  qa/wildfly/src/main/java/org/elasticsearch/wildfly/model/Employee.java
  qa/wildfly/src/main/java/org/elasticsearch/wildfly/transport/RestHighLevelClientActivator.java
  qa/wildfly/src/main/java/org/elasticsearch/wildfly/transport/RestHighLevelClientEmployeeResource.java
  qa/wildfly/src/main/java/org/elasticsearch/wildfly/transport/RestHighLevelClientProducer.java
  qa/wildfly/src/main/java/org/elasticsearch/wildfly/transport/RestHighLevelJacksonJsonProvider.java
  qa/wildfly/src/main/resources/log4j2.properties
  qa/wildfly/src/main/webapp/WEB-INF/beans.xml
  qa/wildfly/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
  qa/wildfly/src/test/java/org/elasticsearch/wildfly/WildflyIT.java
  server/build.gradle
  test/fixtures/azure-fixture/Dockerfile
  test/fixtures/gcs-fixture/Dockerfile
  test/fixtures/geoip-fixture/Dockerfile
  test/fixtures/s3-fixture/Dockerfile
  test/fixtures/url-fixture/Dockerfile
  test/framework/build.gradle
  test/logger-usage/build.gradle
  test/logger-usage/src/main/java/org/elasticsearch/test/loggerusage/ESLoggerUsageChecker.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/utils/time/DateTimeFormatterTimestampConverter.java
  x-pack/plugin/identity-provider/build.gradle
  x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/type/DateUtils.java
  x-pack/plugin/security/build.gradle
  x-pack/plugin/sql/sql-action/build.gradle
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/util/DateUtils.java
Labels: >non-issue, :Delivery/Build, v8.0.0, Team:Delivery, auto-backport-and-merge, v8.1.0

#79512 All system indices are hidden indices
  docs/changelog/79512.yaml
  modules/kibana/src/javaRestTest/java/org/elasticsearch/kibana/KibanaSystemIndexIT.java
  modules/reindex/build.gradle
  modules/reindex/src/internalClusterTest/java/org/elasticsearch/migration/FeatureMigrationIT.java
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/delete_by_query/70_throttle.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/delete_by_query/80_slices.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/80_slices.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/update_by_query/70_slices.yml
  qa/smoke-test-http/src/test/java/org/elasticsearch/http/SystemIndexRestIT.java
  qa/system-indices/src/javaRestTest/java/org/elasticsearch/system/indices/SystemAliasIT.java
  qa/system-indices/src/main/java/org/elasticsearch/system/indices/SystemIndicesQA.java
  server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/create/AutoCreateSystemIndexIT.java
  server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/create/CreateSystemIndicesIT.java
  server/src/internalClusterTest/java/org/elasticsearch/aliases/SystemIndexAliasIT.java
  server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java
  server/src/main/java/org/elasticsearch/action/admin/indices/alias/TransportIndicesAliasesAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/AutoCreateAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreateIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/template/post/TransportSimulateIndexTemplateAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/template/post/TransportSimulateTemplateAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateDataStreamService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/SystemIndexMetadataUpgradeService.java
  server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/TransportCreateIndexActionTests.java
  server/src/test/java/org/elasticsearch/action/admin/indices/settings/put/TransportUpdateSettingsActionTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataCreateDataStreamServiceTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/SystemIndexMetadataUpgradeServiceTests.java
  server/src/test/java/org/elasticsearch/indices/SystemIndexDescriptorTests.java
  server/src/test/java/org/elasticsearch/indices/SystemIndexManagerTests.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java
  x-pack/plugin/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/SystemDataStreamIT.java
  x-pack/plugin/fleet/src/javaRestTest/java/org/elasticsearch/xpack/fleet/FleetDataStreamIT.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsSystemIndicesIntegTests.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/SnapshotUserRoleIntegTests.java
  x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/history/HistoryTemplateTimeMappingsTests.java
  x-pack/qa/multi-cluster-search-security/src/test/resources/rest-api-spec/test/multi_cluster/100_resolve_index.yml
Labels: >enhancement, :Core/Infra/Core, v8.0.0, Team:Core/Infra, auto-backport, v8.1.0

#81387 [8.0] Bump source compatibility version to Java 17 (#80851)
  .ci/java-versions.properties
  build-conventions/build.gradle
  build-tools-internal/build.gradle
  build-tools-internal/src/integTest/resources/org/elasticsearch/gradle/internal/fake_git/remote/build-tools-internal/src/main/resources/minimumCompilerVersion
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchJavaBasePlugin.java
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/precommit/ForbiddenApisPrecommitPlugin.java
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/precommit/ThirdPartyAuditPrecommitPlugin.java
  build-tools-internal/src/main/resources/forbidden/jdk-deprecated.txt
  build-tools-internal/src/main/resources/minimumCompilerVersion
  build-tools-internal/src/main/resources/minimumRuntimeVersion
  build-tools-internal/src/testKit/thirdPartyAudit/build.gradle
  modules/ingest-geoip/build.gradle
  modules/transport-netty4/build.gradle
  plugins/discovery-ec2/build.gradle
  plugins/discovery-gce/build.gradle
  plugins/examples/build.gradle
  plugins/repository-azure/build.gradle
  plugins/repository-gcs/build.gradle
  plugins/transport-nio/build.gradle
  qa/wildfly/build.gradle
  qa/wildfly/docker-compose.yml
  qa/wildfly/src/main/java/org/elasticsearch/wildfly/model/Employee.java
  qa/wildfly/src/main/java/org/elasticsearch/wildfly/transport/RestHighLevelClientActivator.java
  qa/wildfly/src/main/java/org/elasticsearch/wildfly/transport/RestHighLevelClientEmployeeResource.java
  qa/wildfly/src/main/java/org/elasticsearch/wildfly/transport/RestHighLevelClientProducer.java
  qa/wildfly/src/main/java/org/elasticsearch/wildfly/transport/RestHighLevelJacksonJsonProvider.java
  qa/wildfly/src/main/resources/log4j2.properties
  qa/wildfly/src/main/webapp/WEB-INF/beans.xml
  qa/wildfly/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
  qa/wildfly/src/test/java/org/elasticsearch/wildfly/WildflyIT.java
  server/build.gradle
  test/fixtures/azure-fixture/Dockerfile
  test/fixtures/gcs-fixture/Dockerfile
  test/fixtures/geoip-fixture/Dockerfile
  test/fixtures/s3-fixture/Dockerfile
  test/fixtures/url-fixture/Dockerfile
  test/framework/build.gradle
  test/logger-usage/build.gradle
  test/logger-usage/src/main/java/org/elasticsearch/test/loggerusage/ESLoggerUsageChecker.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/utils/time/DateTimeFormatterTimestampConverter.java
  x-pack/plugin/identity-provider/build.gradle
  x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/type/DateUtils.java
  x-pack/plugin/security/build.gradle
  x-pack/plugin/sql/sql-action/build.gradle
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/util/DateUtils.java
Labels: backport, v8.0.0

#81388 [8.0] All system indices are hidden indices (#79512)
  docs/changelog/79512.yaml
  modules/kibana/src/javaRestTest/java/org/elasticsearch/kibana/KibanaSystemIndexIT.java
  modules/reindex/build.gradle
  modules/reindex/src/internalClusterTest/java/org/elasticsearch/migration/FeatureMigrationIT.java
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/delete_by_query/70_throttle.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/delete_by_query/80_slices.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/80_slices.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/update_by_query/70_slices.yml
  qa/smoke-test-http/src/test/java/org/elasticsearch/http/SystemIndexRestIT.java
  qa/system-indices/src/javaRestTest/java/org/elasticsearch/system/indices/SystemAliasIT.java
  qa/system-indices/src/main/java/org/elasticsearch/system/indices/SystemIndicesQA.java
  server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/create/AutoCreateSystemIndexIT.java
  server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/create/CreateSystemIndicesIT.java
  server/src/internalClusterTest/java/org/elasticsearch/aliases/SystemIndexAliasIT.java
  server/src/internalClusterTest/java/org/elasticsearch/cluster/ClusterInfoServiceIT.java
  server/src/main/java/org/elasticsearch/action/admin/indices/alias/TransportIndicesAliasesAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/AutoCreateAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/create/TransportCreateIndexAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/template/post/TransportSimulateIndexTemplateAction.java
  server/src/main/java/org/elasticsearch/action/admin/indices/template/post/TransportSimulateTemplateAction.java
  server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateDataStreamService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/elasticsearch/cluster/metadata/SystemIndexMetadataUpgradeService.java
  server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java
  server/src/test/java/org/elasticsearch/action/admin/indices/create/TransportCreateIndexActionTests.java
  server/src/test/java/org/elasticsearch/action/admin/indices/settings/put/TransportUpdateSettingsActionTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataCreateDataStreamServiceTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/SystemIndexMetadataUpgradeServiceTests.java
  server/src/test/java/org/elasticsearch/indices/SystemIndexDescriptorTests.java
  server/src/test/java/org/elasticsearch/indices/SystemIndexManagerTests.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/datafeed/DatafeedConfig.java
  x-pack/plugin/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/SystemDataStreamIT.java
  x-pack/plugin/fleet/src/javaRestTest/java/org/elasticsearch/xpack/fleet/FleetDataStreamIT.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshotsSystemIndicesIntegTests.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authz/SnapshotUserRoleIntegTests.java
  x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/history/HistoryTemplateTimeMappingsTests.java
  x-pack/qa/multi-cluster-search-security/src/test/resources/rest-api-spec/test/multi_cluster/100_resolve_index.yml
Labels: backport, v8.0.0

#81390 [DOCS] Fix 7.16 breaking change formatting
  docs/reference/migration/migrate_7_16.asciidoc
Labels: >docs, Team:Docs, v7.16.0

#81392 Granting kibana_system reserved role access to "all" privileges to .internal.preview.alerts* index (#80889)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStore.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java
Labels: backport, v8.0.0, auto-merge

#81263 TSDB: Cleaner trigger for tsdb boundary check
  server/src/main/java/org/elasticsearch/index/IndexMode.java
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
  server/src/main/java/org/elasticsearch/index/TimestampBounds.java
  server/src/main/java/org/elasticsearch/index/mapper/DataStreamTimestampFieldMapper.java
  server/src/test/java/org/elasticsearch/index/IndexSettingsTests.java
Labels: >non-issue, Team:Analytics, auto-merge, :Analytics/TSDB, v8.1.0

#81389 _tier_preference docs changes for 8.0
  docs/reference/datatiers.asciidoc
  docs/reference/index-modules/allocation/data_tier_allocation.asciidoc
Labels: >non-issue, :Data Management/ILM+SLM, v8.0.0, Team:Data Management, v8.1.0

#80926 Refactor CompositeRolesStore for separation of concerns
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authc/AuthenticationContext.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authc/AuthenticationField.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authc/Subject.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/permission/LimitedRole.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/RoleKey.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/RoleReference.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/RoleReferenceResolver.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/RolesRetrievalResult.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/user/User.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authc/SubjectTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/RoleReferenceTests.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/ApiKeyService.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/AuthenticatorChain.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/service/ServiceAccountService.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/RBACEngine.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/RoleDescriptorStore.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ApiKeyServiceTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/AuthorizationServiceTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolverTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStoreTests.java
Labels: >refactoring, :Security/Authorization, Team:Security, v8.1.0

#81374 Implement getMinimalSupportedVersion for all NameDiffs
  server/src/main/java/org/elasticsearch/cluster/NamedDiff.java
  server/src/main/java/org/elasticsearch/cluster/metadata/ComponentTemplateMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplateMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexGraveyard.java
  server/src/main/java/org/elasticsearch/cluster/metadata/NodesShutdownMetadata.java
  server/src/main/java/org/elasticsearch/ingest/IngestMetadata.java
  server/src/main/java/org/elasticsearch/script/ScriptMetadata.java
  server/src/main/java/org/elasticsearch/upgrades/FeatureMigrationResults.java
  x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/AutoscalingMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/IndexLifecycleMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/MlMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/slm/SnapshotLifecycleMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/TransformMetadata.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/ModelAliasMetadata.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/allocation/TrainedModelAllocationMetadata.java
Labels: >bug, :Data Management/Indices APIs, v8.0.0, Team:Data Management, v7.16.1, v8.1.0

#81376 Adjust LinuxFileSystemNatives.allocatedSizeInBytes for aarch64 architectures
  server/src/main/java/org/elasticsearch/common/filesystem/LinuxFileSystemNatives.java
  x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFileTests.java
Labels: >bug, :Distributed/Snapshot/Restore, Team:Distributed, v8.1.0

#81410 Mute FullClusterRestartIT testSystemIndexMetadataIsUpgraded
  qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
Labels: :Core/Infra/Core, v8.0.0, >test-mute, Team:Core/Infra, auto-backport, v8.1.0

#81418 [7.15] [DOCS] Fix the weighed average documentation (#81307)
  docs/reference/aggregations/metrics/weighted-avg-aggregation.asciidoc
Labels: backport, auto-merge, v7.15.3

#81417 [7.16] [DOCS] Fix the weighed average documentation (#81307)
  docs/reference/aggregations/metrics/weighted-avg-aggregation.asciidoc
Labels: backport, auto-merge, v7.16.1

#81416 [8.0] [DOCS] Fix the weighed average documentation (#81307)
  docs/reference/aggregations/metrics/weighted-avg-aggregation.asciidoc
Labels: backport, v8.0.0, auto-merge

#81413 [8.0] Mute FullClusterRestartIT testSystemIndexMetadataIsUpgraded (#81410)
  qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java
Labels: backport, v8.0.0

#81414 [8.0] Mute FullClusterRestartIT testSecurityNativeRealm (#81412)
  x-pack/qa/full-cluster-restart/src/test/java/org/elasticsearch/xpack/restart/FullClusterRestartIT.java
Labels: backport, v8.0.0

#81422 Revert "[8.0] [ML] Ensure `BertTokenizer` does not split special toke…
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BasicTokenizer.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/TokenTrieNode.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BasicTokenizerTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BertTokenizerTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/TokenTrieNodeTests.java
Labels: >non-issue, :ml, v8.0.0, Team:ML

#81275 [ML] Track token positions and use source string to tag NER entities
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/results/NerResults.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/BertRequestBuilder.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/FillMaskProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/NerProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BasicTokenizer.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BertTokenizer.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/DelimitedToken.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/NlpTokenizer.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/TokenizationResult.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/WordPieceTokenizer.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/FillMaskProcessorTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/NerProcessorTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BasicTokenizerTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/BertTokenizerTests.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/nlp/tokenizers/WordPieceTokenizerTests.java
Labels: >enhancement, :ml, Team:ML, v8.1.0

#81408 [8.0] Implement getMinimalSupportedVersion for all NameDiffs (#81374)
  server/src/main/java/org/elasticsearch/cluster/NamedDiff.java
  server/src/main/java/org/elasticsearch/cluster/metadata/ComponentTemplateMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplateMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexGraveyard.java
  server/src/main/java/org/elasticsearch/cluster/metadata/NodesShutdownMetadata.java
  server/src/main/java/org/elasticsearch/ingest/IngestMetadata.java
  server/src/main/java/org/elasticsearch/script/ScriptMetadata.java
  server/src/main/java/org/elasticsearch/upgrades/FeatureMigrationResults.java
  x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/AutoscalingMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/IndexLifecycleMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/MlMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/slm/SnapshotLifecycleMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/transform/TransformMetadata.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/ModelAliasMetadata.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/allocation/TrainedModelAllocationMetadata.java
Labels: :Data Management/Indices APIs, backport, v8.0.0, Team:Data Management

#81424 [7.16] Implement getMinimalSupportedVersion for all NameDiffs (#81374)
  server/src/main/java/org/elasticsearch/cluster/NamedDiff.java
  server/src/main/java/org/elasticsearch/cluster/metadata/ComponentTemplateMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplateMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/DataStreamMetadata.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexGraveyard.java
  server/src/main/java/org/elasticsearch/cluster/metadata/NodesShutdownMetadata.java
  server/src/main/java/org/elasticsearch/ingest/IngestMetadata.java
  server/src/main/java/org/elasticsearch/script/ScriptMetadata.java
  server/src/main/java/org/elasticsearch/upgrades/FeatureMigrationResults.java
  x-pack/plugin/autoscaling/src/main/java/org/elasticsearch/xpack/autoscaling/AutoscalingMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/IndexLifecycleMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/MlMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/ModelAliasMetadata.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/slm/SnapshotLifecycleMetadata.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/IndexLifecycleMetadataTests.java
Labels: >bug, :Data Management/Indices APIs, backport, Team:Data Management, v7.16.1

#81290 Stop auto-followers when resetting metadata
  x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java
  x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ccr/AutoFollowMetadata.java
Labels: >bug, :Distributed/CCR, v8.0.0, Team:Distributed, auto-backport-and-merge, v7.16.1, v8.1.0

#81361 Checkstyle shadows vars pt10
  build-tools-internal/src/main/resources/checkstyle.xml
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MachineLearning.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MlInitializationService.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteExpiredDataAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDataFrameAnalyticsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/categorization/CategorizeTextAggregatorFactory.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/categorization/InternalCategorizationAggregation.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/inference/InferencePipelineAggregationBuilder.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/aggs/kstest/BucketCountKSTestAggregator.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/autoscaling/MlAutoscalingDeciderService.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/extractor/scroll/ScrollDataExtractor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/extractor/scroll/ScrollDataExtractorFactory.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DataFrameAnalyticsManager.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DataFrameAnalyticsTask.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/extractor/ExtractedFieldsDetector.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/AnalyticsProcessManager.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/allocation/TrainedModelAllocationNodeService.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/TrainedModelDeploymentTask.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/nlp/ZeroShotClassificationProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/pytorch/process/PyTorchResultProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/JobManager.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/UpdateJobProcessNotifier.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobDataDeleter.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsPersister.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/RecordsQueryBuilder.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/ProcessContext.java
  x-pack/plugin/rollup/src/test/java/org/elasticsearch/xpack/rollup/v2/RollupActionSingleNodeTests.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/SearchableSnapshots.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/action/SearchableSnapshotsStatsResponse.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/FailShardsOnInvalidLicenseClusterListener.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/SearchableSnapshotIndexFoldersDeletionListener.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/decider/SearchableSnapshotEnableAllocationDecider.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/blob/BlobStoreCacheMaintenanceService.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/ByteRange.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFile.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/ProgressListenableActionFuture.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheService.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/store/SearchableSnapshotDirectory.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/store/input/BaseSearchableSnapshotIndexInput.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/integration/IndexPrivilegeIntegTests.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/integration/SecurityClearScrollTests.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/common/CartesianPoint.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/CentroidCalculator.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/Extent.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/GeometryDocValueReader.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/Tile2DVisitor.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/mapper/LatLonShapeDocValuesQuery.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/search/aggregations/InternalGeoLine.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/search/aggregations/bucket/geogrid/BoundedGeoTileGridTiler.java
  x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/DelimitedTextStructureFinderFactory.java
  x-pack/plugin/transform/src/internalClusterTest/java/org/elasticsearch/xpack/transform/checkpoint/TransformCheckpointServiceNodeTests.java
  x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/Transform.java
  x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/ClientTransformIndexer.java
  x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java
  x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java
  x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformIndexerStateTests.java
  x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformIndexerTests.java
Labels: >refactoring, v8.0.0, Team:Delivery, :Delivery/Tooling, v7.16.1, v8.1.0

#81370 [DOCS] Release highlights for 7.16.0
  docs/reference/release-notes/highlights.asciidoc
Labels: >docs, Team:Docs, v7.16.0, v7.16.1

#81369 [DOCS] Release notes for v7.16.0
  docs/reference/release-notes.asciidoc
  docs/reference/release-notes/7.16.asciidoc
Labels: >docs, Team:Docs, v7.16.0, v7.16.1

#81426 Upgrade to released lucene 9.0.0
  build-tools-internal/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.0.0.jar.sha1
  modules/legacy-geo/licenses/lucene-spatial-extras-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  modules/legacy-geo/licenses/lucene-spatial-extras-9.0.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.0.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.0.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.0.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.0.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.0.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.0.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.0.0.jar.sha1
  server/licenses/lucene-analysis-common-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-analysis-common-9.0.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-backward-codecs-9.0.0.jar.sha1
  server/licenses/lucene-core-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-core-9.0.0.jar.sha1
  server/licenses/lucene-grouping-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-grouping-9.0.0.jar.sha1
  server/licenses/lucene-highlighter-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-highlighter-9.0.0.jar.sha1
  server/licenses/lucene-join-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-join-9.0.0.jar.sha1
  server/licenses/lucene-memory-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-memory-9.0.0.jar.sha1
  server/licenses/lucene-misc-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-misc-9.0.0.jar.sha1
  server/licenses/lucene-queries-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-queries-9.0.0.jar.sha1
  server/licenses/lucene-queryparser-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-queryparser-9.0.0.jar.sha1
  server/licenses/lucene-sandbox-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-sandbox-9.0.0.jar.sha1
  server/licenses/lucene-spatial3d-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-spatial3d-9.0.0.jar.sha1
  server/licenses/lucene-suggest-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  server/licenses/lucene-suggest-9.0.0.jar.sha1
  x-pack/plugin/sql/sql-action/licenses/lucene-core-9.0.0-snapshot-cc2a31f2be8.jar.sha1
  x-pack/plugin/sql/sql-action/licenses/lucene-core-9.0.0.jar.sha1
Labels: :Search/Search, >upgrade, v8.0.0, Team:Search, auto-backport-and-merge, v8.1.0

#81402 docs: remove old APM ifeval
  docs/Versions.asciidoc
Labels: >docs, v8.0.0, Team:Docs, external-contributor, v7.16.0, v8.1.0

#81430 [8.0] Stop auto-followers when metadata is resetted (#81290)
  x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java
  x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ccr/AutoFollowMetadata.java
Labels: backport, v8.0.0, auto-merge

#81439 [7.16] [DOCS] Remove outdated APM ifeval (#81402)
  docs/Versions.asciidoc
Labels: backport, auto-merge, v7.16.1

#81438 [8.0] [DOCS] Remove outdated APM ifeval (#81402)
  docs/Versions.asciidoc
Labels: backport, v8.0.0, auto-merge

#81421 Mention prefixes of mounted index in ILM Searchable Snapshot action
  docs/reference/ilm/actions/ilm-searchable-snapshot.asciidoc
Labels: >docs, :Data Management/ILM+SLM, v8.0.0, Team:Data Management, Team:Docs, auto-backport-and-merge, v7.16.1, v8.1.0, v7.15.3

#81441 [8.0] Mention prefixes of mounted index in ILM Searchable Snapshot action (#81421)
  docs/reference/ilm/actions/ilm-searchable-snapshot.asciidoc
Labels: backport, v8.0.0, auto-merge

#81442 [7.16] Mention prefixes of mounted index in ILM Searchable Snapshot action (#81421)
  docs/reference/ilm/actions/ilm-searchable-snapshot.asciidoc
Labels: backport, auto-merge, v7.16.1
