Repository elastic/elasticsearch, pull requests merged in 2022-04, with the labels that each got.

#85584 [8.2] User Profile - rename search to suggest profile (#85196)
  docs/reference/redirects.asciidoc
  rest-api-spec/src/main/resources/rest-api-spec/api/security.suggest_user_profiles.json
  x-pack/docs/en/rest-api/security.asciidoc
  x-pack/docs/en/rest-api/security/disable-user-profile.asciidoc
  x-pack/docs/en/rest-api/security/enable-user-profile.asciidoc
  x-pack/docs/en/rest-api/security/suggest-user-profile.asciidoc
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/profile/SuggestProfilesAction.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/profile/SuggestProfilesRequest.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/profile/SuggestProfilesResponse.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/privilege/WriteProfileDataPrivilegesTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java
  x-pack/plugin/security/qa/operator-privileges-tests/src/javaRestTest/java/org/elasticsearch/xpack/security/operator/Constants.java
  x-pack/plugin/security/qa/profile/src/javaRestTest/java/org/elasticsearch/xpack/security/profile/ProfileIT.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileIntegTests.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/action/profile/TransportSuggestProfilesAction.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/profile/ProfileService.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/rest/action/profile/RestSuggestProfilesAction.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/rest/action/profile/RestSuggestProfilesActionTests.java
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/user_profile/10_basic.yml
Labels: backport, auto-merge, v8.2.1

#85519 Ignore app priv failures when resolving superuser
  docs/changelog/85519.yaml
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStoreTests.java
Labels: >bug, :Security/Authorization, Team:Security, auto-merge, auto-backport-and-merge, v8.2.0, v8.1.3, v8.3.0

#85475 Use Set instead of LongSet in double script field
  server/src/main/java/org/elasticsearch/index/mapper/DoubleScriptFieldType.java
  server/src/main/java/org/elasticsearch/search/runtime/DoubleScriptFieldTermsQuery.java
  server/src/test/java/org/elasticsearch/search/runtime/DoubleScriptFieldTermsQueryTests.java
Labels: :Search/Search, >refactoring, Team:Search, v8.3.0

#85588 [8.1] Ignore app priv failures when resolving superuser (#85519)
  docs/changelog/85519.yaml
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStoreTests.java
Labels: backport, auto-merge, v8.1.3

#85587 [8.2] Ignore app priv failures when resolving superuser (#85519)
  docs/changelog/85519.yaml
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStoreTests.java
Labels: backport, auto-merge, v8.2.1

#85470 Migrate all uses of hppc BitMixer to Lucene
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/precommit/ForbiddenApisPrecommitPlugin.java
  build-tools-internal/src/main/resources/forbidden/es-all-signatures.txt
  build-tools-internal/src/main/resources/forbidden/hppc-signatures.txt
  server/build.gradle
  server/src/main/java/org/elasticsearch/common/lucene/search/function/RandomScoreFunction.java
  server/src/main/java/org/elasticsearch/common/recycler/Recyclers.java
  server/src/main/java/org/elasticsearch/common/util/AbstractPagedHashMap.java
  server/src/main/java/org/elasticsearch/common/util/BytesRefHash.java
  server/src/main/java/org/elasticsearch/common/util/LongLongHash.java
  server/src/main/java/org/elasticsearch/script/ScoreScriptUtils.java
  server/src/main/java/org/elasticsearch/search/aggregations/bucket/sampler/random/RandomSamplingQuery.java
  server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/IncludeExclude.java
  server/src/main/java/org/elasticsearch/search/aggregations/metrics/CardinalityAggregator.java
  server/src/main/java/org/elasticsearch/search/slice/DocValuesSliceQuery.java
  server/src/test/java/org/elasticsearch/search/aggregations/metrics/HyperLogLogPlusPlusSparseTests.java
  server/src/test/java/org/elasticsearch/search/aggregations/metrics/HyperLogLogPlusPlusTests.java
  server/src/test/java/org/elasticsearch/search/aggregations/metrics/InternalCardinalityTests.java
  server/src/test/java/org/elasticsearch/search/slice/DocValuesSliceQueryTests.java
Labels: :Core/Infra/Core, >refactoring, Team:Core/Infra, v8.3.0

#85565 Make the ILM Move to Error Step Batched
  docs/changelog/85565.yaml
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleRunner.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/MoveToErrorStepUpdateTask.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/MoveToErrorStepUpdateTaskTests.java
Labels: >bug, :Data Management/ILM+SLM, Team:Data Management, v8.3.0

#85576 Do not reuse ES log file in testclusters
  build-tools/src/integTest/groovy/org/elasticsearch/gradle/TestClustersPluginFuncTest.groovy
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/RunTask.java
Labels: :Delivery/Build, >refactoring, Team:Delivery, v8.3.0, v8.2.1

#85500 Fix wildcard highlighting on match_only_text
  docs/changelog/85500.yaml
  docs/reference/search/search-your-data/highlighting.asciidoc
  modules/mapper-extras/src/yamlRestTest/resources/rest-api-spec/test/match_only_text/10_basic.yml
  server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/HighlightPhase.java
Labels: >bug, :Search/Highlighting, Team:Search, auto-backport, v7.17.3, v8.3.0, v8.2.1

#85495 replaces BooleanSupplier with a Predicate
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceService.java
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceShardsAllocator.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceServiceTests.java
Labels: :Distributed/Allocation, Team:Distributed

#85594 [8.2] Fix wildcard highlighting on match_only_text (#85500)
  docs/changelog/85500.yaml
  docs/reference/search/search-your-data/highlighting.asciidoc
  modules/mapper-extras/src/yamlRestTest/resources/rest-api-spec/test/match_only_text/10_basic.yml
  server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/HighlightPhase.java
Labels: backport, v8.2.1

#85543 fix: add back tests removed by #85534
  rest-api-spec/build.gradle
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search.aggregation/360_date_histogram.yml
Labels: >test, :Analytics/Aggregations, Team:Analytics, v8.3.0

#85593 [7.17] Fix wildcard highlighting on match_only_text (#85500)
  docs/changelog/85500.yaml
  docs/reference/search/search-your-data/highlighting.asciidoc
  modules/mapper-extras/src/yamlRestTest/resources/rest-api-spec/test/match_only_text/10_basic.yml
  server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/HighlightPhase.java
Labels: backport, v7.17.3

#85555 [ML] Avoid multiple queued quantiles documents in renormalizer
  docs/changelog/85555.yaml
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutodetectResultProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/Renormalizer.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/ShortCircuitingRenormalizer.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutodetectResultProcessorTests.java
Labels: >bug, :ml, Team:ML, auto-backport, v8.2.0, v7.17.3, v8.1.3, v8.3.0

#84230 SQL: Implement binary format support for SQL clear cursor
  docs/changelog/84230.yaml
  x-pack/plugin/sql/jdbc/src/test/java/org/elasticsearch/xpack/sql/jdbc/JdbcHttpClientRequestTests.java
  x-pack/plugin/sql/qa/jdbc/single-node/src/test/java/org/elasticsearch/xpack/sql/qa/jdbc/single_node/JdbcCloseCursorIT.java
  x-pack/plugin/sql/qa/jdbc/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/CloseCursorTestCase.java
  x-pack/plugin/sql/sql-action/src/main/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequest.java
  x-pack/plugin/sql/sql-action/src/test/java/org/elasticsearch/xpack/sql/action/SqlClearCursorRequestTests.java
  x-pack/plugin/sql/sql-action/src/test/java/org/elasticsearch/xpack/sql/action/SqlRequestParsersTests.java
  x-pack/plugin/sql/sql-action/src/test/java/org/elasticsearch/xpack/sql/action/TestSqlClearCursorRequest.java
  x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/HttpClient.java
  x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/Payloads.java
  x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/SqlClearCursorRequest.java
  x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/RestSqlClearCursorAction.java
Labels: >bug, :Query Languages/SQL, Team:QL, v8.3.0

#85595 Fix fields wildcard support to vector tile search API
  docs/changelog/85595.yaml
  x-pack/plugin/vector-tile/src/javaRestTest/java/org/elasticsearch/xpack/vectortile/VectorTileRestIT.java
  x-pack/plugin/vector-tile/src/main/java/org/elasticsearch/xpack/vectortile/rest/RestVectorTileAction.java
Labels: >bug, :Analytics/Geo, Team:Analytics, auto-backport-and-merge, v8.2.0, v7.17.3, v8.1.3, v8.3.0

#85611 [8.2] Update gradle wrapper to 7.4.2 (#85608)
  build-tools-internal/gradle/wrapper/gradle-wrapper.properties
  build-tools-internal/src/main/resources/minimumGradleVersion
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/StandaloneRestIntegTestTask.java
  gradle/wrapper/gradle-wrapper.properties
  plugins/examples/gradle/wrapper/gradle-wrapper.properties
Labels: backport, auto-merge, v8.2.1

#85616 mute PackageUpgradeTests.test21CheckUpgradedVersion
  qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java
Labels: :Security/Security, >test-mute, Team:Security, auto-backport-and-merge, v8.1.3, v8.3.0, v8.2.1

#85615 [7.17] Fix fields wildcard support to vector tile search API (#85595)
  docs/changelog/85595.yaml
  x-pack/plugin/vector-tile/src/javaRestTest/java/org/elasticsearch/xpack/vectortile/VectorTileRestIT.java
  x-pack/plugin/vector-tile/src/main/java/org/elasticsearch/xpack/vectortile/rest/RestVectorTileAction.java
Labels: backport, auto-merge, v7.17.3

#85606 Blacklist wildcard highlighting v7 compat test on 8.1
  modules/mapper-extras/build.gradle
Labels: >test, :Search/Search, Team:Search, v8.1.3

#85393 Warn on user roles disabled due to license reqs
  docs/changelog/85393.yaml
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/RoleDescriptorStore.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStoreTests.java
Labels: >enhancement, :Security/Authentication, Team:Security, v8.3.0

#85618 [8.2] mute PackageUpgradeTests.test21CheckUpgradedVersion (#85616)
  qa/os/src/test/java/org/elasticsearch/packaging/test/PackageUpgradeTests.java
Labels: backport, auto-merge, v8.2.1

#85497 [TEST] Add readiness Docker tests
  qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java
  qa/os/src/test/java/org/elasticsearch/packaging/util/docker/Docker.java
Labels: >test, :Core/Infra/Core, Team:Core/Infra, v8.3.0

#85599 [8.1] [ML] Avoid multiple queued quantiles documents in renormalizer (#85555)
  docs/changelog/85555.yaml
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutodetectResultProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/Renormalizer.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/ShortCircuitingRenormalizer.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutodetectResultProcessorTests.java
Labels: backport, v8.1.3

#85597 [8.2] [ML] Avoid multiple queued quantiles documents in renormalizer (#85555)
  docs/changelog/85555.yaml
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutodetectResultProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/Renormalizer.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/ShortCircuitingRenormalizer.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutodetectResultProcessorTests.java
Labels: backport, v8.2.1

#83706 Remove irrelevant nodeHotThreads comment above nodeUsage method in ClusterAdminClient
  server/src/main/java/org/elasticsearch/client/internal/ClusterAdminClient.java
Labels: >docs, :Distributed/Distributed, Team:Distributed, Team:Docs, external-contributor, auto-merge, v8.3.0

#85507 Avoiding watcher validation errors when a data stream points to more than one index
  docs/changelog/85507.yaml
  x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtils.java
  x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/execution/TriggeredWatchStoreTests.java
  x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtilsTests.java
Labels: >bug, :Data Management/Watcher, Team:Data Management, auto-backport-and-merge, v8.3.0, v8.2.1

#85620 [7.17] Update gradle wrapper to 7.4.2 (#85608)
  build-tools-internal/gradle/wrapper/gradle-wrapper.properties
  build-tools-internal/src/main/resources/minimumGradleVersion
  gradle/wrapper/gradle-wrapper.properties
  plugins/examples/gradle/wrapper/gradle-wrapper.properties
Labels: backport, v7.17.3

#85498 [TEST] Fix test failures on Windows
  build-tools-internal/src/integTest/groovy/org/elasticsearch/gradle/internal/test/rest/InternalYamlRestTestPluginFuncTest.groovy
  test/framework/src/main/java/org/elasticsearch/test/readiness/ReadinessClientProbe.java
  x-pack/plugin/shutdown/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/shutdown/NodeShutdownIT.java
Labels: :Core/Infra/Core, >test-failure, Team:Core/Infra, test-windows, auto-backport-and-merge, v8.2.0, v8.3.0, v8.2.1

#85621 Speed up JsonXContentParser token conversion and text()
  libs/x-content/impl/src/main/java/org/elasticsearch/xcontent/provider/json/JsonXContentParser.java
  libs/x-content/src/main/java/org/elasticsearch/xcontent/XContentParser.java
Labels: :Core/Infra/Core, >refactoring, Team:Core/Infra, v8.3.0

#85627 [ML] re-enable Classification|RegressionIT testStopAndRestart
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/ClassificationIT.java
  x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java
Labels: >test, :ml, Team:ML, v8.3.0

#85626 Remove lang-painless apiJavadoc task
  modules/lang-painless/build.gradle
Labels: :Core/Infra/Scripting, >refactoring, Team:Core/Infra, v8.3.0

#85631 [8.2] Avoiding watcher validation errors when a data stream points to more than one index (#85507)
  docs/changelog/85507.yaml
  x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtils.java
  x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/execution/TriggeredWatchStoreTests.java
  x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtilsTests.java
Labels: backport, auto-merge, v8.2.1

#85633 [8.2] [TEST] Fix test failures on Windows (#85498)
  build-tools-internal/src/integTest/groovy/org/elasticsearch/gradle/internal/test/rest/InternalYamlRestTestPluginFuncTest.groovy
  test/framework/src/main/java/org/elasticsearch/test/readiness/ReadinessClientProbe.java
  x-pack/plugin/shutdown/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/shutdown/NodeShutdownIT.java
Labels: backport, auto-merge, v8.2.1

#85632 Log at WARN level for Watcher cluster state validation errors
  docs/changelog/85632.yaml
  x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherService.java
Labels: >bug, :Data Management/Watcher, Team:Data Management, auto-backport-and-merge, v8.1.3, v8.3.0, v8.2.1

#85636 Extract some cold paths in StreamInput around String reading
  server/src/main/java/org/elasticsearch/common/bytes/BytesReferenceStreamInput.java
  server/src/main/java/org/elasticsearch/common/io/stream/ByteArrayStreamInput.java
  server/src/main/java/org/elasticsearch/common/io/stream/ByteBufferStreamInput.java
  server/src/main/java/org/elasticsearch/common/io/stream/StreamInput.java
Labels: >non-issue, :Core/Infra/Core, Team:Core/Infra, v8.3.0

#85598 [7.17] [ML] Avoid multiple queued quantiles documents in renormalizer (#85555)
  docs/changelog/85555.yaml
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutodetectResultProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/Renormalizer.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/ShortCircuitingRenormalizer.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutodetectResultProcessorTests.java
Labels: backport, v7.17.3

#85625 [ML] Simplify shortcircuiting scores renormalizer
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/ShortCircuitingRenormalizer.java
Labels: >non-issue, :ml, Team:ML, auto-backport, v8.2.0, v7.17.3, v8.1.3, v8.3.0

#85642 [8.2] Log at WARN level for Watcher cluster state validation errors (#85632)
  docs/changelog/85632.yaml
  x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherService.java
Labels: backport, auto-merge, v8.2.1

#85425 Ensure reindex test exception is not swallowed.
  modules/reindex/src/javaRestTest/java/org/elasticsearch/index/reindex/remote/ReindexFromOldRemoteIT.java
Labels: >test, :Distributed/Reindex, Team:Distributed, v8.3.0

#85622 Describe release highlight for ANN filtering
  docs/changelog/84734.yaml
Labels: >docs, :Search/Search, Team:Docs, Team:Search, v8.2.0, v8.3.0

#85641 [8.1] Log at WARN level for Watcher cluster state validation errors (#85632)
  docs/changelog/85632.yaml
  x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherService.java
Labels: backport, auto-merge

#85510 Fix skip caching factor with indices.queries.cache.all_segments
  docs/changelog/85510.yaml
  server/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java
Labels: >bug, :Search/Search, Team:Search, auto-backport-and-merge, v7.17.3, v8.1.3, v8.3.0, v8.2.1

#85643 [8.2] [ML] Simplify shortcircuiting scores renormalizer (#85625)
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/ShortCircuitingRenormalizer.java
Labels: backport, v8.2.1

#85644 [7.17] [ML] Simplify shortcircuiting scores renormalizer (#85625)
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/normalizer/ShortCircuitingRenormalizer.java
Labels: backport, v7.17.3

#85646 [7.17] Fix skip caching factor with indices.queries.cache.all_segments (#85510)
  docs/changelog/85510.yaml
  server/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java
Labels: backport, auto-merge, v7.17.3

#85647 [8.1] Fix skip caching factor with indices.queries.cache.all_segments (#85510)
  docs/changelog/85510.yaml
  server/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java
Labels: backport, auto-merge, v8.1.3

#85650 Fix filters agg test
  server/src/test/java/org/elasticsearch/search/aggregations/bucket/filter/FiltersAggregatorTests.java
Labels: >test, :Analytics/Aggregations, Team:Analytics, auto-merge, auto-backport-and-merge, v8.3.0, v8.2.1

#85652 [8.2] Fix filters agg test (#85650)
  server/src/test/java/org/elasticsearch/search/aggregations/bucket/filter/FiltersAggregatorTests.java
Labels: backport, auto-merge, v8.2.1

#85648 [8.2] Fix skip caching factor with indices.queries.cache.all_segments (#85510)
  docs/changelog/85510.yaml
  server/src/main/java/org/elasticsearch/indices/IndicesQueryCache.java
Labels: backport, auto-merge, v8.2.1

#85660 Speed up Strings.validFileName
  server/src/main/java/org/elasticsearch/common/Strings.java
  server/src/test/java/org/elasticsearch/repositories/RepositoriesServiceTests.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ApplicationPrivilege.java
Labels: >non-issue, :Distributed/Snapshot/Restore, :Core/Infra/Core, Team:Core/Infra, Team:Distributed, v8.3.0

#85659 Cleanup XContentParserUtils throw on method signatures
  server/src/main/java/org/elasticsearch/action/bulk/BulkItemResponse.java
  server/src/main/java/org/elasticsearch/action/bulk/BulkResponse.java
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/common/settings/Settings.java
  server/src/main/java/org/elasticsearch/common/xcontent/XContentParserUtils.java
  server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshot.java
  server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java
  server/src/main/java/org/elasticsearch/repositories/RepositoryData.java
  server/src/main/java/org/elasticsearch/search/aggregations/bucket/range/GeoDistanceAggregationBuilder.java
Labels: >non-issue, :Core/Infra/Core, Team:Core/Infra, v8.3.0

#85197 Update bulk.asciidoc
  docs/reference/docs/bulk.asciidoc
Labels: >docs, :Distributed/CRUD, Team:Docs, external-contributor, v8.1.3

#85581 Bump commons-compress to 1.21
  build-tools-internal/build.gradle
  build-tools/build.gradle
  distribution/tools/geoip-cli/build.gradle
  docs/changelog/85581.yaml
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/commons-compress-1.19.jar.sha1
  plugins/ingest-attachment/licenses/commons-compress-1.21.jar.sha1
  test/x-content/build.gradle
Labels: >bug, :Data Management/Ingest, Team:Data Management, auto-merge, auto-backport-and-merge, v8.0.2, v7.17.3, v8.1.3, v8.2.1

#85619 [8.1] Update gradle wrapper to 7.4.2 (#85608)
  build-tools-internal/gradle/wrapper/gradle-wrapper.properties
  build-tools-internal/src/main/resources/minimumGradleVersion
  gradle/wrapper/gradle-wrapper.properties
  plugins/examples/gradle/wrapper/gradle-wrapper.properties
Labels: backport, v8.1.3

#85638 Ignore frozen shared cache file during data folder upgrades
  docs/changelog/85638.yaml
  server/src/internalClusterTest/java/org/elasticsearch/env/NodeEnvironmentIT.java
  server/src/main/java/org/elasticsearch/env/NodeEnvironment.java
  x-pack/plugin/build.gradle
  x-pack/plugin/ilm/qa/multi-node/build.gradle
  x-pack/plugin/shutdown/qa/rolling-upgrade/build.gradle
  x-pack/qa/rolling-upgrade/build.gradle
  x-pack/qa/xpack-prefix-rest-compat/build.gradle
Labels: >bug, blocker, :Distributed/Snapshot/Restore, Team:Distributed, auto-backport, v8.2.0, v8.3.0

#85331 Reduce logging for cache file synchronization failures
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/full/CacheService.java
Labels: >non-issue, :Distributed/Snapshot/Restore, Team:Distributed, auto-backport-and-merge, v7.17.3, v8.1.3, v8.3.0

#85667 [7.17] Reduce logging for cache file synchronization failures (#85331)
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/full/CacheService.java
Labels: backport, auto-merge, v7.17.3

#85668 [8.1] Reduce logging for cache file synchronization failures (#85331)
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/full/CacheService.java
Labels: backport, auto-merge, v8.1.3

#85635 Report pending joins in ClusterFormationFailureHelper
  docs/changelog/85635.yaml
  server/src/main/java/org/elasticsearch/cluster/coordination/ClusterFormationFailureHelper.java
  server/src/main/java/org/elasticsearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/elasticsearch/cluster/coordination/JoinStatus.java
  server/src/test/java/org/elasticsearch/cluster/coordination/ClusterFormationFailureHelperTests.java
  server/src/test/java/org/elasticsearch/cluster/coordination/JoinHelperTests.java
Labels: >enhancement, :Distributed/Cluster Coordination, Team:Distributed, auto-merge, v8.3.0

#85578 [ML] ensure roberta tokenization options are updateable
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/NlpConfigUpdate.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/RobertaTokenizationUpdate.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/AbstractNlpConfigUpdateTestCase.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/FillMaskConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/NerConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/NlpConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PassThroughConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/TextClassificationConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/TextEmbeddingConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/ZeroShotClassificationConfigUpdateTests.java
Labels: >non-issue, :ml, Team:ML, auto-backport-and-merge, v8.2.0, v8.3.0

#85569 [ML] ensure that inference index primary shards are available before attempting to load model
  docs/changelog/85569.yaml
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/utils/ExceptionsHelper.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportCreateTrainedModelAllocationAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/allocation/TrainedModelAllocationNodeService.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/allocation/TrainedModelAllocationNodeServiceTests.java
  x-pack/qa/full-cluster-restart/src/test/java/org/elasticsearch/xpack/restart/MLModelDeploymentFullClusterRestartIT.java
Labels: >bug, :ml, Team:ML, test-full-bwc, auto-backport-and-merge, v8.3.0, v8.2.1

#85673 [8.2] [ML] ensure roberta tokenization options are updateable (#85578)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/NlpConfigUpdate.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/RobertaTokenizationUpdate.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/AbstractNlpConfigUpdateTestCase.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/FillMaskConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/NerConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/NlpConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/PassThroughConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/TextClassificationConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/TextEmbeddingConfigUpdateTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/ZeroShotClassificationConfigUpdateTests.java
Labels: backport, auto-merge, v8.2.1

#85674 [8.2] [ML] ensure that inference index primary shards are available before attempting to load model (#85569)
  docs/changelog/85569.yaml
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/utils/ExceptionsHelper.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportCreateTrainedModelAllocationAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/allocation/TrainedModelAllocationNodeService.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/allocation/TrainedModelAllocationNodeServiceTests.java
  x-pack/qa/full-cluster-restart/src/test/java/org/elasticsearch/xpack/restart/MLModelDeploymentFullClusterRestartIT.java
Labels: backport, auto-merge, v8.2.1

#85639 Remove hppc from ClusterStatsNodes
  server/src/main/java/org/elasticsearch/action/admin/cluster/stats/ClusterStatsNodes.java
Labels: :Core/Infra/Core, >refactoring, Team:Core/Infra, v8.3.0

#85678 [8.2] Bump commons-compress to 1.21 (#85581)
  build-tools-internal/build.gradle
  build-tools/build.gradle
  distribution/tools/geoip-cli/build.gradle
  docs/changelog/85581.yaml
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/commons-compress-1.19.jar.sha1
  plugins/ingest-attachment/licenses/commons-compress-1.21.jar.sha1
  test/x-content/build.gradle
Labels: backport, auto-merge, v8.2.1

#85681 [7.17] Bump commons-compress to 1.21 (#85581)
  build-tools-internal/build.gradle
  build-tools/build.gradle
  docs/changelog/85581.yaml
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/commons-compress-1.19.jar.sha1
  plugins/ingest-attachment/licenses/commons-compress-1.21.jar.sha1
  test/framework/build.gradle
Labels: backport, auto-merge, v7.17.3

#85671 Use expectThrows instead of ThrowableAssertions
  server/src/internalClusterTest/java/org/elasticsearch/snapshots/RepositoryIntegrityHealthIndicatorServiceIT.java
  server/src/test/java/org/elasticsearch/repositories/RepositoriesServiceTests.java
  test/framework/src/main/java/org/elasticsearch/test/hamcrest/ThrowableAssertions.java
Labels: >test, :Distributed/Snapshot/Restore, Team:Distributed, v8.3.0

#85628 Remove ILM docs redirect
  docs/reference/ilm/apis/put-lifecycle.asciidoc
  docs/reference/ilm/set-up-lifecycle-policy.asciidoc
Labels: >docs, :Data Management/ILM+SLM, Team:Data Management, Team:Docs, v8.2.0, v8.3.0

#85623 Fix typos in comments
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataMappingService.java
  test/framework/src/main/java/org/elasticsearch/index/engine/EngineTestCase.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/ShrinkAction.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/esnative/tool/SetupPasswordTool.java
  x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/WatcherService.java
Labels: >non-issue, :Core/Infra/Core, Team:Core/Infra, auto-merge, v8.3.0

#85661 Cleanup and slight speedup for field name parsing in snapshot metadata
  server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshot.java
  server/src/main/java/org/elasticsearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshots.java
Labels: >non-issue, :Distributed/Snapshot/Restore, Team:Distributed, v8.3.0

#85683 Wait for tasks to finish after the forcemerge yml test
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/indices.forcemerge/10_basic.yml
Labels: >test, :Data Management/ILM+SLM, Team:Data Management, Team:Clients, v8.2.0, v7.17.3, v8.3.0

#85351 Enable overrides of license expiration dates
  x-pack/plugin/core/build.gradle
  x-pack/plugin/core/src/javaRestTest/java/org/elasticsearch/xpack/core/LicenseInstallationIT.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/License.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseOverrides.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseService.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseUtils.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/StartBasicClusterTask.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/StartupSelfGeneratedLicenseTask.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/TransportXPackInfoAction.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/license/LicenseServiceTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/action/TransportXPackInfoActionTests.java
Labels: >non-issue, :Security/License, Team:Security, auto-backport-and-merge, v8.2.0, v7.17.3, v8.1.3, v8.3.0

#85686 [8.1] Enable overrides of license expiration dates (#85351)
  x-pack/plugin/core/build.gradle
  x-pack/plugin/core/src/javaRestTest/java/org/elasticsearch/xpack/core/LicenseInstallationIT.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/License.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseOverrides.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseService.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseUtils.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/StartBasicClusterTask.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/StartupSelfGeneratedLicenseTask.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/TransportXPackInfoAction.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/license/LicenseServiceTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/action/TransportXPackInfoActionTests.java
Labels: backport, auto-merge, v8.1.3

#85685 [8.2] Enable overrides of license expiration dates (#85351)
  x-pack/plugin/core/build.gradle
  x-pack/plugin/core/src/javaRestTest/java/org/elasticsearch/xpack/core/LicenseInstallationIT.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/License.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseOverrides.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseService.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseUtils.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/StartBasicClusterTask.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/StartupSelfGeneratedLicenseTask.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/TransportXPackInfoAction.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/license/LicenseServiceTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/action/TransportXPackInfoActionTests.java
Labels: backport, auto-merge, v8.2.1

#85687 [7.17] Enable overrides of license expiration dates (#85351)
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/License.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseOverrides.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseService.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseUtils.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/StartBasicClusterTask.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/license/StartupSelfGeneratedLicenseTask.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/action/TransportXPackInfoAction.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/license/LicenseServiceTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/action/TransportXPackInfoActionTests.java
  x-pack/plugin/data-streams/qa/multi-node/build.gradle
  x-pack/plugin/data-streams/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/core/LicenseInstallationIT.java
Labels: backport, auto-merge, v7.17.3

#85693 Mute test DebMetadataTests
  qa/os/src/test/java/org/elasticsearch/packaging/test/DebMetadataTests.java
Labels: :Delivery/Packaging, >test-mute, Team:Delivery, auto-merge, v8.3.0

#85699 Test mute
  x-pack/plugin/data-streams/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/core/LicenseInstallationIT.java
Labels: :Security/License, >test-mute, Team:Security, auto-merge, v7.17.3

#85694 Revert "Mute ClientYamlTestSuiteIT "Get all aliases via /_alias" and …
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/indices.get_alias/10_basic.yml
Labels: >test, :Data Management/Indices APIs, Team:Data Management, v8.3.0

#85571 Carry over release highlights from Lucene 9.1
  docs/reference/release-notes/highlights.asciidoc
Labels: >docs, :Search/Search, Team:Search, v8.2.0, v8.2.1

#85664 Update docs for v8.2.0 release
  docs/reference/migration/migrate_8_2.asciidoc
  docs/reference/release-notes.asciidoc
  docs/reference/release-notes/8.2.0.asciidoc
  docs/reference/release-notes/highlights.asciidoc
Labels: >docs, Team:Docs, v8.2.0

#85715 Mute SnapshotLifecycleServiceTests#testPolicyCRUD() test.
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotLifecycleServiceTests.java
Labels: :Data Management/ILM+SLM, >test-mute, Team:Data Management, auto-backport-and-merge, v8.2.0, v8.3.0

#85718 [8.2] Mute SnapshotLifecycleServiceTests#testPolicyCRUD() test. (#85715)
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SnapshotLifecycleServiceTests.java
Labels: backport, auto-merge, v8.2.1

#85672 [ML] Allow retrieving `boolean` fields from _source in DFA jobs
  docs/changelog/85672.yaml
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/extractor/ExtractedFields.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/extractor/ExtractedFieldsTests.java
Labels: >bug, :ml, Team:ML, auto-backport-and-merge, v7.17.3, v8.3.0, v8.2.1

#85724 [8.2] [ML] Allow retrieving `boolean` fields from _source in DFA jobs (#85672)
  docs/changelog/85672.yaml
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/extractor/ExtractedFields.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/extractor/ExtractedFieldsTests.java
Labels: backport, auto-merge, v8.2.1

#85723 [7.17] [ML] Allow retrieving `boolean` fields from _source in DFA jobs (#85672)
  docs/changelog/85672.yaml
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/extractor/ExtractedFields.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/extractor/ExtractedFieldsTests.java
Labels: backport, v7.17.3

#85735 [DOCS] Adds size param to evaluate DFA API docs
  docs/reference/ml/df-analytics/apis/evaluate-dfanalytics.asciidoc
Labels: >docs, :ml, Team:Docs, Team:ML, v8.0.2, v7.17.3, v8.1.3, v8.3.0, v8.2.1

#85736 [8.2] [DOCS] Adds size param to evaluate DFA API docs (#85735)
  docs/reference/ml/df-analytics/apis/evaluate-dfanalytics.asciidoc
Labels: backport, v8.2.1

#85739 [7.17] [DOCS] Adds size param to evaluate DFA API docs (#85735)
  docs/reference/ml/df-analytics/apis/evaluate-dfanalytics.asciidoc
Labels: backport, v7.17.3

#85738 [8.0] [DOCS] Adds size param to evaluate DFA API docs (#85735)
  docs/reference/ml/df-analytics/apis/evaluate-dfanalytics.asciidoc
Labels: backport, v8.0.2

#85737 [8.1] [DOCS] Adds size param to evaluate DFA API docs (#85735)
  docs/reference/ml/df-analytics/apis/evaluate-dfanalytics.asciidoc
Labels: backport, v8.1.3

#85752 [7.17] Relax docs about using new repos across major versions (#85740)
  docs/reference/snapshot-restore/register-repository.asciidoc
Labels: backport, auto-merge, v7.17.3

#85754 [8.2] Relax docs about using new repos across major versions (#85740)
  docs/reference/snapshot-restore/register-repository.asciidoc
Labels: backport, auto-merge, v8.2.1

#85755 Avoiding watcher validation errors when a data stream points to more than one index (#85507)
  docs/changelog/85507.yaml
  x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtils.java
  x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/execution/TriggeredWatchStoreTests.java
  x-pack/plugin/watcher/src/test/java/org/elasticsearch/xpack/watcher/watch/WatchStoreUtilsTests.java
Labels: backport, auto-merge, v8.1.3

#85726 Add indices permissions to Enterprise Search service account
  docs/changelog/85726.yaml
  x-pack/plugin/security/qa/service-account/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/service/ServiceAccountIT.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccounts.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccountsTests.java
Labels: >enhancement, :Security/Authorization, Team:Security, external-contributor, auto-backport, v8.2.0, v8.3.0

#85132 [discovery-gce] Upgrade all Google dependencies
  plugins/discovery-gce/build.gradle
  plugins/discovery-gce/licenses/failureaccess-1.0.1.jar.sha1
  plugins/discovery-gce/licenses/failureaccess-LICENSE.txt
  plugins/discovery-gce/licenses/failureaccess-NOTICE.txt
  plugins/discovery-gce/licenses/google-api-client-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-api-client-1.33.1.jar.sha1
  plugins/discovery-gce/licenses/google-api-services-compute-v1-rev160-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-api-services-compute-v1-rev20220322-1.32.1.jar.sha1
  plugins/discovery-gce/licenses/google-http-client-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-http-client-1.41.1.jar.sha1
  plugins/discovery-gce/licenses/google-http-client-gson-1.41.1.jar.sha1
  plugins/discovery-gce/licenses/google-http-client-jackson2-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-http-client-jackson2-1.41.1.jar.sha1
  plugins/discovery-gce/licenses/google-oauth-client-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-oauth-client-1.33.0.jar.sha1
  plugins/discovery-gce/licenses/grpc-context-1.27.2.jar.sha1
  plugins/discovery-gce/licenses/grpc-context-LICENSE.txt
  plugins/discovery-gce/licenses/grpc-context-NOTICE.txt
  plugins/discovery-gce/licenses/guava-31.0.1-jre.jar.sha1
  plugins/discovery-gce/licenses/guava-LICENSE.txt
  plugins/discovery-gce/licenses/guava-NOTICE.txt
  plugins/discovery-gce/licenses/jsr305-1.3.9.jar.sha1
  plugins/discovery-gce/licenses/jsr305-3.0.2.jar.sha1
  plugins/discovery-gce/licenses/opencensus-LICENSE.txt
  plugins/discovery-gce/licenses/opencensus-NOTICE.txt
  plugins/discovery-gce/licenses/opencensus-api-0.30.0.jar.sha1
  plugins/discovery-gce/licenses/opencensus-contrib-http-util-0.30.0.jar.sha1
Labels: >non-issue, :Distributed/Discovery-Plugins, Team:Distributed, v8.3.0

#85770 [8.2] Add indices permissions to Enterprise Search service account (#85726)
  docs/changelog/85726.yaml
  x-pack/plugin/security/qa/service-account/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/service/ServiceAccountIT.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccounts.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/service/ElasticServiceAccountsTests.java
Labels: backport, external-contributor, v8.2.1

#85775 Remove special rejection handling in Cold/Frozen cache services
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFile.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheService.java
Labels: >non-issue, :Distributed/Snapshot/Restore, Team:Distributed, auto-backport-and-merge, v7.17.3, v8.1.3, v8.3.0, v8.2.1

#85779 [7.17] Remove special rejection handling in Cold/Frozen cache services (#85775)
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFile.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheService.java
Labels: backport, auto-merge, v7.17.3

#85780 [8.1] Remove special rejection handling in Cold/Frozen cache services (#85775)
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFile.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheService.java
Labels: backport, auto-merge, v8.1.3

#85781 [8.2] Remove special rejection handling in Cold/Frozen cache services (#85775)
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/common/CacheFile.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/shared/FrozenCacheService.java
Labels: backport, auto-merge, v8.2.1

#85763 Remove leftover meta plugin descriptor
  x-pack/plugin/security/src/main/resources/meta-plugin-descriptor.properties
Labels: >non-issue, :Core/Infra/Plugins, Team:Core/Infra, v8.3.0

#85762 Remove pre Java 17 system jvm options
  distribution/tools/launchers/src/main/java/org/elasticsearch/tools/launchers/SystemJvmOptions.java
Labels: :Core/Infra/Core, >refactoring, Team:Core/Infra, v8.3.0

#85234 Health api drill down
  docs/changelog/85234.yaml
  rest-api-spec/src/main/resources/rest-api-spec/api/_internal.health.json
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/health/10_basic.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/health/20_component.yml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/health/30_feature.yml
  server/src/internalClusterTest/java/org/elasticsearch/health/GetHealthActionIT.java
  server/src/main/java/org/elasticsearch/cluster/coordination/InstanceHasMasterHealthIndicatorService.java
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorService.java
  server/src/main/java/org/elasticsearch/health/GetHealthAction.java
  server/src/main/java/org/elasticsearch/health/HealthComponentResult.java
  server/src/main/java/org/elasticsearch/health/HealthIndicatorResult.java
  server/src/main/java/org/elasticsearch/health/HealthIndicatorService.java
  server/src/main/java/org/elasticsearch/health/HealthService.java
  server/src/main/java/org/elasticsearch/health/RestGetHealthAction.java
  server/src/main/java/org/elasticsearch/snapshots/RepositoryIntegrityHealthIndicatorService.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java
  server/src/test/java/org/elasticsearch/health/HealthIndicatorServiceTests.java
  server/src/test/java/org/elasticsearch/health/HealthServiceTests.java
  server/src/test/java/org/elasticsearch/snapshots/RepositoryIntegrityHealthIndicatorServiceTests.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IlmHealthIndicatorService.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm/SlmHealthIndicatorService.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/IlmHealthIndicatorServiceTests.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm/SlmHealthIndicatorServiceTests.java
Labels: >feature, Team:Data Management, Team:Clients, :Data Management/Health, v8.3.0

#85766 Only check java version with custom ES_JAVA_HOME
  distribution/build.gradle
  distribution/src/bin/elasticsearch-env
  distribution/src/bin/elasticsearch-env.bat
  qa/os/src/test/java/org/elasticsearch/packaging/test/ArchiveTests.java
  qa/os/src/test/java/org/elasticsearch/packaging/test/WindowsServiceTests.java
Labels: :Delivery/Packaging, >refactoring, Team:Delivery, v8.3.0

#85764 Remove xshare shell logic
  distribution/src/bin/elasticsearch
  distribution/src/bin/elasticsearch-cli
  distribution/src/bin/elasticsearch-env
  distribution/tools/launchers/src/main/java/org/elasticsearch/tools/launchers/JvmOption.java
  x-pack/plugin/sql/src/main/bin/elasticsearch-sql-cli
Labels: :Delivery/Packaging, >refactoring, Team:Delivery, v8.3.0

#85765 Remove no-jdk deprecations
  benchmarks/src/main/resources/org/elasticsearch/benchmark/xcontent/monitor_cluster_stats.json
  distribution/build.gradle
  distribution/src/bin/elasticsearch
  distribution/src/bin/elasticsearch-env
  distribution/src/bin/elasticsearch-env.bat
  distribution/src/bin/elasticsearch-service.bat
  distribution/src/bin/elasticsearch.bat
  docs/reference/cluster/stats.asciidoc
  server/src/main/java/org/elasticsearch/action/admin/cluster/stats/ClusterStatsNodes.java
  server/src/main/java/org/elasticsearch/monitor/jvm/JvmInfo.java
  server/src/main/java/org/elasticsearch/node/Node.java
  test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java
  x-pack/plugin/monitoring/src/test/java/org/elasticsearch/xpack/monitoring/collector/cluster/ClusterStatsMonitoringDocTests.java
Labels: :Delivery/Packaging, :Core/Infra/Core, >refactoring, Team:Core/Infra, Team:Delivery, v8.3.0

#85794 Remove remaining references to legacy role settings
  distribution/tools/launchers/src/main/java/org/elasticsearch/tools/launchers/MachineDependentHeap.java
  distribution/tools/launchers/src/test/java/org/elasticsearch/tools/launchers/NodeRoleParserTests.java
Labels: :Core/Infra/Core, >refactoring, Team:Core/Infra, v8.3.0

#85796 Remove flavor from build
  client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java
  distribution/build.gradle
  distribution/src/bin/elasticsearch
  distribution/src/bin/elasticsearch-cli
  distribution/src/bin/elasticsearch-cli.bat
  distribution/src/bin/elasticsearch-env
  distribution/src/bin/elasticsearch-env.bat
  distribution/src/bin/elasticsearch-service.bat
  distribution/src/bin/elasticsearch.bat
  distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/InstallPluginAction.java
  distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallLicensedPluginTests.java
  distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java
  docs/Versions.asciidoc
  docs/plugins/discovery-azure-classic.asciidoc
  docs/reference/cluster/nodes-info.asciidoc
  docs/reference/cluster/stats.asciidoc
  docs/reference/setup/install/check-running.asciidoc
  server/src/main/java/org/elasticsearch/Build.java
  server/src/main/java/org/elasticsearch/Version.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/node/info/NodesInfoResponse.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/stats/ClusterStatsNodes.java
  server/src/main/java/org/elasticsearch/action/main/MainResponse.java
  server/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java
  server/src/test/java/org/elasticsearch/BuildTests.java
  server/src/test/java/org/elasticsearch/action/main/MainResponseTests.java
  server/src/test/java/org/elasticsearch/bootstrap/ElasticsearchCliTests.java
  x-pack/plugin/monitoring/src/test/java/org/elasticsearch/xpack/monitoring/collector/cluster/ClusterStatsMonitoringDocTests.java
  x-pack/plugin/sql/jdbc/src/test/java/org/elasticsearch/xpack/sql/jdbc/WebServerTestCase.java
  x-pack/plugin/sql/src/main/bin/elasticsearch-sql-cli.bat
Labels: :Delivery/Packaging, :Core/Infra/Core, >refactoring, Team:Core/Infra, Team:Delivery, v8.3.0

#85653 [Test] Use thread-safe hashSet for result collection
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileDomainIntegTests.java
Labels: >test, :Security/Security, Team:Security, auto-backport-and-merge, v8.2.0, v8.3.0

#85515 [TEST] Remove token methods from HLRC SecurityClient
  client/rest-high-level/src/main/java/org/elasticsearch/client/SecurityClient.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/SecurityRequestConverters.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/security/CreateTokenRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/security/CreateTokenResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/security/InvalidateTokenRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/security/InvalidateTokenResponse.java
  x-pack/plugin/security/qa/security-trial/src/javaRestTest/java/org/elasticsearch/xpack/security/SecurityOnTrialLicenseRestTestCase.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authc/TokenAuthIntegTests.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/authc/pki/PkiAuthDelegationIntegTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/test/TestSecurityClient.java
Labels: >test, :Clients/Java High Level REST Client, :Security/Security, Team:Security, Team:Clients, auto-merge, v8.3.0

#85771 Update v8.2.0 BC2 docs
  docs/reference/release-notes/8.2.0.asciidoc
  docs/reference/release-notes/highlights.asciidoc
Labels: >docs, Team:Docs, v8.2.0

#85719 Add a highlighter unit test base class
  server/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/CustomUnifiedHighlighterTests.java
  test/framework/src/main/java/org/elasticsearch/search/fetch/HighlighterTestCase.java
Labels: >test, :Search/Highlighting, Team:Search, v8.3.0

#85778 Unmute Lintian packaging test
  qa/os/src/test/java/org/elasticsearch/packaging/test/DebMetadataTests.java
Labels: >test, :Delivery/Packaging, Team:Delivery, v8.3.0

#85807 Mute XPackRestIT deprecation/10_basic/Test Deprecations
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/deprecation/10_basic.yml
Labels: :Data Management/Other, >test-mute, Team:Data Management, auto-backport-and-merge, v8.1.3, v8.3.0, v8.2.1

#85810 AwaitsFix for #85760
  server/src/test/java/org/elasticsearch/action/admin/indices/diskusage/TransportAnalyzeIndexDiskUsageActionTests.java
Labels: :Search/Search, >test-mute, Team:Search, auto-backport-and-merge, v7.17.3, v8.1.3, v8.2.1

#85805 [8.2] [Transform] Include missing privileges in the error message (#85547)
  x-pack/plugin/transform/qa/multi-cluster-tests-with-security/src/test/resources/rest-api-spec/test/multi_cluster/80_transform.yml
  x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformPrivilegeChecker.java
  x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/action/TransformPrivilegeCheckerTests.java
Labels: >enhancement, backport, :ml/Transform, Team:ML, v8.2.1

#85808 [8.1] Mute XPackRestIT deprecation/10_basic/Test Deprecations (#85807)
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/deprecation/10_basic.yml
Labels: backport, auto-merge, v8.1.3

#85809 [8.2] Mute XPackRestIT deprecation/10_basic/Test Deprecations (#85807)
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/deprecation/10_basic.yml
Labels: backport, auto-merge, v8.2.1

#85812 [8.1] AwaitsFix for #85760 (#85810)
  server/src/test/java/org/elasticsearch/action/admin/indices/diskusage/TransportAnalyzeIndexDiskUsageActionTests.java
Labels: backport, auto-merge, v8.1.3

#85813 Mute MigrationIT.testGetDeprecationInfo
  client/rest-high-level/src/test/java/org/elasticsearch/client/MigrationIT.java
Labels: :Core/Infra/Core, >test-mute, Team:Core/Infra, auto-backport-and-merge, v7.17.3, v8.1.3

#85814 [7.17] Mute MigrationIT.testGetDeprecationInfo (#85813)
  client/rest-high-level/src/test/java/org/elasticsearch/client/MigrationIT.java
Labels: backport, auto-merge, v7.17.3

#84250 Iteratively execute synchronous ingest processors
  docs/changelog/84250.yaml
  modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/ForEachProcessor.java
  modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/ForEachProcessorTests.java
  server/src/internalClusterTest/java/org/elasticsearch/action/ingest/AsyncIngestProcessorIT.java
  server/src/internalClusterTest/java/org/elasticsearch/index/FinalPipelineIT.java
  server/src/main/java/org/elasticsearch/ingest/CompoundProcessor.java
  server/src/main/java/org/elasticsearch/ingest/ConditionalProcessor.java
  server/src/main/java/org/elasticsearch/ingest/PipelineProcessor.java
  server/src/main/java/org/elasticsearch/ingest/Processor.java
  server/src/main/java/org/elasticsearch/ingest/TrackingResultProcessor.java
  server/src/main/java/org/elasticsearch/ingest/WrappingProcessor.java
  server/src/test/java/org/elasticsearch/action/ingest/SimulateExecutionServiceTests.java
  server/src/test/java/org/elasticsearch/ingest/CompoundProcessorTests.java
  server/src/test/java/org/elasticsearch/ingest/ConditionalProcessorTests.java
  server/src/test/java/org/elasticsearch/ingest/IngestServiceTests.java
  test/framework/src/main/java/org/elasticsearch/ingest/TestProcessor.java
  x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/AbstractEnrichProcessor.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/ingest/InferenceProcessor.java
Labels: >enhancement, :Data Management/Ingest, Team:Data Management, v8.3.0

#85822 Remove ILM classes from HLRC
  client/rest-high-level/src/main/java/org/elasticsearch/client/IndexLifecycleRequestConverters.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/AllocateAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/DeleteAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/DeleteLifecyclePolicyRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/ExplainLifecycleRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/ExplainLifecycleResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/ForceMergeAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/FreezeAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/GetLifecyclePolicyRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/GetLifecyclePolicyResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/IndexLifecycleExplainResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/IndexLifecycleNamedXContentProvider.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/LifecycleAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/LifecycleManagementStatusRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/LifecycleManagementStatusResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/LifecyclePolicy.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/LifecyclePolicyMetadata.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/MigrateAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/OperationMode.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/Phase.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/PhaseExecutionInfo.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/PutLifecyclePolicyRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/ReadOnlyAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/RemoveIndexLifecyclePolicyRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/RemoveIndexLifecyclePolicyResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/RetryLifecyclePolicyRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/RolloverAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/SearchableSnapshotAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/SetPriorityAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/ShrinkAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/StartILMRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/StopILMRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/UnfollowAction.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/ilm/WaitForSnapshotAction.java
  client/rest-high-level/src/main/resources/META-INF/services/org.elasticsearch.plugins.spi.NamedXContentProvider
  x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java
Labels: >non-issue, :Clients/Java High Level REST Client, Team:Clients, v8.3.0

#85825 Remove SLM classes from HLRC
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/DeleteSnapshotLifecyclePolicyRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/ExecuteSnapshotLifecyclePolicyRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/ExecuteSnapshotLifecyclePolicyResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/ExecuteSnapshotLifecycleRetentionRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/GetSnapshotLifecyclePolicyRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/GetSnapshotLifecyclePolicyResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/GetSnapshotLifecycleStatsRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/GetSnapshotLifecycleStatsResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/PutSnapshotLifecyclePolicyRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/SnapshotInvocationRecord.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/SnapshotLifecycleManagementStatusRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/SnapshotLifecyclePolicy.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/SnapshotLifecyclePolicyMetadata.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/SnapshotLifecycleStats.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/SnapshotRetentionConfiguration.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/StartSLMRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/slm/StopSLMRequest.java
  x-pack/plugin/ilm/qa/with-security/src/javaRestTest/java/org/elasticsearch/xpack/security/PermissionsIT.java
Labels: >non-issue, :Clients/Java High Level REST Client, Team:Clients, v8.3.0

#85785 Expose proxy settings for GCS repositories
  docs/changelog/85785.yaml
  modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStoragePlugin.java
  modules/repository-gcs/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStoragePluginTests.java
Labels: >bug, :Distributed/Snapshot/Restore, Team:Distributed, auto-backport, v8.0.2, v8.1.3, v8.3.0, v8.2.1

#85761 Remove legacy versioned logic for DefaultSystemMemoryInfo
  distribution/tools/launchers/src/main/java/org/elasticsearch/tools/launchers/DefaultSystemMemoryInfo.java
  distribution/tools/launchers/src/main/java/org/elasticsearch/tools/launchers/MachineDependentHeap.java
  distribution/tools/launchers/src/main/java/org/elasticsearch/tools/launchers/OverridableSystemMemoryInfo.java
  distribution/tools/launchers/src/main/java/org/elasticsearch/tools/launchers/SystemMemoryInfo.java
  distribution/tools/launchers/src/test/java/org/elasticsearch/tools/launchers/MachineDependentHeapTests.java
  distribution/tools/launchers/src/test/java/org/elasticsearch/tools/launchers/OverridableSystemMemoryInfoTests.java
Labels: :Delivery/Packaging, :Core/Infra/Core, >refactoring, Team:Core/Infra, Team:Delivery, v8.3.0

#85836 Revert "[8.0] Expose proxy settings for GCS repositories (#85785)"
  docs/changelog/85785.yaml
  modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStoragePlugin.java
  modules/repository-gcs/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStoragePluginTests.java
Labels: backport, v8.0.2

#85832 [8.1] Expose proxy settings for GCS repositories (#85785)
  docs/changelog/85785.yaml
  modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStoragePlugin.java
  modules/repository-gcs/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStoragePluginTests.java
Labels: backport, v8.1.3

#85833 [8.2] Expose proxy settings for GCS repositories (#85785)
  docs/changelog/85785.yaml
  modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStoragePlugin.java
  modules/repository-gcs/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStoragePluginTests.java
Labels: backport, v8.2.1

#85795 Remove uses of Charset name parsing
  build-tools/src/main/java/org/elasticsearch/gradle/LoggedExec.java
  modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/URLDecodeProcessor.java
  modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/URLDecodeProcessorTests.java
  modules/reindex/src/main/java/org/elasticsearch/reindex/remote/RemoteRequestBuilders.java
  plugins/mapper-annotated-text/src/main/java/org/elasticsearch/index/mapper/annotatedtext/AnnotatedPassageFormatter.java
  server/src/main/java/org/elasticsearch/action/DocWriteResponse.java
  server/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java
  server/src/test/java/org/elasticsearch/action/index/IndexRequestTests.java
  server/src/test/java/org/elasticsearch/common/hashing/MurmurHash3Tests.java
  server/src/test/java/org/elasticsearch/index/query/WrapperQueryBuilderTests.java
  test/framework/src/main/java/org/elasticsearch/cli/MockTerminal.java
  test/framework/src/main/java/org/elasticsearch/snapshots/mockstore/MockRepository.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/HttpResponse.java
  x-pack/plugin/identity-provider/src/internalClusterTest/java/org/elasticsearch/xpack/idp/action/SamlIdentityProviderTests.java
  x-pack/plugin/identity-provider/src/main/java/org/elasticsearch/xpack/idp/saml/authn/SamlAuthnRequestValidator.java
  x-pack/plugin/identity-provider/src/test/java/org/elasticsearch/xpack/idp/saml/authn/SamlAuthnRequestValidatorTests.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/oidc/OpenIdConnectAuthenticator.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirect.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlLogoutRequestHandlerTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java
  x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/http/HttpClient.java
  x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/http/HttpRequest.java
Labels: :Core/Infra/Core, >refactoring, Team:Core/Infra, v8.3.0

#85834 Remove Migration classes from HLRC
  client/rest-high-level/src/main/java/org/elasticsearch/client/MigrationClient.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/MigrationRequestConverters.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/migration/DeprecationInfoRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/migration/DeprecationInfoResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/migration/GetFeatureUpgradeStatusRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/migration/GetFeatureUpgradeStatusResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/migration/PostFeatureUpgradeRequest.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/migration/PostFeatureUpgradeResponse.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/migration/package-info.java
Labels: >non-issue, :Clients/Java High Level REST Client, Team:Clients, v8.3.0

#85835 Remove Task classes from HLRC
  client/rest-high-level/src/main/java/org/elasticsearch/client/RequestConverters.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/tasks/TaskId.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/tasks/TaskSubmissionResponse.java
Labels: >non-issue, :Clients/Java High Level REST Client, Team:Clients, v8.3.0

#85838 Use urgent priority for node shutdown cluster state update
  x-pack/plugin/shutdown/src/main/java/org/elasticsearch/xpack/shutdown/TransportDeleteShutdownNodeAction.java
  x-pack/plugin/shutdown/src/main/java/org/elasticsearch/xpack/shutdown/TransportPutShutdownNodeAction.java
Labels: >refactoring, Team:Core/Infra, :Core/Infra/Node Lifecycle, v8.3.0

#85827 Fix BuildTests serialization
  server/src/test/java/org/elasticsearch/BuildTests.java
Labels: >test, :Core/Infra/Core, Team:Core/Infra, v8.3.0

#85842 Remove hppc from cat allocation api
  server/src/main/java/org/elasticsearch/rest/action/cat/RestAllocationAction.java
Labels: :Data Management/CAT APIs, >refactoring, Team:Data Management, v8.3.0

#85828 Fix TranslogTests#testStats
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
Labels: >test, :Distributed/Engine, Team:Distributed, auto-backport-and-merge, v7.17.3, v8.3.0, v8.2.1

#85830 Add support for impact_areas to health impacts
  docs/changelog/85830.yaml
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorService.java
  server/src/main/java/org/elasticsearch/health/HealthIndicatorImpact.java
  server/src/main/java/org/elasticsearch/health/ImpactArea.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java
  server/src/test/java/org/elasticsearch/health/HealthIndicatorResultTests.java
  server/src/test/java/org/elasticsearch/health/HealthIndicatorServiceTests.java
Labels: >feature, Team:Data Management, :Data Management/Health, v8.3.0

#68649 Prevent ThreadContext header leak when sending response
  docs/changelog/68649.yaml
  modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequestHandler.java
  modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
  modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
  modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4WriteThrottlingHandler.java
  server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java
  server/src/main/java/org/elasticsearch/http/DefaultRestChannel.java
Labels: >bug, :Core/Infra/Core, Team:Core/Infra, auto-backport, v8.2.0, v7.17.3, v8.3.0

#85858 [8.2] Reduce port range re-use in tests (#85777)
  test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java
  test/framework/src/test/java/org/elasticsearch/test/test/ESTestCaseTests.java
Labels: backport, auto-merge, v8.2.1

#85859 [8.1] Reduce port range re-use in tests (#85777)
  test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java
  test/framework/src/test/java/org/elasticsearch/test/test/ESTestCaseTests.java
Labels: backport, auto-merge, v8.1.4

#85857 [8.2] Fix TranslogTests#testStats (#85828)
  server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java
Labels: backport, auto-merge, v8.2.1

#85817 [discovery-gce] Fix initialisation of transport in FIPS mode
  docs/changelog/85817.yaml
  plugins/discovery-gce/src/main/java/org/elasticsearch/cloud/gce/GceInstancesServiceImpl.java
Labels: >bug, :Distributed/Discovery-Plugins, Team:Distributed, v8.3.0

#83884 Upgrade Azure SDK
  modules/repository-azure/azure-storage-blob/build.gradle
  modules/repository-azure/build.gradle
  modules/repository-azure/licenses/azure-core-1.10.0.jar.sha1
  modules/repository-azure/licenses/azure-core-1.25.0.jar.sha1
  modules/repository-azure/licenses/azure-core-http-netty-1.11.7.jar.sha1
  modules/repository-azure/licenses/azure-core-http-netty-1.6.3.jar.sha1
  modules/repository-azure/licenses/azure-storage-blob-12.14.4.jar.sha1
  modules/repository-azure/licenses/azure-storage-common-12.14.3.jar.sha1
  modules/repository-azure/licenses/azure-storage-common-12.9.0.jar.sha1
  modules/repository-azure/licenses/jackson-annotations-2.10.4.jar.sha1
  modules/repository-azure/licenses/jackson-annotations-2.13.2.jar.sha1
  modules/repository-azure/licenses/jackson-core-2.10.4.jar.sha1
  modules/repository-azure/licenses/jackson-core-2.13.2.jar.sha1
  modules/repository-azure/licenses/jackson-databind-2.10.4.jar.sha1
  modules/repository-azure/licenses/jackson-databind-2.13.2.2.jar.sha1
  modules/repository-azure/licenses/jackson-dataformat-xml-2.10.4.jar.sha1
  modules/repository-azure/licenses/jackson-dataformat-xml-2.13.2.jar.sha1
  modules/repository-azure/licenses/jackson-datatype-jsr310-2.10.4.jar.sha1
  modules/repository-azure/licenses/jackson-datatype-jsr310-2.13.2.jar.sha1
  modules/repository-azure/licenses/jackson-module-jaxb-annotations-2.10.4.jar.sha1
  modules/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.2.jar.sha1
  modules/repository-azure/licenses/netty-codec-dns-4.1.74.Final.jar.sha1
  modules/repository-azure/licenses/netty-resolver-dns-4.1.74.Final.jar.sha1
  modules/repository-azure/licenses/netty-transport-native-unix-common-4.1.74.Final.jar.sha1
  modules/repository-azure/licenses/reactor-core-3.3.10.RELEASE.jar.sha1
  modules/repository-azure/licenses/reactor-core-3.4.13.jar.sha1
  modules/repository-azure/licenses/reactor-netty-0.9.12.RELEASE.jar.sha1
  modules/repository-azure/licenses/reactor-netty-core-1.0.14.jar.sha1
  modules/repository-azure/licenses/reactor-netty-http-1.0.14.jar.sha1
  modules/repository-azure/licenses/stax2-api-4.2.1.jar.sha1
  modules/repository-azure/licenses/stax2-api-4.2.jar.sha1
  modules/repository-azure/licenses/woodstox-core-6.0.2.jar.sha1
  modules/repository-azure/licenses/woodstox-core-6.2.7.jar.sha1
  modules/repository-azure/src/internalClusterTest/java/org/elasticsearch/repositories/azure/AzureBlobStoreRepositoryTests.java
  modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java
Labels: >non-issue, :Distributed/Snapshot/Restore, Team:Distributed, v8.3.0

#85865 Prevent ThreadContext header leak when sending response backport(#68649)
  docs/changelog/68649.yaml
  modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequestHandler.java
  server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java
  server/src/main/java/org/elasticsearch/http/DefaultRestChannel.java
Labels: :Core/Infra/Core, backport, Team:Core/Infra, v7.17.3

#85860 [8.2] Prevent ThreadContext header leak when sending response (#68649)
  docs/changelog/68649.yaml
  modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequestHandler.java
  modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java
  modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4Transport.java
  modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/Netty4WriteThrottlingHandler.java
  server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java
  server/src/main/java/org/elasticsearch/http/DefaultRestChannel.java
Labels: backport, v8.2.1

#85866 Fix Intellij integration
  build-tools-internal/src/main/groovy/elasticsearch.ide.gradle
Labels: >non-issue, :Delivery/Build, Team:Delivery, v8.3.0

#84227 Enforce external id uniqueness during DesiredNode construction
  docs/changelog/84227.yaml
  rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/cluster.desired_nodes/10_basic.yml
  server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/desirednodes/TransportDesiredNodesActionsIT.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/desirednodes/TransportGetDesiredNodesAction.java
  server/src/main/java/org/elasticsearch/action/admin/cluster/desirednodes/TransportUpdateDesiredNodesAction.java
  server/src/main/java/org/elasticsearch/cluster/desirednodes/DesiredNodesSettingsValidator.java
  server/src/main/java/org/elasticsearch/cluster/metadata/DesiredNode.java
  server/src/main/java/org/elasticsearch/cluster/metadata/DesiredNodes.java
  server/src/main/java/org/elasticsearch/cluster/metadata/DesiredNodesMetadata.java
  server/src/test/java/org/elasticsearch/action/admin/cluster/desirednodes/TransportUpdateDesiredNodesActionTests.java
  server/src/test/java/org/elasticsearch/cluster/desirednodes/DesiredNodesSettingsValidatorTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/DesiredNodeTests.java
  server/src/test/java/org/elasticsearch/cluster/metadata/DesiredNodesTestCase.java
Labels: >bug, :Distributed/Distributed, Team:Distributed, v8.3.0

#85713 TSDB: fix wrong initial value of tsidOrd in TimeSeriesIndexSearcher
  docs/changelog/85713.yaml
  server/src/main/java/org/elasticsearch/search/aggregations/timeseries/TimeSeriesIndexSearcher.java
  server/src/test/java/org/elasticsearch/search/aggregations/timeseries/TimeSeriesIndexSearcherTests.java
Labels: >bug, Team:Analytics, external-contributor, :Analytics/TSDB, v8.3.0

#85863 [ML] Fix serialisation of text embedding updates
  docs/changelog/85863.yaml
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/MlInferenceNamedXContentProvider.java
Labels: >bug, :ml, Team:ML, auto-backport-and-merge, v8.2.0, v8.3.0, v8.1.4
