Repository elastic/elasticsearch, pull requests merged in 2022-01, with the labels that each got.

#82168 More Efficient Simple String List Setting
  server/src/main/java/org/elasticsearch/common/settings/Setting.java
  server/src/main/java/org/elasticsearch/index/IndexSettings.java
Labels: >non-issue, :Core/Infra/Settings, v8.0.0, Team:Core/Infra, auto-backport-and-merge, v8.1.0

#82103 Fix Noisy Warnings in SecurityIntegTestCase
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/profile/ProfileSingleNodeTests.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/test/SecurityIntegTestCase.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/test/SecuritySettingsSource.java
Labels: >test, :Security/Security, v8.0.0, Team:Security, auto-backport-and-merge, v8.1.0

#82179 Fix docs and error message for role field_security
  x-pack/docs/en/rest-api/security/create-roles.asciidoc
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleDescriptor.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/RoleDescriptorTests.java
Labels: backport, auto-merge, auto-backport-and-merge, v7.17.0, v7.16.3

#82180 Fix docs and error message for role field_security
  x-pack/docs/en/rest-api/security/create-roles.asciidoc
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleDescriptor.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/RoleDescriptorTests.java
Labels: backport, auto-merge, v7.16.3

#82166 SQL: Remove JDBC dependency on ES lib geo
  docs/reference/migration/migrate_8_0.asciidoc
  docs/reference/migration/migrate_8_0/sql-jdbc-changes.asciidoc
  x-pack/plugin/sql/jdbc/build.gradle
  x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/TypeConverter.java
  x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/geo/GeoSqlSpecTestCase.java
  x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/JdbcAssert.java
Labels: >breaking, >refactoring, :Query Languages/SQL, v8.0.0, Team:QL, auto-backport-and-merge, v8.1.0

#82181 [8.0] SQL: Remove JDBC dependency on ES lib geo (#82166)
  docs/reference/migration/migrate_8_0.asciidoc
  docs/reference/migration/migrate_8_0/sql-jdbc-changes.asciidoc
  x-pack/plugin/sql/jdbc/build.gradle
  x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/TypeConverter.java
  x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/geo/GeoSqlSpecTestCase.java
  x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/jdbc/JdbcAssert.java
Labels: backport, v8.0.0, auto-merge

#78875 Paginate persisted cluster state
  server/src/main/java/org/elasticsearch/cluster/coordination/ElasticsearchNodeCommand.java
  server/src/main/java/org/elasticsearch/common/bytes/RecyclingBytesStreamOutput.java
  server/src/main/java/org/elasticsearch/common/settings/ClusterSettings.java
  server/src/main/java/org/elasticsearch/gateway/PersistedClusterStateService.java
  server/src/main/java/org/elasticsearch/node/Node.java
  server/src/test/java/org/elasticsearch/common/bytes/RecyclingBytesStreamOutputTests.java
  server/src/test/java/org/elasticsearch/env/NodeRepurposeCommandTests.java
  server/src/test/java/org/elasticsearch/env/OverrideNodeVersionCommandTests.java
  server/src/test/java/org/elasticsearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/elasticsearch/gateway/PersistedClusterStateServiceTests.java
  server/src/test/java/org/elasticsearch/index/shard/RemoveCorruptedShardDataCommandTests.java
  test/framework/src/main/java/org/elasticsearch/cluster/coordination/AbstractCoordinatorTestCase.java
  test/framework/src/main/java/org/elasticsearch/gateway/MockGatewayMetaState.java
  test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java
Labels: >enhancement, :Distributed/Cluster Coordination, Team:Distributed, auto-merge, v8.1.0

#82187 Simplify MappingMetadata Field in IndexMetadata
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
Labels: >non-issue, :Search/Mapping, v8.0.0, Team:Search, auto-backport-and-merge, v8.1.0

#81944 ILM: fix allocate action to allow only total_shards_per_node
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/AllocateAction.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/AllocateActionTests.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingService.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingServiceTests.java
Labels: >bug, :Data Management/ILM+SLM, v8.0.0, Team:Data Management, v8.1.0, v7.17.0, v7.16.3

#82188 [8.0] stack monitoring: update logstash mappings (#82152)
  x-pack/plugin/core/src/main/resources/monitoring-logstash-mb.json
Labels: backport, v8.0.0, external-contributor, auto-merge

#82189 [8.0] Simplify MappingMetadata Field in IndexMetadata (#82187)
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
Labels: backport, v8.0.0, auto-merge

#82191 [8.0] ILM: fix allocate action to allow only total_shards_per_node (#81944)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/AllocateAction.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/AllocateActionTests.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingService.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingServiceTests.java
Labels: backport, v8.0.0, auto-merge

#81873 [7.17] Add delete privilege to kibana_system for APM and Endpoint ILM policies (#81811)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStore.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java
Labels: backport, external-contributor, auto-merge, v7.17.0

#81972 [Transform] Report _preview warning in the face of pipeline failure.
  x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformPivotRestIT.java
  x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportPreviewTransformAction.java
Labels: >bug, v8.0.0, :ml/Transform, Team:ML, v7.16.0, auto-backport-and-merge, v8.1.0

#81127 [DOCS] Note that `default_field` supports wildcards
  docs/reference/index-modules.asciidoc
  docs/reference/query-dsl/query-string-query.asciidoc
Labels: >docs, :Search/Search, Team:Docs, Team:Search, v8.1.0, v8.0.0-beta1, v7.17.0, v7.16.3

#82200 [7.16] [DOCS] Note that `default_field` support wildcards (#81127)
  docs/reference/index-modules.asciidoc
  docs/reference/query-dsl/query-string-query.asciidoc
Labels: backport, auto-merge, v7.16.3

#82198 [8.0] [DOCS] Note that `default_field` support wildcards (#81127)
  docs/reference/index-modules.asciidoc
  docs/reference/query-dsl/query-string-query.asciidoc
Labels: backport, v8.0.0, auto-merge

#82197 [8.0] [Transform] Report _preview warning in the face of pipeline failure. (#81972)
  x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformPivotRestIT.java
  x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportPreviewTransformAction.java
Labels: backport, v8.0.0, auto-merge

#81989 Fix version resolution and encoding in LLRC
  client/rest/build.gradle
  client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java
  client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostIntegTests.java
Labels: >bug, :Data Management/Java Low Level REST Client, v8.0.0, Team:Data Management, external-contributor, auto-backport-and-merge, v8.1.0, v7.17.0

#82204 [8.0] Fix version resolution and encoding in LLRC (#81989)
  client/rest/build.gradle
  client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java
  client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostIntegTests.java
Labels: backport, v8.0.0, external-contributor, auto-merge

#82205 [7.17] Fix version resolution and encoding in LLRC (#81989)
  client/rest/build.gradle
  client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java
  client/rest/src/test/java/org/elasticsearch/client/RestClientSingleHostIntegTests.java
Labels: backport, external-contributor, auto-merge, v7.17.0

#82135 Fix Watcher test 'testVars'
  x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/ExecutionVarsIntegrationTests.java
Labels: >test, :Data Management/Watcher, Team:Data Management, v8.1.0

#82192 [7.17] ILM: fix allocate action to allow only total_shards_per_node (#81944)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/AllocateAction.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/AllocateActionTests.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingService.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingServiceTests.java
Labels: backport, auto-merge, v7.17.0

#82123 [docs] clarify purged http stats
  docs/reference/cluster/nodes-stats.asciidoc
Labels: >docs, v8.0.0, Team:Docs, v7.16.0, auto-backport-and-merge, v8.1.0, v7.17.0

#82211 [7.17] [docs] clarify purged http stats (#82123)
  docs/reference/cluster/nodes-stats.asciidoc
Labels: backport, auto-merge, v7.17.0

#82210 [7.16] [docs] clarify purged http stats (#82123)
  docs/reference/cluster/nodes-stats.asciidoc
Labels: backport, auto-merge, v7.16.3

#82209 [8.0] [docs] clarify purged http stats (#82123)
  docs/reference/cluster/nodes-stats.asciidoc
Labels: backport, v8.0.0, auto-merge

#82118 Re-enable SingleNodeTests.testThatLoadingWithNonExistingIndexWorks
  x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/SingleNodeTests.java
Labels: >test, :Data Management/Watcher, v8.0.0, Team:Data Management, auto-backport-and-merge, v8.1.0, v7.16.3

#82203 Don't Parse Monitoring Templates on Every CS Update
  x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/MonitoringTemplateRegistry.java
Labels: >non-issue, backport pending, :Data Management/Monitoring, v8.0.0, Team:Data Management, v8.1.0

#81617 Add support for GeoShape to the scripting fields API
  docs/changelog/81617.yaml
  x-pack/plugin/spatial/build.gradle
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/SpatialPainlessExtension.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/fielddata/plain/AbstractAtomicGeoShapeShapeFieldData.java
  x-pack/plugin/spatial/src/main/java/org/elasticsearch/xpack/spatial/index/mapper/GeoShapeWithDocValuesFieldMapper.java
  x-pack/plugin/spatial/src/main/resources/META-INF/services/org.elasticsearch.painless.spi.PainlessExtension
  x-pack/plugin/spatial/src/main/resources/org/elasticsearch/xpack/spatial/org.elasticsearch.xpack.spatial.index.fielddata.plain.txt
  x-pack/plugin/spatial/src/main/resources/org/elasticsearch/xpack/spatial/org.elasticsearch.xpack.spatial.index.fielddata.txt
  x-pack/plugin/spatial/src/main/resources/org/elasticsearch/xpack/spatial/org.elasticsearch.xpack.spatial.index.mapper.txt
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/spatial/70_script_doc_values.yml
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra, v8.1.0

#82214 [8.0] Re-enable SingleNodeTests.testThatLoadingWithNonExistingIndexWorks (#82118)
  x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/SingleNodeTests.java
Labels: backport, v8.0.0, auto-merge

#82215 [7.16] Re-enable SingleNodeTests.testThatLoadingWithNonExistingIndexWorks (#82118)
  x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/SingleNodeTests.java
Labels: backport, auto-merge, v7.16.3

#82013 [DOC] ILM Searchable Snapshot action hot/cold
  docs/reference/ilm/actions/ilm-searchable-snapshot.asciidoc
Labels: >docs, v8.0.0, Team:Docs, external-contributor, v8.1.0, v7.16.3

#82220 [7.16] [DOC] Don't include searchable snapshot ILM action in both hot and cold phases (#82013)
  docs/reference/ilm/actions/ilm-searchable-snapshot.asciidoc
Labels: backport, auto-merge, v7.16.3

#82219 [7.17] [DOC] Don't include searchable snapshot ILM action in both hot and cold phases (#82013)
  docs/reference/ilm/actions/ilm-searchable-snapshot.asciidoc
Labels: backport, auto-merge, v7.17.0

#82218 [8.0] [DOC] Don't include searchable snapshot ILM action in both hot and cold phases (#82013)
  docs/reference/ilm/actions/ilm-searchable-snapshot.asciidoc
Labels: backport, v8.0.0, auto-merge

#82154 Ignore errors syncing ephemeral files in test clusters
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
Labels: >non-issue, :Delivery/Build, v8.0.0, Team:Delivery, auto-backport-and-merge, v8.1.0, v7.17.0, v7.16.3

#82223 [7.16] Ignore errors syncing ephemeral files in test clusters (#82154)
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
Labels: backport, auto-merge, v7.16.3

#82221 [8.0] Ignore errors syncing ephemeral files in test clusters (#82154)
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
Labels: backport, v8.0.0, auto-merge

#82222 [7.17] Ignore errors syncing ephemeral files in test clusters (#82154)
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
Labels: backport, auto-merge, v7.17.0

#82136 Fix Watcher testWatcherWithApiKey
  x-pack/qa/full-cluster-restart/src/test/java/org/elasticsearch/xpack/restart/FullClusterRestartIT.java
Labels: >test, :Data Management/Watcher, v8.0.0, Team:Data Management, v8.1.0, v7.17.0, v7.16.3

#82228 Script: track this pointer capture from blocks within lambdas
  docs/changelog/82228.yaml
  modules/lang-painless/src/main/java/org/elasticsearch/painless/symbol/SemanticScope.java
  modules/lang-painless/src/test/java/org/elasticsearch/painless/UserFunctionTests.java
Labels: >bug, :Core/Infra/Scripting, v8.0.0, Team:Core/Infra, auto-backport-and-merge, v8.1.0, v7.17.0, v7.16.3

#82233 [8.0] Fix Watcher testWatcherWithApiKey (#82136)
  x-pack/qa/full-cluster-restart/src/test/java/org/elasticsearch/xpack/restart/FullClusterRestartIT.java
Labels: backport, v8.0.0

#82231 [7.17] Fix Watcher testWatcherWithApiKey (#82136)
  x-pack/qa/full-cluster-restart/src/test/java/org/elasticsearch/xpack/restart/FullClusterRestartIT.java
Labels: backport, v7.17.0

#82230 [7.16] Fix Watcher testWatcherWithApiKey (#82136)
  x-pack/qa/full-cluster-restart/src/test/java/org/elasticsearch/xpack/restart/FullClusterRestartIT.java
Labels: backport, v7.16.3

#82235 [8.0] Script: track this pointer capture from blocks within lambdas (#82228)
  docs/changelog/82228.yaml
  modules/lang-painless/src/main/java/org/elasticsearch/painless/symbol/SemanticScope.java
  modules/lang-painless/src/test/java/org/elasticsearch/painless/UserFunctionTests.java
Labels: backport, v8.0.0, auto-merge

#82237 [7.16] Script: track this pointer capture from blocks within lambdas (#82228)
  docs/changelog/82228.yaml
  modules/lang-painless/src/main/java/org/elasticsearch/painless/symbol/SemanticScope.java
  modules/lang-painless/src/test/java/org/elasticsearch/painless/UserFunctionTests.java
Labels: backport, auto-merge, v7.16.3

#82236 [7.17] Script: track this pointer capture from blocks within lambdas (#82228)
  docs/changelog/82228.yaml
  modules/lang-painless/src/main/java/org/elasticsearch/painless/symbol/SemanticScope.java
  modules/lang-painless/src/test/java/org/elasticsearch/painless/UserFunctionTests.java
Labels: backport, auto-merge, v7.17.0

#82046 Allow read template with cluster monitor privilege
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/integration/ClusterPrivilegeIntegrationTests.java
Labels: >enhancement, :Data Management/Indices APIs, :Security/Authorization, v8.0.0, Team:Data Management, Team:Security, auto-merge, auto-backport-and-merge, v8.1.0, v7.17.0

#82243 [8.0] Allow read template with cluster monitor privilege (#82046)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/integration/ClusterPrivilegeIntegrationTests.java
Labels: backport, v8.0.0, auto-merge

#82244 Allow read template with cluster monitor privilege
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeTests.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java
  x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/integration/ClusterPrivilegeIntegrationTests.java
Labels: backport, v7.17.0

#82137 Add explicit "roles.yml" support to testclusters
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchCluster.java
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/TestClusterConfiguration.java
  x-pack/plugin/security/qa/security-basic/build.gradle
Labels: >test, :Delivery/Build, v8.0.0, Team:Delivery, v8.1.0

#82246 Add explicit "roles.yml" support to testclusters
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchCluster.java
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/TestClusterConfiguration.java
  x-pack/plugin/security/qa/security-basic/build.gradle
Labels: backport, v8.0.0, auto-merge

#82201 [7.17] [Transform] Report _preview warning in the face of pipeline failure. (#81972)
  x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformPivotRestIT.java
  x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportPreviewTransformAction.java
Labels: backport, v7.17.0

#82202 [7.16] [Transform] Report _preview warning in the face of pipeline failure. (#81972)
  x-pack/plugin/transform/qa/single-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/transform/integration/TransformPivotRestIT.java
  x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransportPreviewTransformAction.java
Labels: backport, v7.16.3

#82213 Check older source-only repos are supported
  x-pack/qa/repository-old-versions/src/test/java/org/elasticsearch/oldrepos/OldRepositoryAccessIT.java
Labels: >non-issue, :Search/Search, Team:Search, v8.1.0

#81940 Data tiers: migrate the coldest node attribute
  docs/reference/data-management/migrate-index-allocation-filters.asciidoc
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/DataTier.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/DataTierTests.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingService.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingServiceTests.java
Labels: >bug, :Data Management/ILM+SLM, v8.0.0, Team:Data Management, v8.1.0, v7.17.0

#82248 [7.17] Data tiers: migrate the coldest node attribute (#81940)
  docs/reference/data-management/migrate-index-allocation-filters.asciidoc
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/DataTier.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/DataTierTests.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingService.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingServiceTests.java
Labels: backport, auto-merge, v7.17.0

#82247 [8.0] Data tiers: migrate the coldest node attribute (#81940)
  docs/reference/data-management/migrate-index-allocation-filters.asciidoc
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/DataTier.java
  server/src/test/java/org/elasticsearch/cluster/routing/allocation/DataTierTests.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingService.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingServiceTests.java
Labels: backport, v8.0.0, auto-merge

#82249 Perform index checking in a caller thread
  server/src/main/java/org/elasticsearch/index/store/Store.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/store/input/BaseSearchableSnapshotIndexInput.java
Labels: >test, :Distributed/Snapshot/Restore, v8.0.0, Team:Distributed, auto-backport-and-merge, v8.1.0, v7.17.0

#82186 Update checkstyle to latest 8.x release
  build-conventions/build.gradle
  build-tools-internal/version.properties
Labels: >enhancement, :Delivery/Build, v8.0.0, Team:Delivery, auto-backport-and-merge, v8.1.0, build-benchmark, v7.17.0

#82252 [8.0] Perform index checking in a caller thread (#82249)
  server/src/main/java/org/elasticsearch/index/store/Store.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/store/input/BaseSearchableSnapshotIndexInput.java
Labels: backport, v8.0.0, auto-merge

#82254 [8.0] Update checkstyle to latest 8.x release (#82186)
  build-conventions/build.gradle
  build-tools-internal/version.properties
Labels: backport, v8.0.0, auto-merge

#82258 [7.17] Perform index checking in a caller thread (#82249)
  server/src/main/java/org/elasticsearch/index/store/Store.java
  x-pack/plugin/searchable-snapshots/src/internalClusterTest/java/org/elasticsearch/xpack/searchablesnapshots/FrozenSearchableSnapshotsIntegTests.java
  x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/store/input/BaseSearchableSnapshotIndexInput.java
Labels: backport, auto-merge, v7.17.0

#82226 Migrate to data tiers API dry run on any ILM status
  docs/reference/ilm/apis/migrate-to-data-tiers.asciidoc
  x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/MigrateToDataTiersIT.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingService.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/action/TransportMigrateToDataTiersAction.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingServiceTests.java
Labels: >enhancement, :Data Management/ILM+SLM, v8.0.0, Team:Data Management, v8.1.0, v7.17.0

#82261 [7.17] Migrate to data tiers API dry run on any ILM status (#82226)
  docs/reference/ilm/apis/migrate-to-data-tiers.asciidoc
  x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/MigrateToDataTiersIT.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingService.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/action/TransportMigrateToDataTiersAction.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/cluster/metadata/MetadataMigrateToDataTiersRoutingServiceTests.java
Labels: backport, auto-merge, v7.17.0

#82134 Fix Watcher ExecuteWatchQueuedStatsTests
  x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/execution/ExecuteWatchQueuedStatsTests.java
Labels: >test, :Data Management/Watcher, Team:Data Management, v8.1.0

#82259 [ML] Refactor ML usage action to reuse the trained model stats API
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/TrainedModelSizeStats.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MachineLearningUsageTransportAction.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/MachineLearningInfoTransportActionTests.java
Labels: >refactoring, :ml, Team:ML, v8.1.0

#82270 Make most Instances of o.e.c.Explict Singletons
  modules/legacy-geo/src/main/java/org/elasticsearch/legacygeo/mapper/LegacyGeoShapeFieldMapper.java
  plugins/mapper-size/src/main/java/org/elasticsearch/index/mapper/size/SizeFieldMapper.java
  server/src/main/java/org/elasticsearch/common/Explicit.java
  server/src/main/java/org/elasticsearch/common/xcontent/support/XContentMapValues.java
  server/src/main/java/org/elasticsearch/index/mapper/AbstractGeometryFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/AbstractShapeGeometryFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/MetadataFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/RangeFieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/RootObjectMapper.java
  server/src/test/java/org/elasticsearch/index/mapper/FieldAliasMapperValidationTests.java
  server/src/test/java/org/elasticsearch/index/mapper/MappingLookupTests.java
Labels: >non-issue, :Search/Mapping, Team:Search, v8.1.0

#81545 SQL: Add CCS SQL documentation
  docs/reference/search/search-your-data/search-across-clusters.asciidoc
  docs/reference/sql/apis/sql-search-api.asciidoc
  docs/reference/sql/endpoints/jdbc.asciidoc
  docs/reference/sql/language/indices.asciidoc
  docs/reference/sql/language/syntax/commands/describe-table.asciidoc
  docs/reference/sql/language/syntax/commands/index.asciidoc
  docs/reference/sql/language/syntax/commands/select.asciidoc
  docs/reference/sql/language/syntax/commands/show-catalogs.asciidoc
  docs/reference/sql/language/syntax/commands/show-columns.asciidoc
  docs/reference/sql/language/syntax/commands/show-functions.asciidoc
  docs/reference/sql/language/syntax/commands/show-tables.asciidoc
  x-pack/plugin/sql/qa/server/multi-cluster-with-security/src/test/java/org/elasticsearch/xpack/sql/qa/multi_cluster_with_security/JdbcCsvSpecIT.java
  x-pack/plugin/sql/qa/server/src/main/resources/multi-cluster-with-security/multi-cluster-command.csv-spec
  x-pack/plugin/sql/qa/server/src/main/resources/multi-cluster-with-security/multi-cluster-docs.csv-spec
Labels: >docs, >test, :Query Languages/SQL, v8.0.0, Team:Docs, Team:QL, auto-backport-and-merge, v8.1.0, v7.17.0, v7.16.3

#82276 [8.0] [DOCS] Custom routing for data streams
  docs/reference/docs/bulk.asciidoc
  docs/reference/docs/index_.asciidoc
  docs/reference/indices/put-index-template.asciidoc
  docs/reference/mapping/fields/routing-field.asciidoc
Labels: >docs, backport, v8.0.0, :Data Management/Data streams, Team:Data Management, Team:Docs

#82277 [8.0] SQL: Add CCS SQL documentation (#81545)
  docs/reference/search/search-your-data/search-across-clusters.asciidoc
  docs/reference/sql/apis/sql-search-api.asciidoc
  docs/reference/sql/endpoints/jdbc.asciidoc
  docs/reference/sql/language/indices.asciidoc
  docs/reference/sql/language/syntax/commands/describe-table.asciidoc
  docs/reference/sql/language/syntax/commands/index.asciidoc
  docs/reference/sql/language/syntax/commands/select.asciidoc
  docs/reference/sql/language/syntax/commands/show-catalogs.asciidoc
  docs/reference/sql/language/syntax/commands/show-columns.asciidoc
  docs/reference/sql/language/syntax/commands/show-functions.asciidoc
  docs/reference/sql/language/syntax/commands/show-tables.asciidoc
  x-pack/plugin/sql/qa/server/multi-cluster-with-security/src/test/java/org/elasticsearch/xpack/sql/qa/multi_cluster_with_security/JdbcCsvSpecIT.java
  x-pack/plugin/sql/qa/server/src/main/resources/multi-cluster-with-security/multi-cluster-command.csv-spec
  x-pack/plugin/sql/qa/server/src/main/resources/multi-cluster-with-security/multi-cluster-docs.csv-spec
Labels: backport, v8.0.0, auto-merge

#82284 [ML] test mute for issue #82279
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/FillMaskConfigUpdateTests.java
Labels: :ml, >test-mute, Team:ML, auto-merge, v8.1.0

#82282 SQL: Add CCS SQL documentation (#81545)
  docs/reference/search/search-your-data/search-across-clusters.asciidoc
  docs/reference/sql/apis/sql-search-api.asciidoc
  docs/reference/sql/endpoints/jdbc.asciidoc
  docs/reference/sql/language/indices.asciidoc
  docs/reference/sql/language/syntax/commands/describe-table.asciidoc
  docs/reference/sql/language/syntax/commands/index.asciidoc
  docs/reference/sql/language/syntax/commands/select.asciidoc
  docs/reference/sql/language/syntax/commands/show-catalogs.asciidoc
  docs/reference/sql/language/syntax/commands/show-columns.asciidoc
  docs/reference/sql/language/syntax/commands/show-functions.asciidoc
  docs/reference/sql/language/syntax/commands/show-tables.asciidoc
  x-pack/plugin/sql/qa/server/multi-cluster-with-security/src/test/java/org/elasticsearch/xpack/sql/qa/multi_cluster_with_security/JdbcCsvSpecIT.java
  x-pack/plugin/sql/qa/server/src/main/resources/multi-cluster-with-security/multi-cluster-command.csv-spec
  x-pack/plugin/sql/qa/server/src/main/resources/multi-cluster-with-security/multi-cluster-docs.csv-spec
Labels: backport, auto-merge, v7.16.3

#82275 Add scaled float to the scripting fields API
  docs/changelog/82275.yaml
  modules/lang-painless/src/main/resources/org/elasticsearch/painless/org.elasticsearch.script.fields.txt
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/50_script_doc_values.yml
  modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/ScaledFloatFieldMapper.java
  server/src/main/java/org/elasticsearch/script/field/ScaledFloatDocValuesField.java
  server/src/test/java/org/elasticsearch/index/fielddata/FloatDocValuesFieldTests.java
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra, v8.1.0

#82283 SQL: Add CCS SQL documentation (#81545)
  docs/reference/search/search-your-data/search-across-clusters.asciidoc
  docs/reference/sql/apis/sql-search-api.asciidoc
  docs/reference/sql/endpoints/jdbc.asciidoc
  docs/reference/sql/language/indices.asciidoc
  docs/reference/sql/language/syntax/commands/describe-table.asciidoc
  docs/reference/sql/language/syntax/commands/index.asciidoc
  docs/reference/sql/language/syntax/commands/select.asciidoc
  docs/reference/sql/language/syntax/commands/show-catalogs.asciidoc
  docs/reference/sql/language/syntax/commands/show-columns.asciidoc
  docs/reference/sql/language/syntax/commands/show-functions.asciidoc
  docs/reference/sql/language/syntax/commands/show-tables.asciidoc
  x-pack/plugin/sql/qa/server/multi-cluster-with-security/src/test/java/org/elasticsearch/xpack/sql/qa/multi_cluster_with_security/JdbcCsvSpecIT.java
  x-pack/plugin/sql/qa/server/src/main/resources/multi-cluster-with-security/multi-cluster-command.csv-spec
  x-pack/plugin/sql/qa/server/src/main/resources/multi-cluster-with-security/multi-cluster-docs.csv-spec
Labels: backport, auto-merge, v7.17.0

#82240 Make unchanged ILM policy updates into noop
  x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/IndexLifecycleInitialisationTests.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/action/TransportPutLifecycleAction.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportPutLifecycleActionTests.java
Labels: >enhancement, :Data Management/ILM+SLM, v8.0.0, Team:Data Management, auto-merge, auto-backport-and-merge, v8.1.0

#82293 [8.0] Make unchanged ILM policy updates into noop (#82240)
  x-pack/plugin/ilm/src/internalClusterTest/java/org/elasticsearch/xpack/ilm/IndexLifecycleInitialisationTests.java
  x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/action/TransportPutLifecycleAction.java
  x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/action/TransportPutLifecycleActionTests.java
Labels: backport, v8.0.0, auto-merge

#82288 Handle wrapped IO exceptions in test cluster distribution syncing
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
Labels: >non-issue, :Delivery/Build, v8.0.0, Team:Delivery, auto-merge, auto-backport-and-merge, v7.17.0, v7.16.3

#82300 [7.16] Handle wrapped IO exceptions in test cluster distribution syncing (#82288)
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
Labels: backport, auto-merge, v7.16.3

#82298 [8.0] Handle wrapped IO exceptions in test cluster distribution syncing (#82288)
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
Labels: backport, v8.0.0, auto-merge

#82299 [7.17] Handle wrapped IO exceptions in test cluster distribution syncing (#82288)
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
Labels: backport, auto-merge, v7.17.0

#82302 Add explicit "roles.yml" support to testclusters
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchCluster.java
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/TestClusterConfiguration.java
  x-pack/plugin/security/qa/security-basic/build.gradle
Labels: backport, auto-merge, v7.17.0

#82272 Make FieldNamesFieldMapper a Singleton in most Cases
  server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java
  server/src/main/java/org/elasticsearch/index/mapper/FieldNamesFieldMapper.java
Labels: >non-issue, :Search/Mapping, Team:Search, v8.1.0

#82271 [ML] Move datafeed stats action off of master node
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetDatafeedsStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportGetDatafeedsStatsAction.java
Labels: >enhancement, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0, v7.17.0

#82285 [ML] fix test #82279 FillMaskConfigUpdateTests#testApply
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/FillMaskConfigUpdateTests.java
Labels: >test, :ml, Team:ML, v8.1.0

#82305 [ML] Simplify the way ML legacy templates are removed
  x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/BasicDistributedJobsIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MachineLearning.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MlInitializationService.java
Labels: >refactoring, :ml, Team:ML, v8.1.0

#82292 Script: fields API for x-pack constant_keyword
  docs/changelog/82292.yaml
  server/src/main/java/org/elasticsearch/script/field/AbstractKeywordDocValuesField.java
  server/src/main/java/org/elasticsearch/script/field/KeywordDocValuesField.java
  x-pack/plugin/mapper-constant-keyword/build.gradle
  x-pack/plugin/mapper-constant-keyword/src/main/java/org/elasticsearch/xpack/constantkeyword/ConstantKeywordDocValuesField.java
  x-pack/plugin/mapper-constant-keyword/src/main/java/org/elasticsearch/xpack/constantkeyword/ConstantKeywordPainlessExtension.java
  x-pack/plugin/mapper-constant-keyword/src/main/java/org/elasticsearch/xpack/constantkeyword/mapper/ConstantKeywordFieldMapper.java
  x-pack/plugin/mapper-constant-keyword/src/main/resources/META-INF/services/org.elasticsearch.painless.spi.PainlessExtension
  x-pack/plugin/mapper-constant-keyword/src/main/resources/org/elasticsearch/xpack/constantkeyword/org.elasticsearch.xpack.constantkeyword.txt
  x-pack/plugin/mapper-constant-keyword/src/yamlRestTest/java/org/elasticsearch/xpack/constantkeyword/ConstantKeywordClientYamlTestSuiteIT.java
  x-pack/plugin/mapper-constant-keyword/src/yamlRestTest/resources/rest-api-spec/test/10_script_values.yml
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra, v8.1.0

#82304 [ML] Fix annotations index maintenance after reindexing
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/annotations/AnnotationIndex.java
  x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/AnnotationIndexIT.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/MlSingleNodeTestCase.java
Labels: >bug, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0, v7.17.0

#82251 Faster ShardsLimitAllocationDecider
  server/src/main/java/org/elasticsearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
Labels: >non-issue, :Distributed/Allocation, v8.0.0, Team:Distributed, auto-backport-and-merge, v8.1.0

#82195 add exception message to the failure details
  test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java
Labels: >test, :Distributed/Allocation, Team:Distributed, v8.1.0

#82308 [ML] Support updates to MPNet tokenizer
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/NlpConfigUpdate.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/NlpConfigUpdateTests.java
Labels: >non-issue, :ml, Team:ML, v8.1.0

#82309 [8.0] [ML] Fix annotations index maintenance after reindexing (#82304)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/annotations/AnnotationIndex.java
  x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/AnnotationIndexIT.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/MlSingleNodeTestCase.java
Labels: backport, v8.0.0, auto-merge

#82306 [8.0] [ML] Move datafeed stats action off of master node
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetDatafeedsStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportGetDatafeedsStatsAction.java
Labels: backport, v8.0.0

#82278 Fix concurrent serialization test for StoredScript
  server/src/main/java/org/elasticsearch/script/StoredScriptSource.java
  test/framework/src/main/java/org/elasticsearch/test/AbstractSerializingTestCase.java
Labels: >test, :Analytics/Aggregations, v8.0.0, Team:Analytics, auto-backport-and-merge, v8.1.0, v7.17.0

#82312 [7.17] [ML] Fix annotations index maintenance after reindexing
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/annotations/AnnotationIndex.java
  x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/AnnotationIndexIT.java
Labels: backport, v7.17.0

#82194 Search - reject arrays of values when passed to the Term query.
  server/src/main/java/org/elasticsearch/index/query/TermQueryBuilder.java
  server/src/test/java/org/elasticsearch/index/query/TermQueryBuilderTests.java
Labels: >bug, :Search/Search, v8.0.0, Team:Search

#82313 [ML] Fix typo
  x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/AnnotationIndexIT.java
Labels: >non-issue, :ml, v8.0.0, Team:ML, auto-backport-and-merge, v8.1.0, v7.17.0

#82307 [7.17] [ML] Move datafeed stats action off of master node
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/action/GetDatafeedsStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportGetDatafeedsStatsAction.java
Labels: backport, v7.17.0

#82314 [8.0] Fix concurrent serialization test for StoredScript (#82278)
  server/src/main/java/org/elasticsearch/script/StoredScriptSource.java
  test/framework/src/main/java/org/elasticsearch/test/AbstractSerializingTestCase.java
Labels: backport, v8.0.0, auto-merge

#82315 Fix concurrent serialization test for StoredScript (backport of #82278)
  test/framework/src/main/java/org/elasticsearch/test/AbstractSerializingTestCase.java
Labels: backport, auto-merge, v7.17.0

#82317 [8.0] [ML] Fix typo (#82313)
  x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/AnnotationIndexIT.java
Labels: backport, v8.0.0, auto-merge

#82318 [7.17] [ML] Fix typo (#82313)
  x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/AnnotationIndexIT.java
Labels: backport, auto-merge, v7.17.0

#82319 Search - reject arrays of values when passed to the Term query. (#82194)
  server/src/main/java/org/elasticsearch/index/query/TermQueryBuilder.java
  server/src/test/java/org/elasticsearch/index/query/TermQueryBuilderTests.java
Labels: >bug, backport, v8.0.0

#80106 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: >enhancement, Team:Core/Infra, v8.1.0

#82274 Use Java 8 for JDBC driver target compatibility version
  x-pack/plugin/sql/jdbc/build.gradle
  x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcConfiguration.java
  x-pack/plugin/sql/sql-client/build.gradle
  x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/StringUtils.java
  x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/UriUtils.java
  x-pack/plugin/sql/sql-proto/build.gradle
  x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/xcontent/ErrorOnUnknown.java
  x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/xcontent/ParsedMediaType.java
Labels: >refactoring, :Query Languages/SQL, v8.0.0, Team:QL, auto-backport-and-merge, v8.1.0

#82325 [8.0] Use Java 8 for JDBC driver target compatibility version (#82274)
  x-pack/plugin/sql/jdbc/build.gradle
  x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcConfiguration.java
  x-pack/plugin/sql/sql-client/build.gradle
  x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/StringUtils.java
  x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/UriUtils.java
  x-pack/plugin/sql/sql-proto/build.gradle
  x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/xcontent/ErrorOnUnknown.java
  x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/xcontent/ParsedMediaType.java
Labels: backport, v8.0.0, auto-merge

#81967 TSDB: fix reindex failed tests without feature flag
  modules/reindex/build.gradle
  plugins/analysis-icu/build.gradle
  plugins/mapper-annotated-text/build.gradle
  plugins/mapper-murmur3/build.gradle
  x-pack/plugin/analytics/build.gradle
  x-pack/plugin/mapper-aggregate-metric/build.gradle
  x-pack/plugin/mapper-constant-keyword/build.gradle
  x-pack/plugin/mapper-unsigned-long/build.gradle
  x-pack/plugin/mapper-version/build.gradle
  x-pack/plugin/spatial/build.gradle
  x-pack/plugin/vectors/build.gradle
  x-pack/plugin/wildcard/build.gradle
Labels: >bug, Team:Analytics, external-contributor, auto-merge, :Analytics/TSDB, auto-backport-and-merge, v8.1.0

#82232 [DOCS] Clarify document updates don't apply ingest pipelines
  docs/reference/ingest.asciidoc
Labels: >docs, :Data Management/Ingest, Team:Docs, external-contributor, v8.1.0, v8.0.0-beta1, v7.17.0, v7.16.3

#82328 [master] [DOCS] Clarify document updates don't apply ingest pipelines (#82232)
  docs/reference/ingest.asciidoc
Labels: backport, v8.1.0

#82330 [7.17] [DOCS] Clarify document updates don't apply ingest pipelines (#82232)
  docs/reference/ingest.asciidoc
Labels: backport, v7.17.0

#82329 [8.0] [DOCS] Clarify document updates don't apply ingest pipelines (#82232)
  docs/reference/ingest.asciidoc
Labels: backport, v8.0.0

#82238 Change TSDB sort order
  server/src/main/java/org/elasticsearch/index/IndexSortConfig.java
Labels: >non-issue, Team:Analytics, :Analytics/TSDB, test-release, v8.1.0

#82048 optimize duplicated code block in MetadataUpdateSettingsService
  server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/test/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsServiceTests.java
Labels: >enhancement, :Core/Infra/Settings, Team:Core/Infra, external-contributor, v8.1.0

#82053 [7.17] Allow to set the security manager Allow to set the security manager
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchTestBasePlugin.java
  distribution/tools/launchers/src/main/java/org/elasticsearch/tools/launchers/SystemJvmOptions.java
Labels: backport, v7.17.0

#82049 Add validation for API key role descriptors
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/CreateApiKeyRequest.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/role/PutRoleRequest.java
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/role/RoleDescriptorRequestValidator.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/action/CreateApiKeyRequestTests.java
Labels: >bug, :Security/Security, Team:Security, v8.1.0

#81964 Remove unused bwc variable from ApiKeyService
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/ApiKeyService.java
Labels: >non-issue, :Security/Security, Team:Security, v8.1.0

#82341 Java 17 instanceof pattern matching for modules
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ResolveAllDependencies.java
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java
  client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java
  client/rest-high-level/src/test/java/org/elasticsearch/test/RequestMatcher.java
  libs/core/src/main/java/org/elasticsearch/jdk/JarHell.java
  libs/lz4/src/test/java/org/elasticsearch/lz4/ESLZ4Tests.java
  libs/nio/src/main/java/org/elasticsearch/nio/NioSelector.java
  libs/ssl-config/src/main/java/org/elasticsearch/common/ssl/DiagnosticTrustManager.java
  libs/ssl-config/src/main/java/org/elasticsearch/common/ssl/KeyStoreUtil.java
  libs/ssl-config/src/main/java/org/elasticsearch/common/ssl/PemKeyConfig.java
  libs/x-content/src/main/java/org/elasticsearch/xcontent/support/MapXContentParser.java
  modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/SetProcessorTests.java
  modules/lang-mustache/src/main/java/org/elasticsearch/script/mustache/CustomReflectionObjectHandler.java
  modules/lang-painless/src/main/java/org/elasticsearch/painless/phase/DefaultIRTreeToASMBytesPhase.java
  modules/legacy-geo/src/test/java/org/elasticsearch/legacygeo/test/ElasticsearchGeoAssertions.java
  modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/RankFeatureQueryBuilder.java
  modules/percolator/src/main/java/org/elasticsearch/percolator/PercolatorFieldMapper.java
  modules/percolator/src/main/java/org/elasticsearch/percolator/QueryAnalyzer.java
  modules/reindex/src/main/java/org/elasticsearch/reindex/remote/RemoteRequestBuilders.java
  modules/reindex/src/main/java/org/elasticsearch/reindex/remote/RemoteScrollableHitSource.java
  modules/reindex/src/test/java/org/elasticsearch/reindex/AsyncBulkByScrollActionTests.java
  modules/repository-url/src/main/java/org/elasticsearch/common/blobstore/url/http/RetryingHttpInputStream.java
Labels: >non-issue, :Core/Infra/Core, >refactoring, v8.0.0, Team:Core/Infra, auto-backport-and-merge, v8.1.0

#82262 [7.17] Update checkstyle to latest 8.x release (#82186)
  build-conventions/build.gradle
  build-tools-internal/version.properties
Labels: backport, v7.17.0

#82207 Add doc values support for ES 5 and ES 6
  x-pack/plugin/old-lucene-versions/build.gradle
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/OldLuceneVersions.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/BWCCodec.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacyBinaryDocValues.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacyBinaryDocValuesWrapper.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacyDocValuesIterables.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacyNumericDocValues.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacyNumericDocValuesWrapper.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacySortedDocValues.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacySortedDocValuesWrapper.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacySortedNumericDocValues.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacySortedNumericDocValuesWrapper.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacySortedSetDocValues.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/index/LegacySortedSetDocValuesWrapper.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/lucene54/LegacyStringHelper.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/lucene54/Lucene54DocValuesConsumer.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/lucene54/Lucene54DocValuesFormat.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/lucene54/Lucene54DocValuesProducer.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/lucene60/Lucene60Codec.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/lucene62/Lucene62Codec.java
  x-pack/plugin/old-lucene-versions/src/main/java/org/elasticsearch/xpack/lucene/bwc/codecs/lucene70/BWCLucene70Codec.java
  x-pack/plugin/old-lucene-versions/src/main/resources/META-INF/services/org.apache.lucene.codecs.DocValuesFormat
  x-pack/plugin/old-lucene-versions/src/test/java/org/elasticsearch/xpack/lucene/bwc/codecs/lucene54/Lucene54DocValuesFormatTests.java
  x-pack/qa/repository-old-versions/src/test/java/org/elasticsearch/oldrepos/OldRepositoryAccessIT.java
Labels: >non-issue, :Search/Search, Team:Search, v8.1.0

#82347 [8.0] Java 17 instanceof pattern matching for modules (#82341)
  build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ResolveAllDependencies.java
  build-tools/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java
  client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java
  client/rest-high-level/src/test/java/org/elasticsearch/client/BulkProcessorRetryIT.java
  client/rest-high-level/src/test/java/org/elasticsearch/test/RequestMatcher.java
  libs/core/src/main/java/org/elasticsearch/jdk/JarHell.java
  libs/lz4/src/test/java/org/elasticsearch/lz4/ESLZ4Tests.java
  libs/nio/src/main/java/org/elasticsearch/nio/NioSelector.java
  libs/ssl-config/src/main/java/org/elasticsearch/common/ssl/DiagnosticTrustManager.java
  libs/ssl-config/src/main/java/org/elasticsearch/common/ssl/KeyStoreUtil.java
  libs/ssl-config/src/main/java/org/elasticsearch/common/ssl/PemKeyConfig.java
  libs/x-content/src/main/java/org/elasticsearch/xcontent/support/MapXContentParser.java
  modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/SetProcessorTests.java
  modules/lang-mustache/src/main/java/org/elasticsearch/script/mustache/CustomReflectionObjectHandler.java
  modules/lang-painless/src/main/java/org/elasticsearch/painless/phase/DefaultIRTreeToASMBytesPhase.java
  modules/legacy-geo/src/test/java/org/elasticsearch/legacygeo/test/ElasticsearchGeoAssertions.java
  modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/RankFeatureQueryBuilder.java
  modules/percolator/src/main/java/org/elasticsearch/percolator/PercolatorFieldMapper.java
  modules/percolator/src/main/java/org/elasticsearch/percolator/QueryAnalyzer.java
  modules/reindex/src/main/java/org/elasticsearch/reindex/remote/RemoteRequestBuilders.java
  modules/reindex/src/main/java/org/elasticsearch/reindex/remote/RemoteScrollableHitSource.java
  modules/reindex/src/test/java/org/elasticsearch/reindex/AsyncBulkByScrollActionTests.java
  modules/repository-url/src/main/java/org/elasticsearch/common/blobstore/url/http/RetryingHttpInputStream.java
Labels: backport, v8.0.0, auto-merge

#82349 Rollback switch expressions in the SQL plugin
  x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/TypeConverter.java
  x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/JreHttpUrlConnection.java
  x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/RemoteFailure.java
  x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/StringUtils.java
  x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/core/TimeValue.java
Labels: >non-issue, :Core/Infra/Core, Team:Core/Infra, v8.1.0

#82352 [ML] Correctly capture min stats for inference.ingest_processors in M…
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MachineLearningUsageTransportAction.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/MachineLearningInfoTransportActionTests.java
Labels: >bug, :ml, v8.0.0, Team:ML, v8.1.0, v7.17.0

#82332 [7.17] Fix failing URLDecodeProcessorTests::testProcessor test (#78690)
  modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/AbstractStringProcessorTestCase.java
Labels: >test, :Data Management/Ingest, backport, Team:Data Management, v7.17.0

#82363 [7.16] [TEST] Fix random RoleDescriptor compat with v6.7 (#82242)
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/RoleDescriptorTests.java
Labels: backport, auto-merge, v7.16.3

#81782 [DOCS] Add prerequisites for CCS
  docs/reference/modules/cluster/remote-clusters-settings.asciidoc
  docs/reference/modules/remote-clusters.asciidoc
  docs/reference/search/search-your-data/search-across-clusters.asciidoc
Labels: >docs, :Search/Search, Team:Docs, Team:Search, v8.1.0, v8.0.0-beta1, v7.17.0, v7.16.3

#82368 [7.17] [DOCS] Add prerequisites for CCS (#81782)
  docs/reference/modules/cluster/remote-clusters-settings.asciidoc
  docs/reference/modules/remote-clusters.asciidoc
  docs/reference/search/search-your-data/search-across-clusters.asciidoc
Labels: backport, auto-merge, v7.17.0

#82369 [7.16] [DOCS] Add prerequisites for CCS (#81782)
  docs/reference/modules/cluster/remote-clusters-settings.asciidoc
  docs/reference/modules/remote-clusters.asciidoc
  docs/reference/search/search-your-data/search-across-clusters.asciidoc
Labels: backport, auto-merge, v7.16.3

#82367 [8.0] [DOCS] Add prerequisites for CCS (#81782)
  docs/reference/modules/cluster/remote-clusters-settings.asciidoc
  docs/reference/modules/remote-clusters.asciidoc
  docs/reference/search/search-your-data/search-across-clusters.asciidoc
Labels: backport, v8.0.0, auto-merge

#81895 Convert empty _tier_preference setting index deprecate check to a cluster deprecation check
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecks.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/DeprecationChecks.java
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/IndexDeprecationChecks.java
  x-pack/plugin/deprecation/src/test/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecksTests.java
  x-pack/plugin/deprecation/src/test/java/org/elasticsearch/xpack/deprecation/IndexDeprecationChecksTests.java
Labels: >non-issue, :Data Management/ILM+SLM, Team:Data Management, v7.17.0

#82145 [ML] Warn when creating job with an unusual bucket span
  docs/reference/ml/ml-shared.asciidoc
  x-pack/plugin/build.gradle
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/config/Job.java
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/jobs_crud.yml
  x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/ml/jobs_get_result_overall_buckets.yml
  x-pack/qa/xpack-prefix-rest-compat/build.gradle
Labels: >enhancement, :ml, Team:ML, v8.1.0

#82362 [ML] optimize the job stats call to do fewer searches
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/process/autodetect/state/DataCounts.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/job/process/autodetect/state/DataCountsTests.java
  x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/JobResultsProviderIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportGetJobsStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProviderTests.java
Labels: >bug, :ml, v8.0.0, Team:ML, auto-merge, auto-backport-and-merge, v8.1.0

#82344 [DOCS] Fix typo
  docs/reference/aggregations/bucket/geodistance-aggregation.asciidoc
Labels: >docs, v8.0.0, Team:Docs, external-contributor, v8.1.0, v7.17.0, v7.16.3

#82375 Ignoring certain system templates with custom types
  x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecks.java
  x-pack/plugin/deprecation/src/test/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecksTests.java
Labels: >non-issue, :Data Management/Other, Team:Data Management, v7.17.0

#82379 [master] [DOCS] Fix typo (#82344)
  docs/reference/aggregations/bucket/geodistance-aggregation.asciidoc
Labels: backport, auto-merge, v8.1.0

#82381 [7.17] [DOCS] Fix typo (#82344)
  docs/reference/aggregations/bucket/geodistance-aggregation.asciidoc
Labels: backport, auto-merge, v7.17.0

#82380 [8.0] [DOCS] Fix typo (#82344)
  docs/reference/aggregations/bucket/geodistance-aggregation.asciidoc
Labels: backport, v8.0.0, auto-merge

#80468 remove nullable annotation in IndexShard constructor
  server/src/main/java/org/elasticsearch/index/shard/IndexShard.java
Labels: >non-issue, :Distributed/Distributed, >refactoring, v8.0.0, Team:Distributed, external-contributor, auto-backport, v8.1.0

#82377 [ML] ML usage inference ingest stats should be calculated per processor
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MachineLearningUsageTransportAction.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/MachineLearningInfoTransportActionTests.java
Labels: >non-issue, :ml, Team:ML, v8.1.0

#82294 Add half float mapping to the scripting fields API
  docs/changelog/82294.yaml
  modules/lang-painless/src/main/resources/org/elasticsearch/painless/org.elasticsearch.script.fields.txt
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/50_script_doc_values.yml
  server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/elasticsearch/script/field/HalfFloatDocValuesField.java
  server/src/test/java/org/elasticsearch/index/fielddata/FloatDocValuesFieldTests.java
Labels: >enhancement, :Core/Infra/Scripting, Team:Core/Infra, v8.1.0

#82378 [8.0] [ML] optimize the job stats call to do fewer searches (#82362)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/process/autodetect/state/DataCounts.java
  x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/job/process/autodetect/state/DataCountsTests.java
  x-pack/plugin/ml/src/internalClusterTest/java/org/elasticsearch/xpack/ml/integration/JobResultsProviderIT.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportGetJobsStatsAction.java
  x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java
  x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProviderTests.java
Labels: backport, v8.0.0, auto-merge

#82388 [DOCS] Adds ML release notes
  docs/reference/release-notes.asciidoc
  docs/reference/release-notes/8.0.0-rc1.asciidoc
Labels: >docs, :ml, v8.0.0, Team:Docs, Team:ML, auto-backport, v8.1.0

#82390 [8.0] [DOCS] Adds ML release notes (#82388)
  docs/reference/release-notes.asciidoc
  docs/reference/release-notes/8.0.0-rc1.asciidoc
Labels: backport, v8.0.0

#82297 [DOCS] Correct yaml syntax in example configuration
  docs/reference/modules/network.asciidoc
Labels: >docs, :Distributed/Network, v8.0.0, Team:Distributed, Team:Docs, external-contributor, v8.1.0, v7.17.0, v7.16.4

#82392 [master] [DOCS] Correct yaml syntax in example configuration (#82297)
  docs/reference/modules/network.asciidoc
Labels: backport, auto-merge, v8.1.0

#82394 [7.17] [DOCS] Correct yaml syntax in example configuration (#82297)
  docs/reference/modules/network.asciidoc
Labels: backport, auto-merge, v7.17.0

#82393 [8.0] [DOCS] Correct yaml syntax in example configuration (#82297)
  docs/reference/modules/network.asciidoc
Labels: backport, v8.0.0, auto-merge

#82386 [7.17] Make the rollover API respect the request's master_timeout (#82326)
  server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java
Labels: backport, v7.17.0

#82182 Add DEBUG log when DLS/FLS usage is detected
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/IndicesAccessControl.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/interceptor/DlsFlsLicenseRequestInterceptor.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/accesscontrol/IndicesAccessControlTests.java
Labels: >enhancement, :Security/Authorization, :Security/License, v8.0.0, Team:Security, auto-merge, auto-backport-and-merge, v8.1.0, v7.17.0

#82397 [8.0] Add DEBUG log when DLS/FLS usage is detected (#82182)
  x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/IndicesAccessControl.java
  x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/interceptor/DlsFlsLicenseRequestInterceptor.java
  x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authz/accesscontrol/IndicesAccessControlTests.java
Labels: backport, v8.0.0, auto-merge
